### ISSUE TITLE
Running CNN on raw features

### ISSUE THREAD

**Issue by nimz** [mravanelli/pytorch-kaldi#100]
Hello,

I am trying to run a CNN on the raw features. I found the config file here: https://bitbucket.org/mravanelli/pytorch-kaldi-exp-timit/src/master/TIMIT_baselines/TIMIT_CNN_raw/conf.cfg. (The config file TIMIT_CNN_raw.cfg in this repository is also for SincNet, which may be a mistake.) I followed the steps here https://github.com/mravanelli/pytorch-kaldi/issues/34 to fix `save_raw_fea.py` to account for the fact that there are only wav.scp files instead of wav.lst, and then ran `save_raw_fea.py` for each of train, dev, and test. After fixing my paths in the config file, I was able to run `python run_exp.py cfg/TIMIT_baselines/TIMIT_CNN_raw.cfg`, and training and validation works properly. However, when it comes time to forward, on the line `out_save=out_save-np.log(counts/np.sum(counts))` I get the error `ValueError: operands could not be broadcast together with shapes (129,1973) (1912,)`.

Indeed, `out_save.shape` is (129, 1973) while `counts.shape` is (1912,). In the [forward] section of my config file, I have `normalize_with_counts_from = lab_cd` as in the repository, but it seems that the output length does not match these counts. I tried replacing `forward_with` with `TIMIT_tr` and `TIMIT_dev` just to see if there was something specifically wrong with the test data, but I got similar errors (the second dimension of out_save is 1973 rather than 1912).

Note that I have run other models on fMLLR or mfcc features which worked fine, it's only raw features I am having trouble with.

What do I need to do - should I be generating a different counts file and normalizing with that, or is there some other issue?

**Comment by TParcollet** [comment]
Hi ! Could you post the cfg file that you are using ?

**Comment by nimz** [comment]
Thanks for the reply! Here is my config file: https://gist.github.com/nimz/01640d1a1abac3da087dd2bf1b2eb222

**Comment by TParcollet** [comment]
Weird to obtain different behaviors with the training phase and the forward phase. Could you please verify the output of hmm-info when applied to the model you are using for the alignement ? Is it 1973 or 1912 ? The thing is to understand where does this 1912 comes from. For this, check what is inside the cmd variable at line 619 of utils.py. And check if the output of this cmd is 1912 or 1973.

**Comment by mravanelli** [comment]
Hi, let me first of all  say that we are writing a new version of the code that can directly take in input raw audio data without the need of converting them into the kaldi format. In your case, I think that the issue is that you have trained the model with dnn_lay = 1973. If you replace it with " N_out_lab_cd" and you retrain the model it should work (see for instance cfg/TIMIT_baselines/TIMIT_CNN_raw.cfg). This way the system automatically detects the number of outputs from the labels. In your case the real number of output is 1912.

**Comment by nimz** [comment]
Thank you! Replaced with N_out_lab_cd and it works.
