### ISSUE TITLE
online speech recognition in pytorch-kaldi

### ISSUE THREAD

**Issue by shiva1393** [mravanelli/pytorch-kaldi#101]
online speech recognition is available in pytorch-kaldi? if not, how can we build online recognition with present architectures using  pytorch-kaldi.

**Comment by mravanelli** [comment]
Hi,
online speech recognition is not currently supported, but it is in our to
do list (we plan to do major changes/improvements of this project both this
summer and this fall).
The changes are the following:
1- the currently implemented model/ features normalization must consider
the online scenario, where we don't have access only to the past features
and not the future ones.
2- the posteriors should be sent to standard output and read by the on-line
kaldi decoder.

It is quite a bit of work actually...

Mirco
