### ISSUE TITLE
LSTM crashing GPU

### ISSUE THREAD

**Issue by mkperez808** [mravanelli/pytorch-kaldi#102]
Hey pytorch-kaldi team,
I’m getting a GPU error when attempting to run an adapted version of TIMIT_LSTM_fbank.cfg (altered to my own dataset). I am able to run my dataset using MLP with MFCCs however when I switch to using LSTM and MFB’s I get the following error message “Unable to determine the device handle for GPU 0000:4D:00.0: GPU is lost.  Reboot the system to recover this GPU”

Have you experienced this type of error before? Do the LSTM architectures require more computing power than the GPU’s I currently am using? I am able to run GRU architecture fine. 

I have also tried turning off GPU 2, which seems to be the GPU in question however, the script then begins training without GPU’s (CPU only).

I've also attached the cfg file below (as a txt for the purposes of GitHub).

Best,
Matt

<img width="616" alt="Screen Shot 2019-05-23 at 6 11 19 PM" src="https://user-images.githubusercontent.com/38544838/58352593-b8b12a00-7e07-11e9-8c3a-b3fb658f5de5.png">
[LSTM_MFB copy.txt](https://github.com/mravanelli/pytorch-kaldi/files/3218357/LSTM_MFB.copy.txt)

**Comment by TParcollet** [comment]
LSTM are more memory demanding that GRU, but they should not literally kill your GPU. I see that you are using multi-gpu training. Considering your hardware configuration, I would suggest you to run only on two identical GPUs (so you have the same amount of VRAM). You can use the CUDA_VISIBLE_DEVICES env variable to hide the 1080 or the Titan X. Is everything running fine with the GRU on 4 GPUs ? If yes, could you report an nvidia-smi of such a case ? Heterogeneous hardware have not been tested, this is why I recommend using a pair of identical GPUs.

**Comment by mkperez808** [comment]
When using just the Titan X's, I am now running into CUDA out of memory errors. Can this be addressed by simply reducing batch size? 

Thank you for your help!

**Comment by TParcollet** [comment]
Many options influence the memory consumption. To find the adequate batch size, I would suggest you to set the increase_seq_length_train to False and the max_seq_length_train to 500. Then, you lower the batch_size until one entire epoch is completed with OOM.

**Comment by mravanelli** [comment]
Yes, Titouan is right. Could you post your config file?

Mirco

**Comment by mkperez808** [comment]
Reducing batch size, setting increase_seg_length_train=False, and reducing max_seq_length_train worked. Thank you for solving the issue. I'll attach the config file anyways. Thank you for your help!


[LSTM_MFB.txt](https://github.com/mravanelli/pytorch-kaldi/files/3242321/LSTM_MFB.txt)

**Comment by TParcollet** [comment]
@mkperez808 Nonetheless, you can reset increase_seq_length to True once you found the right batch_size.
