### ISSUE TITLE
question about logprob

### ISSUE THREAD

**Issue by wentaoxandry** [mravanelli/pytorch-kaldi#104]
Hello, 

I have a question, I want do some processing with logprob after network training. 
What I want to do is convert the logprob to posteriori, I want to ask if the network has a constant prior(just like kaldi nnet2 and nnet3) or with different prior(like kaldi nnet)?

Thank you
Wentao

**Comment by mravanelli** [comment]
Sure,
the network estimates posterior probabilities (see out_save in line 228 of
core.py). Before feeding the decoder, these posteriors must be scaled with
the prior probability (see line 223 of core.py). The prior probability is
fixed and it is derived from counts of the phone states present in the
considered labels.

Mirco

**Comment by wentaoxandry** [comment]
Ok, I understand, thank you for your help
