### ISSUE TITLE
When installing using conda, A majority of the classes are not found.

### ISSUE THREAD

**Issue by zachadasm16** [mravanelli/pytorch-kaldi#106]
All of the classes with Options at the end like (BiglmFasterDecoderOption) are not found and python says there is no reference of them in __init__.py. Also, from kaldi.feats.mfcc import Mfcc is not found and many other classes. I was wondering if there is a way to fix this because I have been playing around for it for a bit and cannot find a solution to this problem. Do you suggest reinstalling pykaldi or is there another option? 

Thank you,
Zach

**Comment by mravanelli** [comment]
Hi,
have you solved it?

Mirco

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
