### ISSUE TITLE
Confused with the label processing: why subtract lab idxs by the minimal idx in this thunk

### ISSUE THREAD

**Issue by JerryPeng21cuhk** [mravanelli/pytorch-kaldi#107]
I am getting start with pytorch-kaldi to do NN training so my question might be naive.

why should we substract all the label ids which are usually integers by the minimal label id in the current chunk ? Is it a trick for training ?

https://github.com/mravanelli/pytorch-kaldi/blob/f2c4c3a420a21c6186a9c3c3d305583cd5fe73d7/data_io.py#L136

**Comment by mravanelli** [comment]
HI Jerry,
this is not really a trick. This line is just written to make sure that the
labels ids are withing the range 0-N_lab-1 (as the software later expects)
and not in other ranges such as 1-N_lab.

Mirco

**Comment by JerryPeng21cuhk** [comment]
Does it lead to training problems if chunk size is not that large (what if label 0 is included in some chunks) ?

**Comment by mravanelli** [comment]
In general not because in kaldi the label "1" is the one related to silence
that is always present. In the new version I'm developing , however, I'm
loading all the labels of all the chunks since the beginning and this
cannot happen in any case.

Mirco

**Comment by JerryPeng21cuhk** [comment]
I see. Thanks~
