### ISSUE TITLE
When running TIMIT_mfcc_fbank_fmllr_liGRU_best.cfg I get this error and have checked everything and cannot figure it out

### ISSUE THREAD

**Issue by zachadasm16** [mravanelli/pytorch-kaldi#108]
![Capture](https://user-images.githubusercontent.com/39277460/59062774-a6f26c80-8874-11e9-8c00-5a8da4e36c6b.PNG)

**Comment by zachadasm16** [comment]
I feel like it has something to do with my fmllr data

**Comment by zachadasm16** [comment]
also are should cw_left and cw_right stay at 0 in this cfg

**Comment by zachadasm16** [comment]
Also do the files have to be in specific folders?

**Comment by TParcollet** [comment]
Hi, please attach or paste your CFG file. This might be a problem related to the path of your features. Consequently, double-check the path of the *.scp files.
