### ISSUE TITLE
Failed to open script file /mfcc_shu/train_split.000

### ISSUE THREAD

**Issue by nahidbrur** [mravanelli/pytorch-kaldi#11]
Hello and thank you for this useful project. I try to run timit experiment following your instructions using tri3 alignments. But it returns following error - WARNING (copy-feats[5.4]:Open():util/kaldi-table-inl.h:106) Failed to open script file /mfcc_shu/train_split.000.

Here are the conf and log file:

[conf&log.zip](https://github.com/mravanelli/pytorch-kaldi/files/2180518/conf.log.zip)

what should i do now. Thanks advance.

**Comment by mravanelli** [comment]
Hi, thank you for the interest in my project! It likely only a path
problem. Just check if the file "  /mfcc_shu/train_split.000" and all the
files included into it actually exists.

**Comment by nahidbrur** [comment]
thank you for your response. problem solved.
