### ISSUE TITLE
load pre_trained model from Kaldi

### ISSUE THREAD

**Issue by yyyyxie** [mravanelli/pytorch-kaldi#111]
Hi,
Thank you for this useful toolkit. I have a question: I know there are several models we can download from Kaldi website, if there is any way I can load pre-trained model from Kaldi into tytorch nn framework?

**Comment by mravanelli** [comment]
Hi,
this feature could be very useful, but it is not currently supported.

Best,

Mirco

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
