### ISSUE TITLE
problem while rescoring with librispeech data set

### ISSUE THREAD

**Issue by shiva1393** [mravanelli/pytorch-kaldi#115]
by following pytorch-kaldi tutorial for librispeech fmllr features.
kaldi_decoding_scripts/decode_dnn.sh and for scoring script kaldi/egs/librispeech/s5/local/score.sh used. Then if use steps/lmrescore_const_arpa.sh it will ask glm and stm files.
can any one help which scripts help for librispeech lmrescore.

**Comment by TParcollet** [comment]
Hi ! stm and glm files are for scoring, they should exist in your data folder of librispeech. Could you 1) verify that you exactly followed the steps for rescoring from the tutorial 2) Post the error message ?

**Comment by shiva1393** [comment]
I followed cfg/librispeech_baselines/libri_ligru_fmllr.cfg file. upto decoding it is fine.
For lmrescore 
code iam following from pytorch-kaldi 
data_dir=data/
dec_dir=exp_librispeech/libri_liGRU_fmllr/decode_test_clean_out_dnn2/
out_dir=exp_librispeech/libri_liGRU_fmllr/

steps/lmrescore_const_arpa.sh  $data_dir/lang_test_{tgsmall,fglarge} \
          $data_dir/test_clean $dec_dir $out_dir/decode_test_clean_fglarge
Error: 
getting : Cannot open transcription file '/data/shiva/kaldi/librispeech/data_libri/data//test_clean/stm': No such file or directory at local/timit_norm_trans.pl line 74, <M> line 61.
cp: cannot stat '/data/shiva/kaldi/librispeech/data_libri/data//test_clean/glm': No such file or directory

while running timit/run.sh we will get stm and glm files.for librispeech/run.sh we won't get stm and glm files.
cfg file decoding information:
decoding_script_folder=kaldi_decoding_scripts/
decoding_script=decode_dnn.sh
decoding_proto=proto/decoding.proto
min_active=200
max_active=7000
max_mem=50000000
beam=20.0
latbeam=12.0
acwt=0.10
max_arcs=-1
skip_scoring=false
scoring_script=/home/user/kaldi/egs/librispeech/s5/local/score.sh
scoring_opts="--min-lmwt 4 --max-lmwt 23"
norm_vars=False

**Comment by TParcollet** [comment]
well, data_dir must be the absolute path to the data folder of the egs/librispeech/s5 recipe. Is it the case for you ? Then, are you running the rescoring from the egs/librispeech/s5 root ?

**Comment by shiva1393** [comment]
actually pytorch-kaldi/kaldi_decoding_scripts/steps not exist so steps copied from wsj/ to  pytorch-kaldi/kaldi_decoding_scripts/ then iam running  steps/lmrescore_const_arpa.sh in pytorch-kaldi/kaldi_decoding_scripts/ folder.

**Comment by TParcollet** [comment]
You must run all these cmd from the Kaldi environment:  kaldi/egs/librispeech/s5

**Comment by TParcollet** [comment]
I would advice you to run these cmd on the Kaldi environment: kaldi/egs/librispeech/s5 .

**Comment by shiva1393** [comment]
which decoding script i should use instead of  pytorch-kaldi/kaldi_decoding_scripts/decode_dnn.sh

**Comment by TParcollet** [comment]
You must distinguish two things:
1) First decoding pass
2) Rescoring
-------

The 1) is done with pytorch-kaldi/kaldi_decoding_scripts/decode_dnn.sh that generates the exp/decode_youexperiment_name folder. In this folder, you can find the lattices (lat.*.gz) that correspond to the "paths" of the decoder.

Then, you move to you go to your librispeech kaldi environment (or you copy the lmrescore script as you did) and you give to the script these parameters:

- data_dir= absolute path to the KALDI data. The same you used for training (.cfg file). Usually it's you_directory/kaldi/egs/librispeech/s5/data/{test/dev/train} depending on what you want to rescore.
- dec_dir= absolute path to the output of step 1) usually it's exp/myexp/decode_mydataset . Unless you changed it on the cfg file.
- out_dir= Well, it's just the final output directory.

**Comment by shiva1393** [comment]
Thank you ... Now it is working fine..
