### ISSUE TITLE
need some explanation for arch_pretrain_file 

### ISSUE THREAD

**Issue by shiva1393** [mravanelli/pytorch-kaldi#116]
Hello sir,
i have pretrained file from pytorch-kaldi (ex : architecture1.pkl) for  "dataset1".
if i want to use this same weights for  "dataset2" with same network.
can i load arch_pretrain_file=architecture1.pkl. 
doubt is initially dataset2 initialize weights with architecture1.pkl.
it is right?

**Comment by TParcollet** [comment]
It will. arch_pretrain_file initialize the target architecture with the file specified. I've never used it personally before @mravanelli could answer you more precisely. 

You can also use the freeze parameter to activate the fine-tuning or not.

**Comment by mravanelli** [comment]
Hi,
as outlined by Titouan, if you initialize the weights with
arch_pretrain_file=architecture1.pkl the weights will be initialized and
changed during training. If you would like to keep unchanged the weights
during training, you can freeze the weights with "arch_freeze=True".
