### ISSUE TITLE
Unable to run run_exp.sh with liGRU_mfcc

### ISSUE THREAD

**Issue by ottj** [mravanelli/pytorch-kaldi#12]
Hi Mirco,

I am trying to reproduce the li-GRU results on the TIMIT dataset in your paper. For this I followed the readme and changed all relevant paths in the liGRU_mfcc.cfg. Training with './run_exp.sh cfg/baselines/liGRU_mfcc.cfg'  runs fine, but as soon as it goes to the next step I get the following error:

bash: line 1: 63283 Aborted                 (core dumped) ( latgen-faster-mapped --min-active=200 --max-active=7000 --max-mem=50000000 --beam=13.0 --lattice-beam=8.0 --acoustic-scale=0.2 --allow-partial=true --word-symbol-table=/home/algo-phd-01/tools/kaldi/egs/timit/s5/exp/tri3/graph/words.txt /home/algo-phd-01/tools/kaldi/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_ali/final.mdl /home/algo-phd-01/tools/kaldi/egs/timit/s5/exp/tri3/graph/HCLG.fst "ark,s,cs:cat ..//home/algo-phd-01/workspace/phd/benchmarking/pytorch-kaldi/exp/TIMIT_liGRU_official_v1/forward_ep_24_ck_4.pkl |" "ark:|gzip -c > ..//home/algo-phd-01/workspace/phd/benchmarking/pytorch-kaldi/exp/TIMIT_liGRU_official_v1/decoding_test/lat.1.gz" ) 2>> ..//home/algo-phd-01/workspace/phd/benchmarking/pytorch-kaldi/exp/TIMIT_liGRU_official_v1/decoding_test/log/decode.1.log >> ..//home/algo-phd-01/workspace/phd/benchmarking/pytorch-kaldi/exp/TIMIT_liGRU_official_v1/decoding_test/log/decode.1.log
run.pl: job failed, log is in ..//home/algo-phd-01/workspace/phd/benchmarking/pytorch-kaldi/exp/TIMIT_liGRU_official_v1/decoding_test/log/decode.1.log
run.pl: job failed, log is in ..//home/algo-phd-01/workspace/phd/benchmarking/pytorch-kaldi/exp/TIMIT_liGRU_official_v1/decoding_test/scoring/log/best_path.1.1.log

The two log files at the end of the error don't exist. When I run latgen-faster-mapped with all parameters directly I get this error:

latgen-faster-mapped --min-active=200 --max-active=7000 --max-mem=50000000 --beam=13.0 --lattice-beam=8.0 --acoustic-scale=0.2 --allow-partial=true --word-symbol-table=/home/algo-phd-01/tools/kaldi/egs/timit/s5/exp/tri3/graph/words.txt /home/algo-phd-01/tools/kaldi/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_ali/final.mdl /home/algo-phd-01/tools/kaldi/egs/timit/s5/exp/tri3/graph/HCLG.fst "ark,s,cs:cat ..//home/algo-phd-01/workspace/phd/benchmarking/pytorch-kaldi/exp/TIMIT_liGRU_official_v1/forward_ep_24_ck_4.pkl |"  "ark:|gzip -c > ..//home/algo-phd-01/workspace/phd/benchmarking/pytorch-kaldi/exp/TIMIT_liGRU_official_v1/decoding_test/lat.JOB.gz"
latgen-faster-mapped --min-active=200 --max-active=7000 --max-mem=50000000 --beam=13.0 --lattice-beam=8.0 --acoustic-scale=0.2 --allow-partial=true --word-symbol-table=/home/algo-phd-01/tools/kaldi/egs/timit/s5/exp/tri3/graph/words.txt /home/algo-phd-01/tools/kaldi/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_ali/final.mdl /home/algo-phd-01/tools/kaldi/egs/timit/s5/exp/tri3/graph/HCLG.fst 'ark,s,cs:cat ..//home/algo-phd-01/workspace/phd/benchmarking/pytorch-kaldi/exp/TIMIT_liGRU_official_v1/forward_ep_24_ck_4.pkl |' 'ark:|gzip -c > ..//home/algo-phd-01/workspace/phd/benchmarking/pytorch-kaldi/exp/TIMIT_liGRU_official_v1/decoding_test/lat.JOB.gz' 
cat: ..//home/algo-phd-01/workspace/phd/benchmarking/pytorch-kaldi/exp/TIMIT_liGRU_official_v1/forward_ep_24_ck_4.pkl: No such file or directory
WARNING (latgen-faster-mapped[5.4.198~1-be7c1]:Close():kaldi-io.cc:515) Pipe cat ..//home/algo-phd-01/workspace/phd/benchmarking/pytorch-kaldi/exp/TIMIT_liGRU_official_v1/forward_ep_24_ck_4.pkl | had nonzero return status 256
ERROR (latgen-faster-mapped[5.4.198~1-be7c1]:~SequentialTableReaderArchiveImpl():util/kaldi-table-inl.h:678) TableReader: error detected closing archive 'cat ..//home/algo-phd-01/workspace/phd/benchmarking/pytorch-kaldi/exp/TIMIT_liGRU_official_v1/forward_ep_24_ck_4.pkl |'

[ Stack-Trace: ]
latgen-faster-mapped() [0xb1aae0]
kaldi::MessageLogger::HandleMessage(kaldi::LogMessageEnvelope const&, char const*)
kaldi::MessageLogger::~MessageLogger()
kaldi::SequentialTableReaderArchiveImpl<kaldi::KaldiObjectHolder<kaldi::Matrix<float> > >::~SequentialTableReaderArchiveImpl()
kaldi::SequentialTableReaderArchiveImpl<kaldi::KaldiObjectHolder<kaldi::Matrix<float> > >::~SequentialTableReaderArchiveImpl()
kaldi::SequentialTableReader<kaldi::KaldiObjectHolder<kaldi::Matrix<float> > >::~SequentialTableReader()
main
__libc_start_main
_start

terminate called after throwing an instance of 'std::runtime_error'
  what():  
Aborted (core dumped)

**Comment by mravanelli** [comment]
Hi Joachim,
does " /home/algo-phd-01/workspace/phd/benchmarking/
pytorch-kaldi/exp/TIMIT_liGRU_official_v1/forward_ep_24_ck_4.pkl " exists?
This file is a binary ark containing the set of posterior probabilities and
it is created during the forward phase. The file should be quite big, if
it's empty it's is likely something went wrong during the forward phase....

Mirco

**Comment by ottj** [comment]
Yes, it exists and is about 426MB
also, the forward_ep_24_ck_4.info has this content:
model_in=/home/algo-phd-01/workspace/phd/benchmarking/pytorch-kaldi/exp/TIMIT_liGRU_official_v1/train_ep_24_ck_4.pkl
fea_in=/home/algo-phd-01/workspace/phd/benchmarking/pytorch-kaldi/mfcc_ord/test_split.000
loss=1.450169
err=0.357555
elapsed_time=76.966896

**Comment by mravanelli** [comment]
OK, so we are at least reasonably sure that it's only a decoding problem. That's a weird error. Errors like this might happen when paths/libraries are not set up correctly. It could be good to check for instance if kaldi_decoding_scripts/path.sh actually points to the right libs....

**Comment by ottj** [comment]
It was indeed a path issue. 'out_folder' must not be an absolute path apparently. I had it set to /home/algo-phd-01/workspace/phd/benchmarking/pytorch-kaldi/exp/TIMIT_liGRU_official_v1
After changing to the relative
exp/TIMIT_liGRU_official_v1
it works fine. 
[even better would be exp/myresults/TIMIT_liGRU_official_v1 then I would not have to change the RESULTS scripts]
I got these results
%WER 15.5 | 192 7215 | 87.0 9.9 3.1 2.5 15.5 99.0 | -1.944 | exp/TIMIT_liGRU_official_v1/decoding_test/score_4/ctm_39phn.filt.sys
which are very close to yours, hence I consider them reproduced.

Thank you for releasing the code and for the help with the path issue.
