### ISSUE TITLE
MFCC audio feature

### ISSUE THREAD

**Issue by trahman888** [mravanelli/pytorch-kaldi#120]
I am new in audio processing. I read audio file using [fs,signal]=scipy.io.wavfile.read(audio_file_name) where fs=44100 and signal contains (2428928, 2) array.  Therefore the total frame become at the end as a (15179, 3200, 2) dimensional array. Is it okay? What is the representation of this three dimensions for deep neural network?

**Comment by mravanelli** [comment]
Hi,
thank yuo very much for your interest into the project.
Are you  referring to the SincNet model or to something else? If so, in
SincNet we use windows of 200 ms (i.e. 3200 samples) shifted with 10 ms
(i.e., 160 samples). This means that your signal should have the
dimensionality you pointed out.

Mirco

**Comment by trahman888** [comment]
Thanks for your clarification. Actually I want to use GRU to the audio feature. In that case is the dimension ok? Or we need to force the audio signal down to mono like librosa. 

Also another question, according to my understanding SincNet works well as it uses bandpass filter to reduce unwanted noise. So can I use SincNet as a pre-process to reduce noise from mfcc features and later use that features for further processing?

**Comment by TParcollet** [comment]
@trahman888 Hi, you can use SyncNet to extract features, but you need it to be trained before extracting. Nonetheless, you can try to combine a GRU with SyncNet.

**Comment by trahman888** [comment]
Yes, I found pretrain weight for SincNet in the following link:
[https://bitbucket.org/mravanelli/sincnet_models/src/master/](https://bitbucket.org/mravanelli/sincnet_models/src/master/)
