### ISSUE TITLE
Regarding Light Gated Recurrent Units for Speech Recognition paper 

### ISSUE THREAD

**Issue by shiva1393** [mravanelli/pytorch-kaldi#122]
Hello Sir,
      I read the Light Gated Recurrent Units for Speech Recognition and pytorch kaldi, In both papers architectures are same but pytorch-kaldi  getting better results.Please can you tell the reason?

**Comment by mravanelli** [comment]
Hi,
the Light GRU paper refers to an old implementation written in Theano. When
we did the porting to the recent PyTorch-Kaldi we took the opportunity to
better tune the hyperparameters with better results for all the RNN models
implemented.

Best,

Mirco

**Comment by shiva1393** [comment]
Thank you
