### ISSUE TITLE
Running pytorch-kaldi in clusters

### ISSUE THREAD

**Issue by Subash33** [mravanelli/pytorch-kaldi#125]
Hello, 

This is not really the pytorch-kaldi related issue I know, but since I am stuck at this for a week now, I am asking it anyway. I  was running one liGRU_fmllr experiment in 80 CPU cluster amazon node, with training chunks (15), test and dev (10), cuda= False, multi-GPU= False configuration as I had only CPUs in it. It has to do with how I set up the experiment maybe but for three days so far, I could not go beyond 2 epochs, for medium size dataset of mine it is totally unreasonable. What am I doing wrong here? The process is running utilizing 0.2% memory and  300-400 %CPU. 

Do you think running this experiment in single GPU computer with Cuda set to True would be more reasonable instead? However, currently I am getting segmentation error in the single GPU system, I am yet to resolve that. The experiments were running fine before. As I read somewhere recloning and reinstalling the pytorch-kaldi might help to resolve it. Any other suggestions on it?

As an alternative, I shifted to HPC cluster-based environment using singularity, I used nvidia docker image as a base to build my kaldi image. In my node, getting inside the kaldi container, I now have run the Kaldi part and the required alignments and graph are in the desired location. I created the pytorch-kaldi container and was now trying to submit my job(the liGRU_fmllr experiment) in it. I am thrown the hmm-info not found error. The path are correct, even the ~/.bashrc has the correct paths in it. When I looked into kaldi/src/lib I could see the softlinks are broken, even though I copied libkaldi-base.so from kaldi/src/base to kaldi/src/lib (As someone in kaldi help group said it fixed the issue), the path error still persists.

Now I am unable to run experiments in either of the platforms, single GPU, CPU cluster or HPC clusters. 

Apologies for the issue being not pytorch specific but any help would be highly appreciated.

Subash

**Comment by TParcollet** [comment]
Hi !

> This is not really the pytorch-kaldi related issue I know, but since I am stuck at this for a week now, I am asking it anyway. I was running one liGRU_fmllr experiment in 80 CPU cluster amazon node, with training chunks (15), test and dev (10), cuda= False, multi-GPU= False configuration as I had only CPUs in it. It has to do with how I set up the experiment maybe but for three days so far, I could not go beyond 2 epochs, for medium size dataset of mine it is totally unreasonable. What am I doing wrong here? The process is running utilizing 0.2% memory and 300-400 %CPU.

Well, this is a problem of Pytorch-Kaldi. With haven't implemented "DistributedDataParallelCPU" yet. So the inference is only done on a single core ... You can try to manually add it and then share with us ! Check Dataparallel in core.py. You might need to change the global proto also for a variable in the conf.file 

> Do you think running this experiment in single GPU computer with Cuda set to True would be more reasonable instead? However, currently I am getting segmentation error in the single GPU system, I am yet to resolve that. The experiments were running fine before. As I read somewhere recloning and reinstalling the pytorch-kaldi might help to resolve it. Any other suggestions on it?

GPU are way faster for training with big architectures. We need more informations on this error if you want us to help ! 

> As an alternative, I shifted to HPC cluster-based environment using singularity, I used nvidia docker image as a base to build my kaldi image. In my node, getting inside the kaldi container, I now have run the Kaldi part and the required alignments and graph are in the desired location. I created the pytorch-kaldi container and was now trying to submit my job(the liGRU_fmllr experiment) in it. I am thrown the hmm-info not found error. The path are correct, even the ~/.bashrc has the correct paths in it. When I looked into kaldi/src/lib I could see the softlinks are broken, even though I copied libkaldi-base.so from kaldi/src/base to kaldi/src/lib (As someone in kaldi help group said it fixed the issue), the path error still persists.

Kaldi is a pain on ... when it comes to moving an already compiled version ... Can't you compile a locl version on the cluster ?
