### ISSUE TITLE
final.mdl production

### ISSUE THREAD

**Issue by shiva1393** [mravanelli/pytorch-kaldi#139]
Hi Sir,
       How final.mdl is  producing in this tool kit.By searching in code i didn't get how final.mdl is present in output folder at decoding stage.

**Comment by TParcollet** [comment]
the final.mdl file is a a copied version of the one used to generate the alignement (see decode_dnn.sh in kaldi_decoding_scripts)

**Comment by shiva1393** [comment]
Sir,if possible can you suggest how we can get final_architecture*.pkl format to final.mdl conversion (means kaldi format).

**Comment by TParcollet** [comment]
It is not possible in the current toolkit. The .pkl contains all the parameters for the trained PyTorch model, it is consequently not feasible to use it as a "Kaldi" model. If you are interested in deploying a trained model, please refer to the "How can I transcript my own audio files" section of the readme.

**Comment by shiva1393** [comment]
Thank you sir, For new data without alignment file.
hmm-info /path/to/the/final.mdl
N_out_lab_cd=number of pdfs .
it is correct right?

**Comment by TParcollet** [comment]
You must replace all the N_out_{smth} by the true pdfs obtained with hmm-info, yes.

**Comment by shiva1393** [comment]
Thank you sir
