### ISSUE TITLE
Problem with 'multply_factor_seq_len_train'

### ISSUE THREAD

**Issue by PeiyanFlying** [mravanelli/pytorch-kaldi#148]
Dear Sir,
Now due to my own task, I have to set the parameter 'n_epochs_tr' >=200 or  'n_epochs_tr' >=400. But if I set that big number, that might result in 'out of memory'. 
(I also set :
increase_seq_length_train = True
start_seq_len_train = 100
multply_factor_seq_len_train = 2)

So If I want to set a parameter ---- 'seq_len_above_theshold', the longest sentence the system can support. How can I do that?

Many thanks!

**Comment by mravanelli** [comment]
Hi,
the number of epochs shouldn't affect the memory. The GPU memory is mainly
affected by the batch size and, in the case of recurrent neural networks,
by the sequence length. You can try to run the code for few iterations
changing the batch size or the maximum sequence length.

Best,

Mirco

**Comment by PeiyanFlying** [comment]
I see... Many thanks. I got it clearly~
