### ISSUE TITLE
when run decode_dnn_TIMIT.sh, I meet bash : line 49185 Aborted (core dumped)

### ISSUE THREAD

**Issue by kidconan** [mravanelli/pytorch-kaldi#15]
./decode_dnn_TIMIT.sh /home/gkb/Download/kaldi/egs/timit/s5/exp/tri3/graph /home/gkb/Download/kaldi/egs/timit/s5/data/test/ /home/gkb/Download/kaldi/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_ali ..//home/gkb/torch_kaldi_exp/exp/TIMIT_MLP/decoding_test cat ..//home/gkb/torch_kaldi_exp/exp/TIMIT_MLP/forward_ep_24_ck_4.pkl
bash: line 1: 49185 Aborted                 (core dumped) ( latgen-faster-mapped --min-active=200 --max-active=7000 --max-mem=50000000 --beam=13.0 --lattice-beam=8.0 --acoustic-scale=0.2 --allow-partial=true --word-symbol-table=/home/gkb/Download/kaldi/egs/timit/s5/exp/tri3/graph/words.txt /home/gkb/Download/kaldi/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_ali/final.mdl /home/gkb/Download/kaldi/egs/timit/s5/exp/tri3/graph/HCLG.fst "ark,s,cs:cat ..//home/gkb/torch_kaldi_exp/exp/TIMIT_MLP/forward_ep_24_ck_4.pkl |" "ark:|gzip -c > ..//home/gkb/torch_kaldi_exp/exp/TIMIT_MLP/decoding_test/lat.1.gz" ) 2>> ..//home/gkb/torch_kaldi_exp/exp/TIMIT_MLP/decoding_test/log/decode.1.log >> ..//home/gkb/torch_kaldi_exp/exp/TIMIT_MLP/decoding_test/log/decode.1.log
run.pl: job failed, log is in ..//home/gkb/torch_kaldi_exp/exp/TIMIT_MLP/decoding_test/log/decode.1.log

**Comment by mravanelli** [comment]
Try to run again the decode command making sure all your paths are correct.  For instance, are you sure " ..//home/gkb/torch_kaldi_exp/exp/TIMIT_MLP/forward_ep_24_ck_4.pk" is right?
