### ISSUE TITLE
Why no automated testing? Travis CI, CircleCI, AppVeyor, Azure Pipelines, etc?

### ISSUE THREAD

**Issue by cclauss** [mravanelli/pytorch-kaldi#150]

**Comment by TParcollet** [comment]
Hi,

PyTorch-Kaldi is currently in its first released version. It is going to be majorly re-worked soon to improve the toolkit. This first version is intended to quickly be able to experiment on acoustic models for research, with a possibility to deploy in production. The next version will integrate a continuous integration solution.

**Comment by cclauss** [comment]
Makes sense.  If you pick a CI system and want a starter config file, let me know...

**Comment by TParcollet** [comment]
Sure! Thank you very much for proposing.

**Comment by Mistobaan** [comment]
Github now has its own CI build system too.

**Comment by cclauss** [comment]
@Mistobaan https://github.com/actions/starter-workflows/pull/25#event-2559440260 Now contains the tests that I would have applied.
