### ISSUE TITLE
Integration with pytorch audio? 

### ISSUE THREAD

**Issue by Mistobaan** [mravanelli/pytorch-kaldi#151]
Pytorch recently released https://github.com/pytorch/audio which contains a lot of groundwork for kaldi-pytorch integration.
I think it can be beneficial for both projects to build upon the pytorch.audio API. 

Is there a rough milestone plan of the changes that pytorch-kaldi is planning to do?

**Comment by mravanelli** [comment]
Hi,
thank you for the question.
Yes, we are in contact and we plan to collaborate heavily during the next
days on the next version of the pytorch-kaldi project.
Let me also take this opportunity to announce that the project will be
significantly expanded during the next months and we already have  some
important sponsors that will help us developing the new toolkit. There will
be an announcement about it during the next week. Stay tuned!

Mirco
