### ISSUE TITLE
Error about reading fmllr

### ISSUE THREAD

**Issue by PeiyanFlying** [mravanelli/pytorch-kaldi#152]
Hi, I wanna use fmllr as my input feature, but I meet with trouble as follows:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/dongpe/Software/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/dongpe/Software/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dongpe/RNN/temp0/data_io.py", line 202, in read_lab_fea
    [data_name_fea,data_set_fea,data_end_index_fea]=load_chunk(fea_scp,fea_opts,lab_folder,lab_opts,cw_left,cw_right,max_seq_length, output_folder, fea_only)
  File "/home/dongpe/RNN/temp0/data_io.py", line 123, in load_chunk
    [data_name,data_set,data_lab,end_index]=load_dataset(fea_scp,fea_opts,lab_folder,lab_opts,left,right, max_sequence_length, output_folder, fea_only)
  File "/home/dongpe/RNN/temp0/data_io.py", line 77, in load_dataset
    fea_conc,lab_conc = zip(*fea_sorted)
ValueError: not enough values to unpack (expected 2, got 0)

- Reading config file......OK!
- Chunk creation......OK!

------------------------------ Epoch 00 / 24 ------------------------------
Training TIMIT_tr chunk = 1 / 5
Traceback (most recent call last):
  File "run_exp.py", line 195, in <module>
    [data_name,data_set,data_end_index,fea_dict,lab_dict,arch_dict]=run_nn(data_name,data_set,data_end_index,fea_dict,lab_dict,arch_dict,config_chunk_file,processed_first,next_config_file)
  File "/home/dongpe/RNN/temp0/core.py", line 82, in run_nn
    data_name=shared_list[0]
IndexError: list index out of range

And this is my cfg file, I have check all the path, I still cannot find the bug. Many thanks!

[cfg_proto]
cfg_proto = proto/global.proto
cfg_proto_chunk = proto/global_chunk.proto

[exp]
cmd = 
run_nn_script = run_nn
out_folder = exp/TIMIT_GOOLSTM_fmllr
seed = 2234
use_cuda = True
multi_gpu = False
save_gpumem = False
n_epochs_tr = 25

[dataset1]
data_name = TIMIT_tr
fea = fea_name=mfcc
	fea_lst=/home/dongpe/kaldi/egs/timit/s5/data/train/feats.scp
	fea_opts=apply-cmvn --utt2spk=ark:/home/dongpe/kaldi/egs/timit/s5/data/train/utt2spk  ark:/home/dongpe/kaldi/egs/timit/s5/mfcc/cmvn_train.ark ark:- ark:- | add-deltas --delta-order=2 ark:- ark:- |
	cw_left=0
	cw_right=0

	fea_name=fmllr
	fea_lst=/home/dongpe/kaldi/egs/timit/s5/data-fmllr-tri3/train/feats.scp
	fea_opts=apply-cmvn --utt2spk=ark:/home/dongpe/kaldi/egs/timit/s5/data-fmllr-tri3/train/utt2spk  ark:/home/dongpe/kaldi/egs/timit/s5/fmllr-tri3/cmvn_train.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
	cw_left=0
	cw_right=0
lab = lab_name=lab_cd
	lab_folder=/home/dongpe/kaldi/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_ali
	lab_opts=ali-to-pdf
	lab_count_file=auto
	lab_data_folder=/home/dongpe/kaldi/egs/timit/s5/data-fmllr-tri3/train
	lab_graph=/home/dongpe/kaldi/egs/timit/s5/exp/tri3/graph
	
	lab_name=lab_mono
	lab_folder=/home/dongpe/kaldi/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_ali
	lab_opts=ali-to-phones --per-frame=true
	lab_count_file=none
	lab_data_folder=/home/dongpe/kaldi/egs/timit/s5/data-fmllr-tri3/train
	lab_graph=home/dongpe/kaldi/egs/timit/s5/exp/tri3/graph
n_chunks = 5

[dataset2]
data_name = TIMIT_dev
fea = fea_name=mfcc
	fea_lst=/home/dongpe/kaldi/egs/timit/s5/data/dev/feats.scp
	fea_opts=apply-cmvn --utt2spk=ark:/home/dongpe/kaldi/egs/timit/s5/data/dev/utt2spk  ark:/home/dongpe/kaldi/egs/timit/s5/mfcc/cmvn_dev.ark ark:- ark:- | add-deltas --delta-order=2 ark:- ark:- |
	cw_left=0
	cw_right=0

	fea_name=fmllr
	fea_lst=/home/dongpe/kaldi/egs/timit/s5/data-fmllr-tri3/dev/feats.scp
	fea_opts=apply-cmvn --utt2spk=ark:/home/dongpe/kaldi/egs/timit/s5/data-fmllr-tri3/dev/utt2spk  ark:/home/dongpe/kaldi/egs/timit/s5/fmllr-tri3/cmvn_dev.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
	cw_left=0
	cw_right=0
lab = lab_name=lab_cd
	lab_folder=/home/dongpe/kaldi/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_ali_dev
	lab_opts=ali-to-pdf
	lab_count_file=auto
	lab_data_folder=/home/dongpe/kaldi/egs/timit/s5/data-fmllr-tri3/dev
	lab_graph=/home/dongpe/kaldi/egs/timit/s5/exp/tri3/graph
	
	lab_name=lab_mono
	lab_folder=/home/dongpe/kaldi/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_ali_dev
	lab_opts=ali-to-phones --per-frame=true
	lab_count_file=none
	lab_data_folder=home/dongpe/kaldi/egs/timit/s5/data-fmllr-tri3/dev
	lab_graph=/home/dongpe/kaldi/egs/timit/s5/exp/tri3/graph
n_chunks = 1

[dataset3]
data_name = TIMIT_test
fea = fea_name=mfcc
	fea_lst=/home/dongpe/kaldi/egs/timit/s5/data/test/feats.scp
	fea_opts=apply-cmvn --utt2spk=ark:/home/dongpe/kaldi/egs/timit/s5/data/test/utt2spk  ark:/home/dongpe/kaldi/egs/timit/s5/mfcc/cmvn_test.ark ark:- ark:- | add-deltas --delta-order=2 ark:- ark:- |
	cw_left=0
	cw_right=0

	fea_name=fmllr
	fea_lst=/home/dongpe/kaldi/egs/timit/s5/data-fmllr-tri3/test/feats.scp
	fea_opts=apply-cmvn --utt2spk=ark:/home/dongpe/kaldi/egs/timit/s5/data-fmllr-tri3/test/utt2spk  ark:/home/dongpe/kaldi/egs/timit/s5/fmllr-tri3/cmvn_test.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
	cw_left=0
	cw_right=0
lab = lab_name=lab_cd
	lab_folder=/home/dongpe/kaldi/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_ali_test
	lab_opts=ali-to-pdf
	lab_count_file=auto
	lab_data_folder=/home/dongpe/kaldi/egs/timit/s5/data-fmllr-tri3/test/
	lab_graph=/home/dongpe/kaldi/egs/timit/s5/exp/tri3/graph
	
	lab_name=lab_mono
	lab_folder=/home/dongpe/kaldi/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_ali_test
	lab_opts=ali-to-phones --per-frame=true
	lab_count_file=none
	lab_data_folder=/home/dongpe/kaldi/egs/timit/s5/data-fmllr-tri3/test
	lab_graph=/home/dongpe/kaldi/egs/timit/s5/exp/tri3/graph
n_chunks = 1

[data_use]
train_with = TIMIT_tr
valid_with = TIMIT_dev
forward_with = TIMIT_test

[batches]
batch_size_train = 8
max_seq_length_train = 1000
increase_seq_length_train = True
start_seq_len_train = 100
multply_factor_seq_len_train = 2
batch_size_valid = 8
max_seq_length_valid = 1000

[architecture1]
arch_name = GOOLSTM_layers
arch_proto = proto/GOOLSTM.proto
arch_library = neural_networks
arch_class = GOOLSTM
arch_pretrain_file = none
arch_freeze = False
arch_seq_model = True
goolstm_lay = 1024
goolstm_project = 512
goolstm_drop = 0
goolstm_use_laynorm_inp = False
goolstm_use_batchnorm_inp = False
goolstm_use_laynorm = False
goolstm_use_batchnorm = True
goolstm_bidir = True
goolstm_act = tanh
goolstm_orthinit = True
arch_lr = 0.00016
arch_halving_factor = 0.5
arch_improvement_threshold = 0.001
arch_opt = rmsprop
opt_momentum = 0.0
opt_alpha = 0.95
opt_eps = 1e-8
opt_centered = False
opt_weight_decay = 0.0

[architecture2]
arch_name = MLP_layers
arch_proto = proto/MLP.proto
arch_library = neural_networks
arch_class = MLP
arch_pretrain_file = none
arch_freeze = False
arch_seq_model = False
dnn_lay = N_out_lab_cd
dnn_drop = 0.0
dnn_use_laynorm_inp = False
dnn_use_batchnorm_inp = False
dnn_use_batchnorm = False
dnn_use_laynorm = False
dnn_act = softmax
arch_lr = 0.00016
arch_halving_factor = 0.5
arch_improvement_threshold = 0.001
arch_opt = rmsprop
opt_momentum = 0.0
opt_alpha = 0.95
opt_eps = 1e-8
opt_centered = False
opt_weight_decay = 0.0

[architecture3]
arch_name = MLP_layers2
arch_proto = proto/MLP.proto
arch_library = neural_networks
arch_class = MLP
arch_pretrain_file = none
arch_freeze = False
arch_seq_model = False
dnn_lay = N_out_lab_mono
dnn_drop = 0.0
dnn_use_laynorm_inp = False
dnn_use_batchnorm_inp = False
dnn_use_batchnorm = False
dnn_use_laynorm = False
dnn_act = softmax
arch_lr = 0.0004
arch_halving_factor = 0.5
arch_improvement_threshold = 0.001
arch_opt = rmsprop
opt_momentum = 0.0
opt_alpha = 0.95
opt_eps = 1e-8
opt_centered = False
opt_weight_decay = 0.0

[model]
model_proto = proto/model.proto
model = out_dnn1=compute(GOOLSTM_layers,fmllr)
	out_dnn2=compute(MLP_layers,out_dnn1)
	out_dnn3=compute(MLP_layers2,out_dnn1)
	loss_mono=cost_nll(out_dnn3,lab_mono)
	loss_mono_w=mult_constant(loss_mono,1.0)
	loss_cd=cost_nll(out_dnn2,lab_cd)
	loss_final=sum(loss_cd,loss_mono_w)
	err_final=cost_err(out_dnn2,lab_cd)

[forward]
forward_out = out_dnn2
normalize_posteriors = True
normalize_with_counts_from = lab_cd
save_out_file = False
require_decoding = True

[decoding]
decoding_script_folder = kaldi_decoding_scripts/
decoding_script = decode_dnn.sh
decoding_proto = proto/decoding.proto
min_active = 200
max_active = 7000
max_mem = 50000000
beam = 13.0
latbeam = 8.0
acwt = 0.2
max_arcs = -1
skip_scoring = false
scoring_script = local/score.sh
scoring_opts = "--min-lmwt 1 --max-lmwt 10"
norm_vars = False

**Comment by TParcollet** [comment]
Hi! 

Unfortunately, this error is typical of a wrong path. It's also related to the training data, since it crashed when loading the training data. I would suggest you to very again the paths, and to check the paths of the feat.scp file.

**Comment by PeiyanFlying** [comment]
Thanks, I made it~ Thanks for the projection.

**Comment by l2009312042** [comment]
@PeiyanFlying   hello  ,can you show how to get  fmllr-tri3/cmvn_train.ark
