### ISSUE TITLE
Error about context_window()

### ISSUE THREAD

**Issue by huangjun0413** [mravanelli/pytorch-kaldi#153]
In the code of kaldi, we set left=5, which means that we get  five frames from history.  Howerer, it is the other way round here.

`   
 fea_conc=np.empty([N_elem,N_fea*(left+right+1)])

    index_fea=0
    for lag in range(-left,right+1):
        fea_conc[:,index_fea:index_fea+fea.shape[1]]=np.roll(fea,lag,axis=0)
        index_fea=index_fea+fea.shape[1]

    fea_conc=fea_conc[left:fea_conc.shape[0]-right]
`

`x = np.arange(10) x=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a = np.roll(x, 2)    a=array([8, 9, 0, 1, 2, 3, 4, 5, 6, 7])
`
maybe the right code is:
fea_conc[:,index_fea:index_fea+fea.shape[1]]=np.roll(fea,-lag,axis=0)

**Comment by mravanelli** [comment]
Yes, 
you are right. I fix it. Could you double check if everything is fine now? Thank you very much!
