### ISSUE TITLE
error when running ./local/nnet/run_dnn.sh

### ISSUE THREAD

**Issue by stylelohan** [mravanelli/pytorch-kaldi#155]
Hi, sorry for bothering, an error occur when I run ./local/nnet/run_dnn.sh. I have tried the instructions before I post this issue. The error message is as follows:

![error](https://user-images.githubusercontent.com/11243331/63786387-91955780-c924-11e9-9582-478de3627ad3.PNG)

Thank you very much!

**Comment by TParcollet** [comment]
Hi !

Unfortunately, this is more a Kaldi issue than a Pytorch-Kaldi one ... Thus, I would suggest you to ask this question on the Kaldi google group for an optimal answer. From what I see, it might relate to an error when compiling Kaldi with GPU enabled.

**Comment by underdogliu** [comment]
@stylelohan yeah it's a kaldi question....but just as a quick thought, maybe it's because of cuda version in-compatibility? Can you please run `nvcc --version` to check it?

**Comment by TParcollet** [comment]
The toolkit has been tested on many different CUDA version, ranging from 8.0 to 10.x

**Comment by underdogliu** [comment]
no I'm not saying it's pytorch-kaldi's problem. But maybe it happens to kaldi :thinking:

**Comment by TParcollet** [comment]
Well, since the toolkit involves Kaldi, I can say that we also tested Kaldi with CUDA going from 8.x to 10.x.
