### ISSUE TITLE
error about reading shared_list from dataset with TIMIT tutorial

### ISSUE THREAD

**Issue by hajime9652** [mravanelli/pytorch-kaldi#156]
python3 run_exp.py cfg/TIMIT_baselines/TIMIT_MLP_mfcc_basic.cfg
- Reading config file......OK!
- Chunk creation......OK!

------------------------------ Epoch 00 / 23 ------------------------------
Training TIMIT_tr chunk = 1 / 5
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sysadmin/pytorch-kaldi/data_io.py", line 458, in read_lab_fea
    [data_name_fea,data_set_fea,data_end_index_fea]=load_chunk(fea_scp,fea_opts,lab_folder,lab_opts,cw_left,cw_right,max_seq_length, output_folder, fea_only)
  File "/home/sysadmin/pytorch-kaldi/data_io.py", line 208, in load_chunk
    [data_name,data_set,data_lab,end_index_fea,end_index_lab]=load_dataset(fea_scp,fea_opts,lab_folder,lab_opts,left,right, max_sequence_length, output_folder, fea_only)
  File "/home/sysadmin/pytorch-kaldi/data_io.py", line 171, in load_dataset
    fea_conc, lab_conc, end_index_fea, end_index_lab = _concatenate_features_and_labels(fea_chunks, lab_chunks)
  File "/home/sysadmin/pytorch-kaldi/data_io.py", line 134, in _concatenate_features_and_labels
    fea_conc, lab_conc = _sort_chunks_by_length(fea_conc, lab_conc)
  File "/home/sysadmin/pytorch-kaldi/data_io.py", line 124, in _sort_chunks_by_length
    fea_conc,lab_conc = zip(*fea_sorted)
ValueError: not enough values to unpack (expected 2, got 0)

Traceback (most recent call last):
  File "run_exp.py", line 223, in <module>
    [data_name,data_set,data_end_index,fea_dict,lab_dict,arch_dict]=run_nn(data_name,data_set,data_end_index,fea_dict,lab_dict,arch_dict,config_chunk_file,processed_first,next_config_file)
  File "/home/sysadmin/pytorch-kaldi/core.py", line 355, in run_nn
    data_name=shared_list[0]
IndexError: list index out of range

**Comment by hajime9652** [comment]
### config
[dataset1]
data_name = TIMIT_tr
fea = fea_name=mfcc
        fea_lst=/home/sysadmin/kaldi/egs/timit/s5_tutorial/data/train/feats.scp
        fea_opts=apply-cmvn --utt2spk=ark:/home/syadmin/kaldi/egs/timit/s5_tutorial/data/train/utt2spk  ark:/home/sysadmin/kaldi/egs/timit/s5_tutorial/mfcc/cmvn_train.ark ark:- ark:- | add-deltas --delta-order=2 ark:- ark:- |
        cw_left=5
        cw_right=5


lab = lab_name=lab_cd
        lab_folder=/home/sysadmin/kaldi/egs/timit/s5_tutorial/exp/dnn4_pretrain-dbn_dnn_ali
        lab_opts=ali-to-pdf
        lab_count_file=auto
        lab_data_folder=/home/sysadmin/kaldi/egs/timit/s5_tutorial/data/train/
        lab_graph=/home/sysadmin/kaldi/egs/timit/s5_tutorial/exp/tri3/graph


n_chunks = 5

[dataset2]
data_name = TIMIT_dev
fea = fea_name=mfcc
        fea_lst=/home/sysadmin/kaldi/egs/timit/s5_tutorial/data/dev/feats.scp
        fea_opts=apply-cmvn --utt2spk=ark:/home/sysadmin/kaldi/egs/timit/s5_tutorial/data/dev/utt2spk  ark:/home/sysadmin/kaldi/egs/timit/s5_tutorial/mfcc/cmvn_dev.ark ark:- ark:- | add-deltas --delta-order=2 ark:- ark:- |
        cw_left=5
        cw_right=5


lab = lab_name=lab_cd
        lab_folder=/home/sysadmin/kaldi/egs/timit/s5_tutorial/exp/dnn4_pretrain-dbn_dnn_ali_dev
        lab_opts=ali-to-pdf
        lab_count_file=auto
        lab_data_folder=/home/sysadmin/kaldi/egs/timit/s5_tutorial/data/dev/
        lab_graph=/home/mirco/kaldi/egs/timit/s5_tutorial/exp/tri3/graph


n_chunks = 1

[dataset3]
data_name = TIMIT_test
fea = fea_name=mfcc
        fea_lst=/home/sysadmin/kaldi/egs/timit/s5_tutorial/data/test/feats.scp
        fea_opts=apply-cmvn --utt2spk=ark:/home/sysadmin/kaldi/egs/timit/s5_tutorial/data/test/utt2spk  ark:/home/sysadmin/kaldi/egs/timit/s5_tutorial/mfcc/cmvn_test.ark ark:- ark:- | add-deltas --delta-order=2 ark:- ark:- |
        cw_left=5
        cw_right=5


lab = lab_name=lab_cd
        lab_folder=/home/sysadmin/kaldi/egs/timit/s5_tutorial/exp/dnn4_pretrain-dbn_dnn_ali_test
        lab_opts=ali-to-pdf
        lab_count_file=auto
        lab_data_folder=/home/sysadmin/kaldi/egs/timit/s5_tutorial/data/test/
        lab_graph=/home/sysadmin/kaldi/egs/timit/s5_tutorial/exp/tri3/graph


n_chunks = 1

**Comment by hajime9652** [comment]
I can find this issue
https://github.com/mravanelli/pytorch-kaldi/issues/105

**Comment by hajime9652** [comment]
feats.scp is here. I checked.
cat ~/kaldi/egs/timit/s5_tutorial/data/train/feats.scp

**Comment by weienzhang** [comment]
> feats.scp is here. I checked.
> cat ~/kaldi/egs/timit/s5_tutorial/data/train/feats.scp
May i know that was there a solution to your error eventually?
