### ISSUE TITLE
How to inference on my dataset

### ISSUE THREAD

**Issue by Caoang327** [mravanelli/pytorch-kaldi#159]
Hi. It is a really amazing tool-kit and thanks for your contributions.

Right now, I have trained a model using pytorch-kaldi on timit for phoneme recognition. I want to add some noise to the test dataset and see how these noise would effect the recognition error. I have re-calculate the features of new test dataset and link the new features in the test config. But when I run the run_exp.py file, it just outputs the results of my previous experiments. So could you please tell me how to evaluate the existing model on my new test data set?

Thank you very much.

**Comment by TParcollet** [comment]
Sure! Two possibilities: 

1. Research Pipeline: Just delete the forward_* in the exp_files folder and "decod*" directly in the log dir, and relaunch. It will launch the forward / decode on the new test.

2. Production Pipeline: Just have a look at the readme ! But it's way longer .

**Comment by Caoang327** [comment]
Hi:
What you mean "decod*" in the log dir? I cannot find the log dir. Could you please specify it?

Thank you very much

**Comment by TParcollet** [comment]
Yes sorry,
it's the exp/your_exp/ dir !

**Comment by Caoang327** [comment]
It works. Thanks for your help!

**Comment by Originofamonia** [comment]
Hi!
I tried to remove all files and directory with forward* and decod* in exp dir and added some noise for inference. But the PER doesn't change. Is there some steps I'm missing?
I added the noise on the utils.py's forward_model function's:
`        if operation == 'compute':
            if len(inp_out_dict[inp2]) > 1:  # if it is an input feature
                # Selection of the right feature in the inp tensor
                if len(inp.shape) == 3:
                    inp_dnn = inp[:, :, inp_out_dict[inp2][-3]:inp_out_dict[inp2][-2]]
                    if not (bool(arch_dict[inp1][2])):
                        inp_dnn = inp_dnn.view(max_len * batch_size, -1)

                if len(inp.shape) == 2:
                    inp_dnn = inp[:, inp_out_dict[inp2][-3]:inp_out_dict[inp2][-2]]
                    if bool(arch_dict[inp1][2]):
                        inp_dnn = inp_dnn.view(max_len, batch_size, -1)
                if has_noise:  # inference add noise
                    inp_dnn = gaussian(inp_dnn, 0.1)
                outs_dict[out_name] = nns[inp1](inp_dnn)`
And my gaussian function is this:
`def gaussian(ins, stddev=0.01):
    return ins + torch.autograd.Variable(torch.randn(ins.shape).cuda() * stddev)`
I added noise onto the inp_dnn.
I don't know whether my adding noise method is wrong or I forgot to delete some files?
Thanks!
