### ISSUE TITLE
In training quantization of weights (parameters) and activations

### ISSUE THREAD

**Issue by razor1179** [mravanelli/pytorch-kaldi#16]
Have there been any attempts at implementing in training quantization, like that in "Binarized Neural Networks: Training Deep Neural Networks with Weights and Activations Constrained to +1 or -1" using pytorch-kaldi? If not can the admin provide direction on how to proceed to obtain in-training quantization?

**Comment by TParcollet** [comment]
To my knowledge, we haven't tried to implement binarized NN in pytorch-Kaldi. Nonetheless, following the "How can I plug-in my model?" section of the readme, you can find everything you need to know to plug your own model based on other pytorch implementations of BNN such as https://github.com/itayhubara/BinaryNet.pytorch.

**Comment by mravanelli** [comment]
This model is not implemented in the current version. However, if someone implements it we can definitely add it into the toolkit!
