### ISSUE TITLE
The mono-regu question。

### ISSUE THREAD

**Issue by 17551023349** [mravanelli/pytorch-kaldi#163]
Hello, thank you very much for your work.I recently had a problem with mono-regu.
Are lab_cd and lab_mono Settings the same except lab_opts? I ran timit_rnn_mfc.cfg with my own data, using mono-regu and not using it, but I got the same WER.May I ask what caused this and where I should make changes? Here are my specific Settings.
（1）here is my lab settings

        lab_name=lab_cd
        lab_folder=/data/sxs/kaldi-master/egs/thchs30/s5_py/exp/tri4b_ali
        lab_opts=ali-to-pdf
        lab_count_file=auto
        lab_data_folder=/data/sxs/kaldi-master/egs/thchs30/s5_py/data/mfcc/train/
        lab_graph=/data/sxs/kaldi-master/egs/thchs30/s5_py/exp/tri4b/graph

        lab_name=lab_mono
        lab_folder=/data/sxs/kaldi-master/egs/thchs30/s5_py/exp/tri4b_ali
        lab_opts=ali-to-phones --per-frame=true
        lab_count_file=none
        lab_data_folder=/data/sxs/kaldi-master/egs/thchs30/s5_py/data/mfcc/train/
        lab_graph=/data/sxs/kaldi-master/egs/thchs30/s5_py/exp/tri4b/graph
n_chunks = 40

（2）here is my model with mono-regu     （forward_out is out_dnn2）

        model_proto = proto/model.proto
        model = out_dnn1=compute(RNN_layers,mfcc)
        out_dnn2=compute(MLP_layers,out_dnn1)
        out_dnn3=compute(MLP_layers2,out_dnn1)
        loss_mono=cost_nll(out_dnn3,lab_mono)
        loss_mono_w=mult_constant(loss_mono,1.0)
        loss_cd=cost_nll(out_dnn2,lab_cd)
        loss_final=sum(loss_cd,loss_mono_w)
        err_final=cost_err(out_dnn2,lab_cd)

（3）here is my model without mono-regu （forward_out is out_dnn2）

        model_proto = proto/model.proto
        model = out_dnn1=compute(RNN_layers,mfcc)
        out_dnn2=compute(MLP_layers,out_dnn1)
        loss_cd=cost_nll(out_dnn2,lab_cd)
        loss_final=sum(loss_cd,loss_cd)
        err_final=cost_err(out_dnn2,lab_cd)

Looking forward to your reply，Thanks。

**Comment by speechbrain** [comment]
Could you post here the res.res file with and without monophone regularization?
