### ISSUE TITLE
PASE frontend

### ISSUE THREAD

**Issue by eginhard** [mravanelli/pytorch-kaldi#165]
Do you have an example for using the PASE module in neural_networks.py? Should it work for the raw features in the format generated by save_raw_fea.py and the available pre-trained model?

I tried to add the PASE frontend to the DIRHA cfg as shown below, but run into issues of mismatching shapes/ranks.

```
[architecture1]
arch_name = PASE_CNN
arch_proto = proto/PASE.proto
arch_library = neural_networks
arch_class = PASE
arch_pretrain_file = none
arch_freeze = False
arch_seq_model = False

pase_cfg = .../pase/cfg/PASE.cfg
pase_model = .../PASE/PASE.ckpt

arch_lr = 0.0004
arch_halving_factor = 0.5
arch_improvement_threshold = 0.001
arch_opt = rmsprop
opt_momentum = 0.0
opt_alpha = 0.95
opt_eps = 1e-8
opt_centered = False
opt_weight_decay = 0.0

...

[model]
model_proto=proto/model.proto
model:out_dnn1=compute(PASE_CNN,raw)
      out_dnn2=compute(liGRU_layers,out_dnn1)
      out_dnn3=compute(MLP_layers,out_dnn2)
      loss_final=cost_nll(out_dnn3,lab_cd)
      err_final=cost_err(out_dnn3,lab_cd)
```

**Comment by mravanelli** [comment]
Which dimensionality issue do you see exactly?

Mirco

**Comment by eginhard** [comment]
The PASE module in this toolkit creates rank 4 tensors, which results in a `AssertionError: 4D tensors expect 4 values for padding` error because PASE itself expects rank 3 input. I tried to fix this by changing [this line](https://github.com/mravanelli/pytorch-kaldi/blob/5374de91e8ae8b1f06eda4cd4d46167775dd8fcb/neural_networks.py#L1804) but this results in further mismatches, so I'm not sure if I'm on the right track.

**Comment by mravanelli** [comment]
Looks like one have reshape the tensors properly. Yes, I have an example and I will post it as soon as I can!

**Comment by zmf0507** [comment]
Can you please post an example of using pase in pytorch-kaldi?
