### ISSUE TITLE
confused about feature/label processing

### ISSUE THREAD

**Issue by Cescfangs** [mravanelli/pytorch-kaldi#167]
I was confused about why pytorch-kaldi process chunk-wise feature/label like :

https://github.com/mravanelli/pytorch-kaldi/blob/5374de91e8ae8b1f06eda4cd4d46167775dd8fcb/data_io.py#L220
Using fixed global mean/std could be better?

https://github.com/mravanelli/pytorch-kaldi/blob/5374de91e8ae8b1f06eda4cd4d46167775dd8fcb/data_io.py#L223
what if global min label(say 0) is missing in this chunk?

**Comment by mravanelli** [comment]
Hi, the assumption is that chunks are large enough to have there the min label.
Note that this is not a problem at all with kaldi, where lab_id=0 correspond to silence (it is present in all the sentences).

**Comment by Cescfangs** [comment]
@mravanelli Thanks for the explanation, what about feature processing? I think chunk-wise stats(mean and std) may lack stability, kaldi using a fixed feature_transform to normalize features.

**Comment by mravanelli** [comment]
In general this could be risky as you pointed out, but we suggest to form
chunks composed of at least one hour of speech. This way the statistics
become very stable and we don't require an initial step where we compute
them over all the datasets.

**Comment by Cescfangs** [comment]
thanks for the explanation, it may be reasonable during training, but in test mode we may not expect one hour speech, this could introduce train/test inconsistent, on the other hand if you think one hour speech is large enough, I suggest computing stats only in the first chunk and make it fixed during training and testing.

**Comment by Cescfangs** [comment]
and according to profile results, fix mean and std could save 10% time in data_loading

![data_io](https://user-images.githubusercontent.com/11382612/65656700-5edd9c80-e053-11e9-949f-4161e1dd9201.png)

**Comment by mravanelli** [comment]
Interesting,
thank you for this analysis!
