### ISSUE TITLE
How to turn off parallel data loading?

### ISSUE THREAD

**Issue by HardikSailor** [mravanelli/pytorch-kaldi#168]
Hi all,

I am having a problem with GPU job failure with 120 hrs of data. When I looked at the log it says:

CUDA out of memory. Tried to allocate 1.79 GiB (GPU 0; 11.92 GiB total capacity; 2.15 GiB already allocated; 1.13 GiB free; 8.20 GiB cached)

I am using GPU in SGE server. I think this may be due to parallel data loading in the memory.
 
I have tried chunk size with 120 that ideally have one hour chunk. However, I still got the above error.   How should I turn off parallel data loading in GPU memory to solve CUDA error? Or this is related to something different?

Thank you.

**Comment by TParcollet** [comment]
Hi there! Sorry for the late reply. CUDA errors are not related to data loading. The multi-core data loading process only stores the data in the RAM and not the VRAM. In your case, it's either a problem of network size / batch_size.

**Comment by HardikSailor** [comment]
Hi,

Thank you for the response. Yes, I am looking into the network now. This network is 4 layers GRU with multitasking as monophones. May be due to this the memory problems occur.
many thanks.
