### ISSUE TITLE
The file "cmvn.ark" for fmllr

### ISSUE THREAD

**Issue by PeiyanFlying** [mravanelli/pytorch-kaldi#172]
Hello Sir,
I have made all the steps in our TIMIT tutorial, but I can't find the "cmvn.ark" for fmllr feature. So could you tell me which steps are necessary for the fmllr feature extraction?
Many thanks.

**Comment by TParcollet** [comment]
Hey ! You will have to take a look at the traditional Kaldi recipes to find the best way to extract fmllr! A pointer is: https://github.com/kaldi-asr/kaldi/blob/8ce3a95761e0eb97d95d3db2fcb6b2bfb7ffec5b/egs/timit/s5/local/nnet/run_dnn.sh

**Comment by TParcollet** [comment]
I think you can also use align_fmllr.sh

**Comment by mravanelli** [comment]
Did you solve this issue?

**Comment by PeiyanFlying** [comment]
Yes, I have.. Sorry to not close this issue timely. Many thanks !

**Comment by mnabihali** [comment]
@PeiyanFlying  How you solve this problem
