### ISSUE TITLE
Problem with run_exp.py

### ISSUE THREAD

**Issue by sapinedamo** [mravanelli/pytorch-kaldi#177]
Hi!

I'm trying the Librispeech dataset and I get the following error: 

(pytorch-kaldi) csanta@lilistt:~/pytorch-kaldi/pytorch-kaldi$ CUDA_VISIBLE_DEVICES=0 python3 run_exp.py cfg/Librispeech_baselines/libri_MLP_fmllr.cfg                   - Reading config file......OK!
- Chunk creation......OK!

------------------------------ Epoch 0 / 9 ------------------------------
Training train_clean_100 chunk = 1 / 50
[========================================] 100% Training | (Batch 5567/5567)7) | L:4.613
Training train_clean_100 chunk = 2 / 50
[========================================] 100% Training | (Batch 5710/5710)0) | L:2.779
Training train_clean_100 chunk = 3 / 50
[========================================] 100% Training | (Batch 5690/5690)0) | L:2.365
Training train_clean_100 chunk = 4 / 50
[========================================] 100% Training | (Batch 5630/5630)0) | L:2.229
Training train_clean_100 chunk = 5 / 50
[========================================] 100% Training | (Batch 5666/5666)6) | L:2.112
Training train_clean_100 chunk = 6 / 50
[========================================] 100% Training | (Batch 5606/5606)6) | L:2.03
Training train_clean_100 chunk = 7 / 50
[========================================] 100% Training | (Batch 5636/5636)6) | L:1.986
Training train_clean_100 chunk = 8 / 50
[========================================] 100% Training | (Batch 5507/5507)7) | L:1.958
Training train_clean_100 chunk = 9 / 50
[========================================] 100% Training | (Batch 5719/5719)9) | L:1.917
Training train_clean_100 chunk = 10 / 50
[========================================] 100% Training | (Batch 5606/5606)6) | L:1.851
Training train_clean_100 chunk = 11 / 50
[========================================] 100% Training | (Batch 5654/5654)4) | L:1.849
Training train_clean_100 chunk = 12 / 50
[========================================] 100% Training | (Batch 5585/5585)5) | L:1.808
Training train_clean_100 chunk = 13 / 50
[========================================] 100% Training | (Batch 5591/5591)1) | L:1.81
Training train_clean_100 chunk = 14 / 50
[========================================] 100% Training | (Batch 5656/5656)6) | L:1.78
Training train_clean_100 chunk = 15 / 50
[========================================] 100% Training | (Batch 5727/5727)7) | L:1.758
Training train_clean_100 chunk = 16 / 50
[========================================] 100% Training | (Batch 5603/5603)3) | L:1.756
Training train_clean_100 chunk = 17 / 50
[========================================] 100% Training | (Batch 5582/5582)2) | L:1.763
Training train_clean_100 chunk = 18 / 50
[========================================] 100% Training | (Batch 5649/5649)9) | L:1.723
Training train_clean_100 chunk = 19 / 50
[========================================] 100% Training | (Batch 5573/5573)3) | L:1.715
Training train_clean_100 chunk = 20 / 50
[========================================] 100% Training | (Batch 5646/5646)6) | L:1.71
Training train_clean_100 chunk = 21 / 50
[========================================] 100% Training | (Batch 5753/5753)3) | L:1.704
Training train_clean_100 chunk = 22 / 50
[========================================] 100% Training | (Batch 5708/5708)8) | L:1.709
Training train_clean_100 chunk = 23 / 50
[========================================] 100% Training | (Batch 5584/5584)4) | L:1.68
Training train_clean_100 chunk = 24 / 50
[========================================] 100% Training | (Batch 5599/5599)9) | L:1.669
Training train_clean_100 chunk = 25 / 50
[========================================] 100% Training | (Batch 5732/5732)2) | L:1.674
Training train_clean_100 chunk = 26 / 50
[========================================] 100% Training | (Batch 5682/5682)2) | L:1.636
Training train_clean_100 chunk = 27 / 50
[========================================] 100% Training | (Batch 5598/5598)8) | L:1.648
Training train_clean_100 chunk = 28 / 50
[========================================] 100% Training | (Batch 5695/5695)5) | L:1.65
Training train_clean_100 chunk = 29 / 50
[========================================] 100% Training | (Batch 5685/5685)5) | L:1.644
Training train_clean_100 chunk = 30 / 50
[========================================] 100% Training | (Batch 5733/5733)3) | L:1.623
Training train_clean_100 chunk = 31 / 50
[========================================] 100% Training | (Batch 5727/5727)7) | L:1.627
Training train_clean_100 chunk = 32 / 50
[========================================] 100% Training | (Batch 5645/5645)5) | L:1.623
Training train_clean_100 chunk = 33 / 50
[========================================] 100% Training | (Batch 5708/5708)8) | L:1.609
Training train_clean_100 chunk = 34 / 50
[========================================] 100% Training | (Batch 5589/5589)9) | L:1.607
Training train_clean_100 chunk = 35 / 50
[========================================] 100% Training | (Batch 5679/5679)9) | L:1.601
Training train_clean_100 chunk = 36 / 50
[========================================] 100% Training | (Batch 5688/5688)8) | L:1.603
Training train_clean_100 chunk = 37 / 50
[========================================] 100% Training | (Batch 5547/5547)7) | L:1.607
Training train_clean_100 chunk = 38 / 50
[========================================] 100% Training | (Batch 5738/5738)8) | L:1.576
Training train_clean_100 chunk = 39 / 50
[========================================] 100% Training | (Batch 5634/5634)4) | L:1.59
Training train_clean_100 chunk = 40 / 50
[========================================] 100% Training | (Batch 5577/5577)7) | L:1.587
Training train_clean_100 chunk = 41 / 50
[========================================] 100% Training | (Batch 5706/5706)6) | L:1.563
Training train_clean_100 chunk = 42 / 50
[========================================] 100% Training | (Batch 5637/5637)7) | L:1.576
Training train_clean_100 chunk = 43 / 50
[========================================] 100% Training | (Batch 5701/5701)1) | L:1.581
Training train_clean_100 chunk = 44 / 50
[========================================] 100% Training | (Batch 5620/5620)0) | L:1.56
Training train_clean_100 chunk = 45 / 50
[========================================] 100% Training | (Batch 5718/5718)8) | L:1.555
Training train_clean_100 chunk = 46 / 50
[========================================] 100% Training | (Batch 5696/5696)6) | L:1.562
Training train_clean_100 chunk = 47 / 50
[========================================] 100% Training | (Batch 5626/5626)6) | L:1.566
Training train_clean_100 chunk = 48 / 50
[========================================] 100% Training | (Batch 5609/5609)9) | L:1.553
Training train_clean_100 chunk = 49 / 50
[========================================] 100% Training | (Batch 5659/5659)9) | L:1.565
Training train_clean_100 chunk = 50 / 50
Exception in thread Thread-151:----------] 1.9% Training | (Batch 108/5602) | L:1.622
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/csanta/pytorch-kaldi/pytorch-kaldi/data_io.py", line 458, in read_lab_fea
    [data_name_fea,data_set_fea,data_end_index_fea]=load_chunk(fea_scp,fea_opts,lab_folder,lab_opts,cw_left,cw_right,max_seq_length, output_folder, fea_only)
  File "/home/csanta/pytorch-kaldi/pytorch-kaldi/data_io.py", line 208, in load_chunk
    [data_name,data_set,data_lab,end_index_fea,end_index_lab]=load_dataset(fea_scp,fea_opts,lab_folder,lab_opts,left,right, max_sequence_length, output_folder, fea_only
  File "/home/csanta/pytorch-kaldi/pytorch-kaldi/data_io.py", line 171, in load_dataset
    fea_conc, lab_conc, end_index_fea, end_index_lab = _concatenate_features_and_labels(fea_chunks, lab_chunks)
  File "/home/csanta/pytorch-kaldi/pytorch-kaldi/data_io.py", line 134, in _concatenate_features_and_labels
    fea_conc, lab_conc = _sort_chunks_by_length(fea_conc, lab_conc)
  File "/home/csanta/pytorch-kaldi/pytorch-kaldi/data_io.py", line 124, in _sort_chunks_by_length
    fea_conc,lab_conc = zip(*fea_sorted)
ValueError: not enough values to unpack (expected 2, got 0)

[========================================] 100% Training | (Batch 5602/5602)2) | L:1.552
Traceback (most recent call last):
  File "run_exp.py", line 223, in <module>
    [data_name,data_set,data_end_index,fea_dict,lab_dict,arch_dict]=run_nn(data_name,data_set,data_end_index,fea_dict,lab_dict,arch_dict,config_chunk_file,processed_fir
  File "/home/csanta/pytorch-kaldi/pytorch-kaldi/core.py", line 582, in run_nn
    data_name=shared_list[0]
IndexError: list index out of range

**Comment by TParcollet** [comment]
HI there!

Can you confirm that everything exploded during the training phases and not validation?

**Comment by mravanelli** [comment]
It seems to me a path error in the validation data

Mirco

**Comment by TParcollet** [comment]
@mravanelli But it's happening during the last training chunk. So it's during the pre-loading of the validation?

**Comment by mravanelli** [comment]
Yes, because while processing the last training chunk we preload the first
validation one. I think there is just a wrong path there..

**Comment by sapinedamo** [comment]
I think that the run.sh file for Librispeech is not creating the trans files for the dev and test datasets, so when I run the lines in the Readme, it fails. So I took the feats.scp that where in another location.

**Comment by sapinedamo** [comment]
My libri_MLP_fmllr.cfg file is as follow:

[cfg_proto]
cfg_proto=proto/global.proto
cfg_proto_chunk=proto/global_chunk.proto

[exp]
cmd=
run_nn_script=run_nn
out_folder=exp/libri_MLP_fmllr
seed=1234
use_cuda=True
multi_gpu=False
save_gpumem=False
N_epochs_tr=10

[dataset1]
data_name=train_clean_100
fea:fea_name=fmllr
    fea_lst=/home/csanta/pytorch-kaldi/kaldi/egs/librispeech/s5/fmllr/train_clean_100/feats.scp
    fea_opts=apply-cmvn --utt2spk=ark:/home/csanta/pytorch-kaldi/kaldi/egs/librispeech/s5/fmllr/train_clean_100/utt2spk  ark:/home/csanta/pytorch-kaldi/kaldi/egs/librispeech/s5/fmllr/train_clean_100/data/cmvn_speaker.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
    cw_left=5
    cw_right=5

    
lab:lab_name=lab_cd
    lab_folder=/home/csanta/pytorch-kaldi/kaldi/egs/librispeech/s5/exp/tri4b/
    lab_opts=ali-to-pdf 
    lab_count_file=auto
    lab_data_folder=/home/csanta/pytorch-kaldi/kaldi/egs/librispeech/s5/fmllr/train_clean_100/
    lab_graph=/home/csanta/pytorch-kaldi/kaldi/egs/librispeech/s5/exp/tri4b/graph_tgsmall/

N_chunks=50
        
[dataset2]
data_name=dev_clean
fea:fea_name=fmllr
    fea_lst=/home/csanta/pytorch-kaldi/kaldi/egs/librispeech/s5/data/dev_clean/feats.scp
    fea_opts=apply-cmvn --utt2spk=ark:/home/csanta/pytorch-kaldi/kaldi/egs/librispeech/s5/fmllr/dev_clean/utt2spk  ark:/home/csanta/pytorch-kaldi/kaldi/egs/librispeech/s5/fmllr/dev_clean/data/cmvn_speaker.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
    cw_left=5
    cw_right=5


lab:lab_name=lab_cd
    lab_folder=/home/csanta/pytorch-kaldi/kaldi/egs/librispeech/s5/exp/tri4b_ali_dev_clean_100
    lab_opts=ali-to-pdf 
    lab_count_file=auto
    lab_data_folder=/home/csanta/pytorch-kaldi/kaldi/egs/librispeech/s5/fmllr/dev_clean/
    lab_graph=/home/csanta/pytorch-kaldi/kaldi/egs/librispeech/s5/exp/tri4b/graph_tgsmall/

N_chunks=4

[dataset3]
data_name=test_clean
fea:fea_name=fmllr
    fea_lst=/home/csanta/pytorch-kaldi/kaldi/egs/librispeech/s5/data/test_clean/feats.scp
    fea_opts=apply-cmvn --utt2spk=ark:/home/csanta/pytorch-kaldi/kaldi/egs/librispeech/s5/fmllr/test_clean/utt2spk  ark:/home/csanta/pytorch-kaldi/kaldi/egs/librispeech/s5/fmllr/test_clean/data/cmvn_speaker.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
    cw_left=5
    cw_right=5


lab:lab_name=lab_cd
    lab_folder=/home/csanta/pytorch-kaldi/kaldi/egs/librispeech/s5/exp/tri4b_ali_test_clean_100
    lab_opts=ali-to-pdf 
    lab_count_file=auto
    lab_data_folder=/home/csanta/pytorch-kaldi/kaldi/egs/librispeech/s5/fmllr/test_clean/
    lab_graph=/home/csanta/pytorch-kaldi/kaldi/egs/librispeech/s5/exp/tri4b/graph_tgsmall/

N_chunks=8

        
[data_use]
train_with=train_clean_100
valid_with=dev_clean
forward_with=test_clean


[batches]
batch_size_train=128
max_seq_length_train=1000
increase_seq_length_train=False
start_seq_len_train=100
multply_factor_seq_len_train=2
batch_size_valid=128
max_seq_length_valid=1000


[architecture1]
arch_name=MLP_layers
arch_proto=proto/MLP.proto
arch_library=neural_networks
arch_class=MLP
arch_pretrain_file=none
arch_freeze=False
arch_seq_model=False

dnn_lay=1024,1024,1024,1024,1024,N_out_lab_cd
dnn_drop=0.15,0.15,0.15,0.15,0.15,0.0
dnn_use_laynorm_inp=False
dnn_use_batchnorm_inp=False
dnn_use_batchnorm=True,True,True,True,True,False
dnn_use_laynorm=False,False,False,False,False,False
dnn_act=relu,relu,relu,relu,relu,softmax

arch_lr=0.08
arch_halving_factor=0.5
arch_improvement_threshold=0.001
arch_opt=sgd
opt_momentum=0.0
opt_weight_decay=0.0
opt_dampening=0.0
opt_nesterov=False


[model]
model_proto=proto/model.proto
model:out_dnn1=compute(MLP_layers,fmllr)
      loss_final=cost_nll(out_dnn1,lab_cd)
      err_final=cost_err(out_dnn1,lab_cd)
 
      
[forward]
forward_out=out_dnn1
normalize_posteriors=True
normalize_with_counts_from=lab_cd
save_out_file=False
require_decoding=True


[decoding]
decoding_script_folder=kaldi_decoding_scripts/
decoding_script=decode_dnn.sh
decoding_proto=proto/decoding.proto
min_active=200
max_active=7000
max_mem=50000000
beam=20.0
latbeam=12.0
acwt=0.10
max_arcs=-1
skip_scoring=false
scoring_script=/home/csanta/pytorch-kaldi/kaldi/egs/librispeech/s5/local/score.sh
scoring_opts="--min-lmwt 4 --max-lmwt 23"
norm_vars=False

**Comment by chijiudao** [comment]
I'll check the data PATH.

**Comment by mravanelli** [comment]
Hi,
did you solve the problem?

**Comment by chijiudao** [comment]
> Hi,
> did you solve the problem?
Hi! 
I haven't solve it. I check the data path but still have the problem:
 (1)In the validating dev data period the problem is : ValueError: not enough values to unpack (expected 2, got 0);
 (2) In the test period it's :File "/home/q/pytorch-kaldi/pytorch-kaldi/core.py", line 582, in run_nn 
data_name=shared_list[0]
IndexError: list index out of range

**Comment by chijiudao** [comment]
The problem is this: I have not solve it.
![testerror](https://user-images.githubusercontent.com/39076097/70145717-b21b3d80-16db-11ea-90db-96944d81c640.png)

**Comment by mravanelli** [comment]
Hi,
this is another problem. Did you solve the issues in the previous message?
For this one, could you tell us the version of python that you have?

Mirco

**Comment by chijiudao** [comment]
Sure, I have solve the previous problem.  The python version I use is 3.5.

**Comment by mravanelli** [comment]
Your python version is too old. As written in the documentation we support
python 3.6 and 3.7. Could you try to upgrade your python and try everything
again?

**Comment by chijiudao** [comment]
Thank you so much. I'll try it.

**Comment by chijiudao** [comment]
Sorry to bother you again. I try to use python3.6, while still encounter this problem.

**Comment by chijiudao** [comment]
Hello,Sir! I have a new problem. It is in the Decode period.  Could you give me some suggestions?The log is here:
# lattice-align-phones /home/lt/pytorch-kaldi/exp/quick_conect1225/decode_TIMIT_test_out_dnn1/../final.mdl "ark:gunzip -c /home/
lt/pytorch-kaldi/exp/quick_conect1225/decode_TIMIT_test_out_dnn1/lat.1.gz|" ark:- | lattice-to-ctm-conf --acoustic-scale=1.00000000 --lm-scale=1.0 ark:- /home/lt/pytorch-kaldi/exp/quick_conect1225/decode_TIMIT_test_out_dnn1/scoring/1.1.ctm
# Started at Mon Dec  9 13:57:14 CST 2019
#
lattice-align-phones /home/lt/pytorch-kaldi/exp/quick_conect1225/
decode_TIMIT_test_out_dnn1/../final.mdl 'ark:gunzip -c /home/lt/pytorch-kaldi/exp/quick_conect1225/decode_TIMIT_test_out_dnn1/lat.1.gz|' ark:- lattice-to-ctm-conf --acoustic-scale=1.00000000 --lm-scale=1.0 ark:- /home/lt/pytorch-kaldi/exp/quick_conect1225/
decode_TIMIT_test_out_dnn1/scoring/1.1.ctm 
LOG (lattice-align-phones[5.1.88~1-ab5c9]:main():lattice-align-phones.cc:104) Successfully aligned 0 lattices; 0 had errors.
LOG (lattice-to-ctm-conf[5.1.88~1-ab5c9]:main():lattice-to-ctm-conf.cc:157) Done 0 lattices.
LOG (lattice-to-ctm-conf[5.1.88~1-ab5c9]:main():lattice-to-ctm-conf.cc:158) Overall average Bayes Risk per sentence is -nan and per word, -nan
# Accounting: time=1 threads=1
# Ended (code 1) at Mon Dec  9 13:57:15 CST 2019, elapsed time 1 seconds

**Comment by TParcollet** [comment]
Any news ?
