### ISSUE TITLE
copy-feats and hmm-info not found

### ISSUE THREAD

**Issue by mmilunovic** [mravanelli/pytorch-kaldi#178]
After installing all dependencies and successfully running commands stated in _../tools/INSTALL_ and _../src/INSTALL_.

I've also set the environment paths 
```
export KALDI_ROOT=/home/milos/kaldi

PATH=$PATH:$KALDI_ROOT/tools/openfst
PATH=$PATH:$KALDI_ROOT/src/featbin
PATH=$PATH:$KALDI_ROOT/src/gmmbin
PATH=$PATH:$KALDI_ROOT/src/bin
PATH=$PATH:$KALDI_ROOT//src/nnetbin
export PATH
```

And yes, the path is correct, when I run **pwd** in kaldi folder I get  **/home/milos/kaldi**. 
Still, when I run copy-feats and hmm-info I get command not found.

**Comment by mravanelli** [comment]
That weird, have you done "source .bashrc" to refresh the shell? Please, let me know if you still have the problem.

**Comment by mmilunovic** [comment]
@mravanelli I did source ~/.bashrc. And I've also done the whole installation again, on a fresh system. 
Previously I had some issues with g++ compiler version which I resolved now. 
After installation and changes in .bashrc I get the following.

When I run `hmm-info` :
```usage: hmm-info <hmm file>
commands:
  -models
  -general
  -durations <length>
```
When I run `copy-feats` :
`copy-feats: command not found`

- System: ubuntu 18.04
- g++ version: 4.9.3

If you need any more information let me know.

**Comment by mravanelli** [comment]
Hi,
in your kaldi folder there should be the following executable:

kaldi/src/featbin/copy-feats

Do you have it? Can you run in?

In the .bashrch do you have the following lines?

export KALDI_ROOT=/home/mirco/kaldi/

export
PATH=$KALDI_ROOT/src/bin:$KALDI_ROOT/tools/openfst/bin:$KALDI_ROOT/tools/irstlm/bin/:$KALDI_ROOT/src/fstbin/:$KALDI_ROOT/src/gmmbi
n/:$KALDI_ROOT/src/featbin/:$KALDI_ROOT/src/lm/:$KALDI_ROOT/src/sgmmbin/:$KALDI_ROOT/src/sgmm2bin/:$KALDI_ROOT/src/fgmmbin/:$KALDI_ROOT/src/latbin/:$KALDI_ROOT/src/nnetbin:$KALDI_ROOT/src/nnet2bin/:$KALDI_ROOT/src/kwsbin:$PWD:$PATH

**Comment by mmilunovic** [comment]
Hi, 

There is a copy-feats.cc. No executables. 
Also yes, I have those lines in the .bashrc file

**Comment by mravanelli** [comment]
This means that the copy-feats.cc has not been compiler for some reason
during the kaldi installation.

Mirco

**Comment by mmilunovic** [comment]
Do you have any idea why, or how should I approach solving this?

**Comment by mravanelli** [comment]
This is a kaldi compilation issue and it is not related with pytorch-kaldi.
I suggest to recompile the sources in src and tools folders (see INSTALL
files for the instructions). Make sure the compilations ends without errors.

Mirco
