### ISSUE TITLE
Transcript my own audio file

### ISSUE THREAD

**Issue by vkdhanaraj** [mravanelli/pytorch-kaldi#179]
Hello, I want to transcript my own audio file. I have it in .wav format. I'am not understanding where exactly to specify the path to .wav file so that the model uses it and produces corresponding text.

_Originally posted by @vkdhanaraj in https://github.com/mravanelli/pytorch-kaldi/issues/70#issuecomment-553757236_

**Comment by TParcollet** [comment]
Hi!

As detailed in the section "How can I transcript my own audio files?" of the README. You first need to create the .scp file! Indeed, it's following the standard Kaldi process.

**Comment by TParcollet** [comment]
Hey, any progress on your problem ?

**Comment by vkdhanaraj** [comment]
Hey. Thank you for your response. 
I'am a beginner, so I couldn't figure out how to generate feats.scp file for my .wav file.

**Comment by TParcollet** [comment]
Then, I would suggest you to follow one of the simplest recipe of Kaldi (TIMIT / WSJ / YESNO) and see of the data dire is build !
