### ISSUE TITLE
Multi-GPU  training performance VS  single-GPU training

### ISSUE THREAD

**Issue by Rpersie** [mravanelli/pytorch-kaldi#18]
I usually use tensorflow to train the acoustic model. And I found that the multi-gpu training performs worse than the single gpu. So I want to know if this project also has this problem ? Thank you !

**Comment by TParcollet** [comment]
Well it depends. In term of training speed, you'll only notice a speed-up when using twice the batch size compared to a mono GPU training. In term of WER or PER, a larger batch size can slightly harm the results ... So yes, it could be faster but slightly worst.

**Comment by Rpersie** [comment]
sometimes, the gap maybe very large. In this project, for example, do you have compared  4-gpu and 1-gpu performance ?  Thanks!

**Comment by mravanelli** [comment]
We haven't done an extensive test for comparing 1-gpu or
multi.gpu performance. My experience (with all the toolkits I tried so
far), hower, is that if we increase too much the number of GPUs there is a
quite significant performance drop (sometimes you can fill this gap by
training for more epochs, but this might neutralize the benefits of having
more GPUS). It could be interesting if some of the users study this aspect
and report add some insights to add to the documentation.

Mirco
