### ISSUE TITLE
how to use pytorch-kaldi to inference? give a audio file ,return the text.

### ISSUE THREAD

**Issue by l2009312042** [mravanelli/pytorch-kaldi#184]
hello ,everyone .It is a great work  about pytorch-kaldi, i study it rencently. but there is no tutorial about how to inference with a given audio file ,can you give a example about how to inference ? thx

**Comment by TParcollet** [comment]
Hey !

To transcript your own audio file, you need to follow this part: How can I transcript my own audio files?

In fact, we do not provide the part .wav -> features, that is related to Kaldi. You just need the feat.scp file with the corresponding *.ark (generated by Kaldi when calling make_mfcc / make_fbank etc ...). And a decoding graph relying on the language model you want to use !

**Comment by TParcollet** [comment]
You can refer at the TIMIT / YESNO / WSJ Kaldi recipes for the features extraction part.

**Comment by l2009312042** [comment]
@TParcollet  thanks for your reply ,i go to have a look at it
