### ISSUE TITLE
data_name = shared_list[0] IndexError: list index out of range

### ISSUE THREAD

**Issue by weienzhang** [mravanelli/pytorch-kaldi#185]
Sorry to bother everyone again ! Recently i have been runnning the TIMIT_liGRU_fmllr model and something weird happened:
![error](https://user-images.githubusercontent.com/24769686/69413532-fb6aa500-0d4b-11ea-8cd8-b749d9aeadff.png)
i checked a few issues related to my error here, then i checked the cfg file and all the folders, it just seemed alright, i also print something like fea_opt which are showed in the screen, and also the TIMIT_liGRU_fmllr.cfg:
`[cfg_proto]
cfg_proto = proto/global.proto
cfg_proto_chunk = proto/global_chunk.proto

[exp]
cmd = 
run_nn_script = run_nn
out_folder = exp/TIMIT_liGRU_fmllr
seed = 4234
use_cuda = True
multi_gpu = False
save_gpumem = False
n_epochs_tr = 24

[dataset1]
data_name = TIMIT_tr
# fea = fea_name=mfcc
# 	fea_lst=quick_test/data/train/feats_mfcc.scp
# 	fea_opts=apply-cmvn --utt2spk=ark:quick_test/data/train/utt2spk  ark:quick_test/mfcc/train_cmvn_speaker.ark ark:- ark:- | add-deltas --delta-order=2 ark:- ark:- |
# 	cw_left=0
# 	cw_right=0
	
# 	fea_name=fbank
# 	fea_lst=quick_test/data/train/feats_fbank.scp
# 	fea_opts=apply-cmvn --utt2spk=ark:quick_test/data/train/utt2spk  ark:quick_test/fbank/cmvn_train.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
# 	cw_left=0
# 	cw_right=0
	
fea = fea_name=fmllr
	fea_lst=/home/zwe/Downloads/kaldi-master/egs/timit/s5/data-fmllr-tri3/train/feats.scp
	#fea_opts=apply-cmvn --utt2spk=ark:/home/zwe/Downloads/kaldi-master/egs/timit/s5/data-fmllr-tri3/train/utt2spk  ark:/home/zwe/Downloads/kaldi-master/egs/timit/s5/mfcc/cmvn_train.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
    fea_opts=apply-cmvn --utt2spk=ark:/home/zwe/Downloads/kaldi-master/egs/timit/s5/data-fmllr-tri3/train/utt2spk  ark:/home/zwe/Downloads/kaldi-master/egs/timit/s5/mfcc/cmvn_train.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
	cw_left=0
	cw_right=0

lab = lab_name=lab_cd
	lab_folder=/home/zwe/Downloads/kaldi-master/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_ali
	lab_opts=ali-to-pdf
	lab_count_file=auto
	lab_data_folder=/home/zwe/Downloads/kaldi-master/egs/timit/s5/data-fmllr-tri3/train/
	lab_graph=/home/zwe/Downloads/kaldi-master/egs/timit/s5/exp/tri3/graph
	
# 	lab_name=lab_mono
# 	lab_folder=quick_test/dnn4_pretrain-dbn_dnn_ali
# 	lab_opts=ali-to-phones --per-frame=true
# 	lab_count_file=none
# 	lab_data_folder=quick_test/data/train/
# 	lab_graph=quick_test/graph
n_chunks = 5

[dataset2]
data_name = TIMIT_dev
# fea = fea_name=mfcc
# 	fea_lst=/home/zwe/Downloads/kaldi-master/egs/timit/s5/data-fmllr-tri3/dev/feats.scp
# 	fea_opts=apply-cmvn --utt2spk=ark:/home/zwe/Downloads/kaldi-master/egs/timit/s5/data-fmllr-tri3/dev/utt2spk  ark:/home/zwe/Downloads/kaldi-master/egs/timit/s5/mfcc/cmvn_dev.ark ark:- ark:- | add-deltas --delta-order=2 ark:- ark:- |
# 	cw_left=0
# 	cw_right=0
	
# 	fea_name=fbank
# 	fea_lst=quick_test/data/dev/feats_fbank.scp
# 	fea_opts=apply-cmvn --utt2spk=ark:quick_test/data/dev/utt2spk  ark:quick_test/fbank/cmvn_dev.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
# 	cw_left=0
# 	cw_right=0
	
fea = fea_name=fmllr
	fea_lst=/home/zwe/Downloads/kaldi-master/egs/timit/s5/data-fmllr-tri3/dev/feats.scp
	fea_opts=apply-cmvn --utt2spk=ark:/home/zwe/Downloads/kaldi-master/egs/timit/s5/data-fmllr-tri3/dev/utt2spk  ark:/home/zwe/Downloads/kaldi-master/egs/timit/s5/mfcc/cmvn_dev.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
	cw_left=0
	cw_right=0
lab = lab_name=lab_cd
	lab_folder=/home/zwe/Downloads/kaldi-master/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_ali_dev
	lab_opts=ali-to-pdf
	lab_count_file=auto
	lab_data_folder=/home/zwe/Downloads/kaldi-master/egs/timit/s5/data-fmllr-tri3/dev/
	lab_graph=/home/zwe/Downloads/kaldi-master/egs/timit/s5/exp/tri3/graph
	
# 	lab_name=lab_mono
# 	lab_folder=quick_test/dnn4_pretrain-dbn_dnn_ali_dev
# 	lab_opts=ali-to-phones --per-frame=true
# 	lab_count_file=none
# 	lab_data_folder=quick_test/data/dev/
# 	lab_graph=quick_test/graph
n_chunks = 1

[dataset3]
data_name = TIMIT_test
# fea = fea_name=mfcc
# 	fea_lst=/home/zwe/Downloads/kaldi-master/egs/timit/s5/data-fmllr-tri3/test/feats.scp
# 	fea_opts=apply-cmvn --utt2spk=ark:/home/zwe/Downloads/kaldi-master/egs/timit/s5/data-fmllr-tri3/test/utt2spk  ark:/home/zwe/Downloads/kaldi-master/egs/timit/s5/mfcc/cmvn_dev.ark ark:- ark:- | add-deltas --delta-order=2 ark:- ark:- |
# 	cw_left=0
# 	cw_right=0
	
# 	fea_name=fbank
# 	fea_lst=quick_test/data/test/feats_fbank.scp
# 	fea_opts=apply-cmvn --utt2spk=ark:quick_test/data/test/utt2spk  ark:quick_test/fbank/cmvn_test.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
# 	cw_left=0
# 	cw_right=0
	
fea = fea_name=fmllr
	fea_lst=/home/zwe/Downloads/kaldi-master/egs/timit/s5/data-fmllr-tri3/test/feats.scp
	fea_opts=apply-cmvn --utt2spk=ark:/home/zwe/Downloads/kaldi-master/egs/timit/s5/data-fmllr-tri3/test/utt2spk  ark:/home/zwe/Downloads/kaldi-master/egs/timit/s5/mfcc/cmvn_dev.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
	cw_left=0
	cw_right=0
lab = lab_name=lab_cd
	lab_folder=/home/zwe/Downloads/kaldi-master/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_ali_test
	lab_opts=ali-to-pdf
	lab_count_file=auto
	lab_data_folder=/home/zwe/Downloads/kaldi-master/egs/timit/s5/data-fmllr-tri3/test/
	lab_graph=/home/zwe/Downloads/kaldi-master/egs/timit/s5/exp/tri3/graph
	
# 	lab_name=lab_mono
# 	lab_folder=quick_test/dnn4_pretrain-dbn_dnn_ali_test
# 	lab_opts=ali-to-phones --per-frame=true
# 	lab_count_file=none
# 	lab_data_folder=quick_test/data/test/
# 	lab_graph=quick_test/graph
n_chunks = 1

[data_use]
train_with = TIMIT_tr
valid_with = TIMIT_dev
forward_with = TIMIT_test

[batches]
batch_size_train = 8
max_seq_length_train = 1000
increase_seq_length_train = True
start_seq_len_train = 100
multply_factor_seq_len_train = 2
batch_size_valid = 8
max_seq_length_valid = 1000

[architecture1]
arch_name = liGRU_layers
arch_proto = proto/liGRU.proto
arch_library = neural_networks
arch_class = liGRU
arch_pretrain_file = none
arch_freeze = False
arch_seq_model = True
ligru_lay = 550,550,550,550,550
ligru_drop = 0.2,0.2,0.2,0.2,0.2
ligru_use_laynorm_inp = False
ligru_use_batchnorm_inp = False
ligru_use_laynorm = False,False,False,False,False
ligru_use_batchnorm = True,True,True,True,True
ligru_bidir = True
ligru_act = relu,relu,relu,relu,relu
ligru_orthinit = True
arch_lr = 0.0004
arch_halving_factor = 0.5
arch_improvement_threshold = 0.001
arch_opt = rmsprop
opt_momentum = 0.0
opt_alpha = 0.95
opt_eps = 1e-8
opt_centered = False
opt_weight_decay = 0.0

[architecture2]
arch_name = MLP_layers
arch_proto = proto/MLP.proto
arch_library = neural_networks
arch_class = MLP
arch_pretrain_file = none
arch_freeze = False
arch_seq_model = False
dnn_lay = N_out_lab_cd
dnn_drop = 0.0
dnn_use_laynorm_inp = False
dnn_use_batchnorm_inp = False
dnn_use_batchnorm = False
dnn_use_laynorm = False
dnn_act = softmax
arch_lr = 0.0004
arch_halving_factor = 0.5
arch_improvement_threshold = 0.001
arch_opt = rmsprop
opt_momentum = 0.0
opt_alpha = 0.95
opt_eps = 1e-8
opt_centered = False
opt_weight_decay = 0.0

# [architecture3]
# arch_name = MLP_layers2
# arch_proto = proto/MLP.proto
# arch_library = neural_networks
# arch_class = MLP
# arch_pretrain_file = none
# arch_freeze = False
# arch_seq_model = False
# dnn_lay = N_out_lab_mono
# dnn_drop = 0.0
# dnn_use_laynorm_inp = False
# dnn_use_batchnorm_inp = False
# dnn_use_batchnorm = False
# dnn_use_laynorm = False
# dnn_act = softmax
# arch_lr = 0.0004
# arch_halving_factor = 0.5
# arch_improvement_threshold = 0.001
# arch_opt = rmsprop
# opt_momentum = 0.0
# opt_alpha = 0.95
# opt_eps = 1e-8
# opt_centered = False
# opt_weight_decay = 0.0

[model]
model_proto = proto/model.proto
model = out_dnn1=compute(liGRU_layers,fmllr)
	out_dnn2=compute(MLP_layers,out_dnn1)
	#out_dnn3=compute(MLP_layers2,out_dnn1)
	#loss_mono=cost_nll(out_dnn3,lab_mono)
	#loss_mono_w=mult_constant(loss_mono,1.0)
	loss_final=cost_nll(out_dnn2,lab_cd)
	#loss_final=sum(loss_cd,loss_mono_w)
	err_final=cost_err(out_dnn2,lab_cd)

[forward]
forward_out = out_dnn2
normalize_posteriors = True
normalize_with_counts_from = lab_cd
save_out_file = False
require_decoding = True

[decoding]
decoding_script_folder = kaldi_decoding_scripts/
decoding_script = decode_dnn.sh
decoding_proto = proto/decoding.proto
min_active = 200
max_active = 7000
max_mem = 50000000
beam = 13.0
latbeam = 8.0
acwt = 0.2
max_arcs = -1
skip_scoring = false
scoring_script = local/score.sh
scoring_opts = "--min-lmwt 1 --max-lmwt 10"
norm_vars = False
`
Could you help me out of this ! Thank you !

**Comment by chijiudao** [comment]
Have you solved the problem?

**Comment by weienzhang** [comment]
> Have you solved the problem?

no...

**Comment by mravanelli** [comment]
Hi,
the error that you see means that you are not able to read the features or
the labels correctly (note that before running pytorch-kaldi you have to
run the timit kaldi recipe).
To debug this error, I suggest to load the features and labels manually in
the following way:
1- go to the scp file (e.g. data/train/feats.scp) and copy the second
column of one row (e.g,
/home/mirco/kaldi-trunk/egs/timit/s5/fbank/raw_fbank_train.1.ark),
2- make sure that this file exists.
3- open the terminal and write:
copy-feats
ark:/home/mirco/kaldi-trunk/egs/timit/s5/fbank/raw_fbank_train.1.ark
ark,t:- | more
make sure there are no errors running the script.
4- copy the feature options that you have in your config file (e.g,
apply-cmvn --utt2spk=ark:quick_test/data/train/utt2spk
ark:quick_test/mfcc/train_cmvn_speaker.ark ark:- ark:- | add-deltas --
delta-order=2 ark:- ark:- |) and add them into the command in this way:
copy-feats
ark:/home/mirco/kaldi-trunk/egs/timit/s5/fbank/raw_fbank_train.1.ark ark:-
| apply-cmvn --utt2spk=ark:quick_test/data/train/utt2spk
ark:quick_test/mfcc/train_cmvn_speaker.ark ark:- ark:- | add-deltas --
delta-order=2 ark:- ark,t:- | more
make sure there are no errors when you execute this command.
5-check the labels, by running:
gunzip -c $your_lab_folder/ali.*.gz | $your_lab_folder//final.mdl ark:-
ark,t:- | more
where $your_lab_folder is the one you set in the config file (see
lab_folder)

Most likely your error is due to a path that is wrong or something like
this.

Best,

Mirco

**Comment by TParcollet** [comment]
Is it solved ?
