### ISSUE TITLE
Decoding questions

### ISSUE THREAD

**Issue by Baksonator** [mravanelli/pytorch-kaldi#188]
Hello Mirco, Titouan and Yoshua,

First of all, one massive thank you for this amazing repository and toolkit, it is really helpful.

Next, I'll get right into the issues I am having. Please note that I am a complete novice for Kaldi, and I've only been researching speech recognition for about a month and a half, so if I am asking some pretty obvious questions, sorry about that, and please bear with me.

I have been following this guide and I successfully completed it for my own dataset: https://eleanorchodroff.com/tutorial/kaldi/index.html

Then, I tried to use the files I got with your tool. I did manage to actually train the model, largely following your TIMIT tutorial altered to use my data set. Then, when it came to testing, I realized I did not have a decoding graph, but I also managed to create it. 

Finally, the issue I am having right now is actually decoding the outputs I feed through the network. I suspect what the issue might be, but I am asking anyways since I have a few other questions as well. 

Now, since I did not use any finished recipe for Kaldi, but rather followed a few guides, I ran into issue like not having the decoding graph. That is also probably the source of my current issue. Right now, this is what I see in my log file:

![log_file](https://user-images.githubusercontent.com/43252088/70312046-1db3f680-1813-11ea-950d-71a046c9987b.png)

And this is the decode part of my configuration file:

![cfg_file](https://user-images.githubusercontent.com/43252088/70312037-18ef4280-1813-11ea-8370-c050adda579f.png)

Obviously, I do not have the lattice file created. However, I suspect I might not need to, and that the real issue is that I am trying to run the decoding script decode_dnn.sh. I am thinking this is the wrong script, and maybe I should use something else, since I have not been using and do not have dnn alignments, just regular ones. Are lattices only needed in the case when you are using those alignments? I am wondering since you mention that only features and feature lists and the decoding graph are needed for actually transcribing files, but not lattices, and since it's still hard for me to find my way around Kaldi, acquiring those lattices is a big step for me. Furthermore, when I checked the [Kaldi for Dummies tutorial](https://kaldi-asr.org/doc/kaldi_for_dummies.html), there's no mentioning of those lattices, so I find them really confusing.

Also, I assume that the decoding graph I need for transcribing files needs to be created for the data set I am transcribing, I can't just use the same one I have from training, validation or test data?

Once more, sorry if the questions are obvious, but I am really new to all of this. If you need any more clarification on the issues I am having, I'll respond as thoroughly as I can. Thanks in advance!

**Comment by TParcollet** [comment]
Hi there ! Thank you for using our toolkit ! 

From the first screenshot, we can see that the missing file is a forward_*_.ark file. Meaning that something went wrong in the forwarding of PyTorch-Kaldi. Could you please provide the console output (PyTorch-kaldi visual feedback) at the end of the training / testing phase ? It might simply be that your testing files are not found. From what I see, it's not a decoding error but a forward error (it does not mean that you won't have a decoding error latter on).

**Comment by Baksonator** [comment]
Thanks for the prompt response!

Here is the final part of the output I'm getting from running run_exp.py:

![testing_output](https://user-images.githubusercontent.com/43252088/70317682-8785cd80-181e-11ea-92c5-08dd7298fc45.png)

Also, here's my full configuration file: 
[mycorp_mlp_mfcc.zip](https://github.com/mravanelli/pytorch-kaldi/files/3931803/mycorp_mlp_mfcc.zip)

**Comment by TParcollet** [comment]
you could try to remove any forward_TIMIT_test* in the exp files and re-call the training (it should just run the forward phase of the test)

**Comment by Baksonator** [comment]
I'll try that out and I will get back to you with the results, thanks.

**Comment by Baksonator** [comment]
Hey Titouan,

I've done as you instructed, and now this is the final part of my log file:

![log_file (2)](https://user-images.githubusercontent.com/43252088/70425994-8e0c8300-1a72-11ea-9e97-7215f7f5ef7c.png)

**Comment by TParcollet** [comment]
As indicated here, the transcription file is missing and needed to score the transcription.

**Comment by Baksonator** [comment]
I managed to make it work, I just had to change the scoring script to "score_basic.sh" since I did not have these transcription files. In any case, thank you very much, you have been very helpful! I hope you have a lot of success with this project as well as others, I'll certainly continue to use it!

**Comment by chijiudao** [comment]
Hi,sir! I have the same problem. So you have solved it?
> I managed to make it work, I just had to change the scoring script to "score_basic.sh" since I did not have these transcription files. In any case, thank you very much, you have been very helpful! I hope you have a lot of success with this project as well as others, I'll certainly continue to use it!
