### ISSUE TITLE
nn alignments in TIMIT tutorial

### ISSUE THREAD

**Issue by dori2063** [mravanelli/pytorch-kaldi#19]
Hi, I'm following your TIMIT tutorial.
And... I'm stuck in step 4.
I could use the first two commands, but last two were not possible.
I thought it can be ignored, but step 7' command required the outputs of those.
Sorry, if this is a basic issue .. Can I get some comments..?

**Comment by TParcollet** [comment]
Hi ! 
Have you run the full standard Kaldi TIMIT recipe (with the local/nnet/run_dnn.sh part) ? If not, check Line 144 of the run.sh script : exit 0 # From this point you can run Karel's DNN : local/nnet/run_dnn.sh. You actually HAVE to run this part if you want to use the DNN alignement. Also you don't need to run both the tri3b and DNN alignements (Since you only need one of them during for training)

**Comment by vyraun** [comment]
@TParcollet @dori2063  Hi, could you take a look at this issue: https://github.com/mravanelli/pytorch-kaldi/issues/29? I am not getting all the test and train files in timit exp folder after running run.sh as in the intructions. Maybe I am missing some command, going through the instruction steps again didn't help as well. Thanks.

**Comment by dori2063** [comment]
Hi! 
Have you tried "TIMIT tutorial" step 4, which is making "test, dev" align files"?
I think that is an answer.
Origin Kaldi run.sh doesn't make "test, dev" align files.

**Comment by vyraun** [comment]
@dori2063 Thanks for the reply! I was getting an error in step 4 only, while trying to generated the align files. The error I was getting while running step 4 dnn commands, was file not found. So, it seems run.sh or any earlier step is failing to create some files..let me try to replicate the exact error message again.

**Comment by vyraun** [comment]
The error message comes up in the 4th step:

steps/nnet/align.sh --nj 4 data-fmllr-tri3/dev data/lang exp/dnn4_pretrain-dbn_dnn exp/dnn4_pretrain-dbn_dnn_ali_dev
steps/nnet/align.sh --nj 4 data-fmllr-tri3/dev data/lang exp/dnn4_pretrain-dbn_dnn exp/dnn4_pretrain-dbn_dnn_ali_dev
cp: cannot stat 'exp/dnn4_pretrain-dbn_dnn/tree': No such file or directory
cp: cannot stat 'exp/dnn4_pretrain-dbn_dnn/final.mdl': No such file or directory

I ran run.sh with the exit 0 command removed from the script at line 144.

**Comment by dori2063** [comment]
In my case, I just remained line 144.
Then I executed only the run_dnn.
So, actually, I don't know the rest of the run file.
Is there any problem in other combinations?

**Comment by vyraun** [comment]
@dori2063 thanks, so only run_dnn.sh command needs to be in the run.sh file after the MFCC feature extraction step?

**Comment by dori2063** [comment]
Oh, I was meaning you don't need to edit run.sh.
run_dnn just requires only the output of run.sh (about tri3 things).

**Comment by vyraun** [comment]
Hi @dori2063 The alignment step now works. However, I am getting an error in the last step now.

python run_exp.py cfg/TIMIT_baselines/TIMIT_MLP_mfcc_basic.cfg

Reading config file......OK!
Chunk creation......OK!
------------------------------ Epoch 000 / 023 ------------------------------
Training TIMIT_tr chunk = 1 / 5
ERROR: training epoch 0, chunk 0 not done! File exp/TIMIT_MLP_basic/exp_files/train_TIMIT_tr_ep000_ck00.info does not exist.
See exp/TIMIT_MLP_basic/log.log

Some step is still missing it seems.

**Comment by zdgithub** [comment]
@TParcollet  Hi, after the `run.sh`, I executed the `./local/nnet/run_dnn.sh`. But the error occurred in the last line:
```
steps/nnet/make_fmllr_feats.sh --nj 10 --cmd run.pl --mem 4G --transform-dir exp/tri3/decode_test data-fmllr-tri3/test data/test exp/tri3 data-fmllr-tri3/test/log data-fmllr-tri3/test/data
steps/nnet/make_fmllr_feats.sh: feature type is lda_fmllr
utils/copy_data_dir.sh: copied data from data/test to data-fmllr-tri3/test
utils/validate_data_dir.sh: Successfully validated data-directory data-fmllr-tri3/test
steps/nnet/make_fmllr_feats.sh: Done!, type lda_fmllr, data/test --> data-fmllr-tri3/test, using : raw-trans None, gmm exp/tri3, trans exp/tri3/decode_test
steps/nnet/make_fmllr_feats.sh --nj 10 --cmd run.pl --mem 4G --transform-dir exp/tri3/decode_dev data-fmllr-tri3/de
s exp/tri3/decode_test
steps/nnet/make_fmllr_feats.sh --nj 10 --cmd run.pl --mem 4G --transform-dir exp/tri3/decode_dev data-fmllr-tri3/dev data/dev exp/tri3 data-fmllr-tri3/dev/log data-fmllr-tri3/dev/data
steps/nnet/make_fmllr_feats.sh: feature type is lda_fmllr
utils/copy_data_dir.sh: copied data from data/dev to data-fmllr-tri3/dev
utils/validate_data_dir.sh: Successfully validated data-directory data-fmllr-tri3/dev
steps/nnet/make_fmllr_feats.sh: Done!, type lda_fmllr, data/dev --> data-fmllr-tri3/dev, using : raw-trans None, gmm exp/tri3, trans exp/tri3/decode_dev
steps/nnet/make_fmllr_feats.sh --nj 10 --cmd run.pl --mem 4G --transform-dir exp/tri3_ali data-fmllr-tri3/train data/train exp/tri3 data-fmllr-tri3/train/log data-fmllr-tri3/train/data
fmllr-tri3/train/data
steps/nnet/make_fmllr_feats.sh: feature type is lda_fmllr
utils/copy_data_dir.sh: copied data from data/train to data-fmllr-tri3/train
utils/validate_data_dir.sh: Successfully validated data-directory data-fmllr-tri3/train
steps/nnet/make_fmllr_feats.sh: Done!, type lda_fmllr, data/train --> data-fmllr-tri3/train, using : raw-trans None, gmm exp/tri3, trans exp/tri3_ali
Speakers, src=462, trn=416, cv=46 /tmp/zhanghao_jiVvW/speakers_cv
utils/data/subset_data_dir.sh: reducing #utt from 3696 to 3328
utils/data/subset_data_dir.sh: reducing #utt from 3696 to 368
./local/nnet/run_dnn.sh: line 56: exp/dnn4_pretrain-dbn/log/pretrain_dbn.log: No such file or directory
```

**Comment by MaddyThakker** [comment]
Hi, I am also facing the exact error? Did anyone find the solution to this?

**Comment by mravanelli** [comment]
This looks more a Kaldi-related issue. When you downloaded the toolkit?
Could you post here the /local/nnet/run_dnn.sh file?

Thank you

Best,

**Comment by MaddyThakker** [comment]
This is my /local/nnet/run_dnn.sh file. 
```
#!/bin/bash

# Copyright 2012-2014  Brno University of Technology (Author: Karel Vesely)
# Apache 2.0

# This example script trains a DNN on top of fMLLR features. 
# The training is done in 3 stages,
#
# 1) RBM pre-training:
#    in this unsupervised stage we train stack of RBMs, 
#    a good starting point for frame cross-entropy trainig.
# 2) frame cross-entropy training:
#    the objective is to classify frames to correct pdfs.
# 3) sequence-training optimizing sMBR: 
#    the objective is to emphasize state-sequences with better 
#    frame accuracy w.r.t. reference alignment.

. ./cmd.sh ## You'll want to change cmd.sh to something that will work on your system.
           ## This relates to the queue.

. ./path.sh ## Source the tools/utils (import the queue.pl)

# Config:
gmmdir=exp/tri3
data_fmllr=data-fmllr-tri3
stage=0 # resume training with --stage=N
# End of config.
. utils/parse_options.sh || exit 1;
#

if [ $stage -le 0 ]; then
  # Store fMLLR features, so we can train on them easily,
  # test
  dir=$data_fmllr/test
  steps/nnet/make_fmllr_feats.sh --nj 10 --cmd "$train_cmd" \
     --transform-dir $gmmdir/decode_test \
     $dir data/test $gmmdir $dir/log $dir/data || exit 1
  # dev
  dir=$data_fmllr/dev
  steps/nnet/make_fmllr_feats.sh --nj 10 --cmd "$train_cmd" \
     --transform-dir $gmmdir/decode_dev \
     $dir data/dev $gmmdir $dir/log $dir/data || exit 1
  # train
  dir=$data_fmllr/train
  steps/nnet/make_fmllr_feats.sh --nj 10 --cmd "$train_cmd" \
     --transform-dir ${gmmdir}_ali \
     $dir data/train $gmmdir $dir/log $dir/data || exit 1
  # split the data : 90% train 10% cross-validation (held-out)
  utils/subset_data_dir_tr_cv.sh $dir ${dir}_tr90 ${dir}_cv10 || exit 1
fi

if [ $stage -le 1 ]; then
  # Pre-train DBN, i.e. a stack of RBMs (small database, smaller DNN)
  dir=exp/dnn4_pretrain-dbn
  (tail --pid=$$ -F $dir/log/pretrain_dbn.log 2>/dev/null)& # forward log
  $cuda_cmd $dir/log/pretrain_dbn.log \
    steps/nnet/pretrain_dbn.sh --hid-dim 1024 --rbm-iter 20 $data_fmllr/train $dir || exit 1;
fi

if [ $stage -le 2 ]; then
  # Train the DNN optimizing per-frame cross-entropy.
  dir=exp/dnn4_pretrain-dbn_dnn
  ali=${gmmdir}_ali
  feature_transform=exp/dnn4_pretrain-dbn/final.feature_transform
  dbn=exp/dnn4_pretrain-dbn/6.dbn
  (tail --pid=$$ -F $dir/log/train_nnet.log 2>/dev/null)& # forward log
  # Train
  $cuda_cmd $dir/log/train_nnet.log \
    steps/nnet/train.sh --feature-transform $feature_transform --dbn $dbn --hid-layers 0 --learn-rate 0.008 \
    $data_fmllr/train_tr90 $data_fmllr/train_cv10 data/lang $ali $ali $dir || exit 1;
  # Decode (reuse HCLG graph)
  steps/nnet/decode.sh --nj 20 --cmd "$decode_cmd" --acwt 0.2 \
    $gmmdir/graph $data_fmllr/test $dir/decode_test || exit 1;
  steps/nnet/decode.sh --nj 20 --cmd "$decode_cmd" --acwt 0.2 \
    $gmmdir/graph $data_fmllr/dev $dir/decode_dev || exit 1;
fi


# Sequence training using sMBR criterion, we do Stochastic-GD 
# with per-utterance updates. We use usually good acwt 0.1
dir=exp/dnn4_pretrain-dbn_dnn_smbr
srcdir=exp/dnn4_pretrain-dbn_dnn
acwt=0.2

if [ $stage -le 3 ]; then
  # First we generate lattices and alignments:
  steps/nnet/align.sh --nj 20 --cmd "$train_cmd" \
    $data_fmllr/train data/lang $srcdir ${srcdir}_ali || exit 1;
  steps/nnet/make_denlats.sh --nj 20 --cmd "$decode_cmd" --acwt $acwt \
    --lattice-beam 10.0 --beam 18.0 \
    $data_fmllr/train data/lang $srcdir ${srcdir}_denlats || exit 1;
fi

if [ $stage -le 4 ]; then
  # Re-train the DNN by 6 iterations of sMBR 
  steps/nnet/train_mpe.sh --cmd "$cuda_cmd" --num-iters 6 --acwt $acwt \
    --do-smbr true \
    $data_fmllr/train data/lang $srcdir ${srcdir}_ali ${srcdir}_denlats $dir || exit 1
  # Decode
  for ITER in 1 6; do
    steps/nnet/decode.sh --nj 20 --cmd "$decode_cmd" \
      --nnet $dir/${ITER}.nnet --acwt $acwt \
      $gmmdir/graph $data_fmllr/test $dir/decode_test_it${ITER} || exit 1
    steps/nnet/decode.sh --nj 20 --cmd "$decode_cmd" \
      --nnet $dir/${ITER}.nnet --acwt $acwt \
      $gmmdir/graph $data_fmllr/dev $dir/decode_dev_it${ITER} || exit 1
  done 
fi

echo Success
exit 0

# Getting results [see RESULTS file]
# for x in exp/*/decode*; do [ -d $x ] && grep WER $x/wer_* | utils/best_wer.sh; done

```

**Comment by mravanelli** [comment]
I'm not able to replicate the issue (to me everything is working). Are you
sure you are working on a machine with a cuda GPU?


Mirco

**Comment by MaddyThakker** [comment]
Yes, I have NVIDIA GEFORCE 940MX as my GPU.  
My `/kaldi/egs/timit/s5/exp` has the following files -
 `combine_2,                  mono,      sgmm2_4_ali,       tri1,      tri2_ali,  tri3_ali_dev,   ubm4,
dnn4_pretrain-dbn_dnn_ali,  mono_ali,  sgmm2_4_denlats,   tri1_ali,  tri3,      tri3_ali_test,
make_mfcc,                  sgmm2_4  , sgmm2_4_mmi_b0.1,  tri2,      tri3_ali,  tri4_nnet `

There is no "dnn4_pretrain-dbn_dnn" folder or file. When are such files generated? I know I am asking a very vague question, this is because I am not very familiar with Kaldi. 
Thanks for your quick replies and help.

**Comment by mravanelli** [comment]
what happens if you comment the line 56?

Mirco

**Comment by MaddyThakker** [comment]
The error was indeed because of Cuda not being installed properly. After installing Cuda and configuring it works without any error. Thanks for your help.

**Comment by Originofamonia** [comment]
Hello @MaddyThakker ,
I'm facing the same problem as you. Can you tell me how is the problem solved?
Thanks!

**Comment by sabolfazlgh** [comment]
Hello everyone,

I had the same problem, and after trying everything suggested in this page, I realized the problem was with kaldi not recognizing cuda.
During installation of kaldi, you have to configure it to use cuda and if you don't do that, you will face this issue.
Hope it helps!

**Comment by EklavyaFCB** [comment]
I solved this problem by updating my `cmd.sh` which was missing the `export cuda_cmd="queue.pl --config $queue_conf --gpu 1 --mem 10G --tmp 40G"` command. (I updated it to correspond to my lab's SGE grid).
