### ISSUE TITLE
Decode issue

### ISSUE THREAD

**Issue by chijiudao** [mravanelli/pytorch-kaldi#190]
Hi, Sir! Sorry to bother you. I don't know how to solve the problem as follows. Could you give me some suggestions? Thank you so much.
![de](https://user-images.githubusercontent.com/39076097/70993619-5901cf80-2107-11ea-8026-17bc849cf68e.png)
![lo](https://user-images.githubusercontent.com/39076097/70993721-8a7a9b00-2107-11ea-9b8e-ec059c25e7e5.png)

**Comment by TParcollet** [comment]
Could you please provide us the content of the best_path.1.1.log as suggested in the log ?

Thank you

**Comment by chijiudao** [comment]
Thanks for your reply! The best_path.1.1.log is as follows:
![best_path](https://user-images.githubusercontent.com/39076097/71087160-76519f00-21d6-11ea-943e-39c98bd67884.png)

> Could you please provide us the content of the best_path.1.1.log as suggested in the log ?
> 
> Thank you

**Comment by TParcollet** [comment]
Okay, so something went wrong with the forward phase since lattices are empty. Could please erase all forward_* in your exp_files/ directory, alongside with all decod* directory in your experiment directory ? It's just to run the forward phase of the test again. Also please consider verifying that the testing audio files you provide exist.

**Comment by chijiudao** [comment]
Thank you Sir. I try it with your suggestion: delete the forward_* files ,  decode* directory, and the testing audio files exists. While there is still the issue.
> Okay, so something went wrong with the forward phase since lattices are empty. Could please erase all forward_* in your exp_files/ directory, alongside with all decod* directory in your experiment directory ? It's just to run the forward phase of the test again. Also please consider verifying that the testing audio files you provide exist.

**Comment by TParcollet** [comment]
Could you then try to launch manually via the prompt the last command of the log.log file (the one that failed)?

**Comment by chijiudao** [comment]
Sorry Sir. I don't understand this step.
> Could you then try to launch manually via the prompt the last command of the log.log file (the one that failed)?

**Comment by TParcollet** [comment]
This cmd: 
<img width="657" alt="Capture d’écran 2019-12-20 à 13 44 22" src="https://user-images.githubusercontent.com/11910731/71255684-dfe4c100-232e-11ea-9a02-c4379d98a407.png"> Could you try to execute it directly ?
