### ISSUE TITLE
Some thread errors

### ISSUE THREAD

**Issue by gezhaoDL** [mravanelli/pytorch-kaldi#191]
Hi,sir，When i use PyTorch-Kaldi toolkit based on the THCHS-30 dataset.Some epochs work fine，but others  throw error like this.Could you tell me why this happened？
`Exception in thread Thread-639:
Traceback (most recent call last): 
  
  File "/root/anaconda3/envs/py37_gz/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()

  File "/root/anaconda3/envs/py37_gz/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)

  File "/home/rd/gz/pytorch-kaldi/data_io.py", line 732, in cleanup
    raise SubprocessFailed("cmd %s returned %d !" % (cmd, ret))

data_io.SubprocessFailed: cmd gunzip -c /home/rd/gz/kaldi/egs/thchs30/s5/exp/tri3b_ali/ali*.gz | ali-to-pdf /home/rd/gz/kaldi/egs/thchs30/s5/exp/tri3b_ali/final.mdl ark:- ark:- returned 134 !`

**Comment by TParcollet** [comment]
Hi ! What if you directly call this command from the prompt. Is it working?

**Comment by gezhaoDL** [comment]
> Hi ! What if you directly call this command from the prompt. Is it working?

Thank you for your reply，I rerun Kaldi's process and the error disappears.
