### ISSUE TITLE
score issue

### ISSUE THREAD

**Issue by jiashihuigithub** [mravanelli/pytorch-kaldi#195]
Error: Unable to stat GLM file '/home/jiashihui/open_source/pytorch-kaldi-master/exp/AISHELL_MLP_mfcc/decode_AISHELL_test_out_dnn2/scoring/glm_39phn' at /home/jiashihui/open_source/kaldi-trunk/tools/sctk/bin/hubscr.pl line 265.

what's glm_39phn, why i don't have it?

**Comment by mravanelli** [comment]
Are you running an experiment with TIMIT or with something else?

Best,

Mirco

**Comment by Subohao** [comment]
Hi, 
I do have some similar issues of scoring,
log file shows that 
--------------------------------------------------------------------------------
Cannot open transcription file '.../data/test/stm': No such file or directory
cp: cannot stat '.../data/test/glm': No such file or directory
--------------------------------------------------------------------------------
May I ask what should be contain in stm and glm file,
should I prepare it in the kaldi script or it will be generated during run_exp.py?

**Comment by Subohao** [comment]
Hi, @mravanelli could u help me if you are free?
Thx a lot!

**Comment by mravanelli** [comment]
Hi, If you change dataset you also have to use a different scoring function. Probably you just have to point to the right scoring function:

scoring_script = local/score.sh
