### ISSUE TITLE
How can I get a single %PER for a input

### ISSUE THREAD

**Issue by s104323002** [mravanelli/pytorch-kaldi#196]
Hello, thanks for your attention.
First of all, its a amazing toolkit that really really help those study in speech area. I really want to appreciate for you contribution and kindness.

I have a question about: Is there any way to feed model a single input (e.g. MFCC of a frame and its context, that is all the input which model needed) and get a single %PER (e.g. after decoding process).

I know its not a function in toolkit, but could you give some direction or the way to fulfill this. Thanks a lot.

**Comment by mravanelli** [comment]
Hi,
thank you very much for your interest into the project. I'm not sure about the usefulness of this operation (if you feed a single input, the decoding process doesn't really make sense and likely runs into some errors).  However, one way is to save kaldi ark files that are composed of a single feature and see what happens. To fugure out how to read/write kaldi feature files with python, you can take a look into this project https://github.com/vesis84/kaldi-io-for-python
