### ISSUE TITLE
is lab_count_file not used?

### ISSUE THREAD

**Issue by Joefi** [mravanelli/pytorch-kaldi#200]
Hi, I read the readme and the config file of TIMIT, I noticed the lab_count_file field, but I found this field seems not used when  I reading the code. the count file is actually is specified or generated according to the normalize_with_counts_from field. If the lab_count_file field is used, could you please tell where used this field in code? Thank you.

**Comment by TParcollet** [comment]
Hi ! This is the function you are looking for: `load_counts `

**Comment by Joefi** [comment]
> Hi ! This is the function you are looking for: `load_counts `. From data_io.py

Thank you for your reply. em....,  the function load_counts read the file specified by "the normalize_with_counts_from" field.  so I think it did not use the lab_count_file field of the config file.

**Comment by TParcollet** [comment]
Oh yes sorry I got confused by the name. I wonder if this option isn't linked to our pre-refactored code. @mravanelli is this field still used? Or is just a Kaldi option. From what I see, and as stated by @Joefi, this field isn't used in data_io and core.

**Comment by mravanelli** [comment]
Hi,
the count file is used to normalize the posterior probabilities before doing the HMM decoding. It is used here:

**Comment by Joefi** [comment]
sorry, I forgot to close this issue. I got it. Thank you again.
