### ISSUE TITLE
Phones in ctm have zero duration

### ISSUE THREAD

**Issue by kevinmchu** [mravanelli/pytorch-kaldi#202]
I trained and tested the TIMIT MLP basic model, and I obtained a CTM file where some of the phones have a duration of zero. What is the purpose of hypothesizing phones with zero duration?
[ctm_39phn.txt](https://github.com/mravanelli/pytorch-kaldi/files/4030934/ctm_39phn.txt)

**Comment by mravanelli** [comment]
Hi,
interesting point. In pytorch-kaldi we inherit the kaldi decoder and this might be a question that it is better to ask into the kaldi project.
