### ISSUE TITLE
Issue:IndexError: list index out of range

### ISSUE THREAD

**Issue by chijiudao** [mravanelli/pytorch-kaldi#203]
Hi,sir!
 I set  "save_out_file = True" , and use the .ark file as new feature. While there are some problems as follows:
![zhongduan](https://user-images.githubusercontent.com/39076097/71980645-87cd1a80-325b-11ea-94c6-2b9f9d8cf6c1.png)
Thank you so much! And here is the log:
[log.log](https://github.com/mravanelli/pytorch-kaldi/files/4035397/log.log)

**Comment by aziryasin** [comment]
Did you fix it? How?
