### ISSUE TITLE
How to load my pretrained model.

### ISSUE THREAD

**Issue by couragelfyang** [mravanelli/pytorch-kaldi#207]
I have an another model pretrained using pytorch and I want to use such model in pytorch-kaldi. Is there any way in pytorch-kaldi to read and load my model (saved in pytorch format) and proceed?

**Comment by mravanelli** [comment]
I think you can take a look into the models that are already implemented and create a new model that performs the computations you need. Note that you need to specify not only the parameters that you saved, but also the related computations.

**Comment by yanglongfei908** [comment]
@mravanelli 
Thanks for your information. But I'm a little confused about the process. What do you mean the related computations? Is there any difference about network computations in pytorch-kaldi?
For example, suppose I have a pretrained model with 3 dense layers, what should be modified?
