### ISSUE TITLE
Error in labels / final.mdl

### ISSUE THREAD

**Issue by bsutapa** [mravanelli/pytorch-kaldi#208]
I got the same error as #185 (data_name = shared_list[0] IndexError: list index out of range) while running TIMIT_LSTM_mfcc.cfg, so I followed the steps suggested by  mravanelli to check if all paths were okay. N.B. I am using only the mfcc features and commented out the parts with fbank and fmllr features. 
1- files listed in scp file exists  in correct path
3- copy-feats ark:/home/mirco/kaldi-trunk/egs/timit/s5/fbank/raw_fbank_train.1.ark
ark,t:- | more
shows the numerical values of  features and there is no error

4-copy-feats
ark:/home/mirco/kaldi-trunk/egs/timit/s5/fbank/raw_fbank_train.1.ark ark:-
| apply-cmvn --utt2spk=ark:quick_test/data/train/utt2spk
ark:quick_test/mfcc/train_cmvn_speaker.ark ark:- ark:- | add-deltas --
delta-order=2 ark:- ark,t:- | more

shows the numerical values of features and there is no error

However the final step
5-check the labels, by running:
gunzip -c $your_lab_folder/ali.*.gz | $your_lab_folder//final.mdl ark:-
ark,t:- | more
where $your_lab_folder is the one you set in the config file (see
lab_folder)
gives the following error.
![untitled](https://user-images.githubusercontent.com/50566213/72730286-196f4d00-3bb7-11ea-893b-997da7946a61.png)

This final.mdl is in the kaldi folder. When running the TIMIT_MLP_mfcc_basic.cfg file using the same final.mdl and alignment files, there is no error. Could yo please help me out with this? 

I have another query regarding using multiple features. Do I have to run the TIMIT baseline with all the features? In that case, how do I concatenate/combine the alignments and models before running pytorch-kaldi?

Any help would be greatly appreciated.

**Comment by TParcollet** [comment]
Hi! For the last part of your question the answer is no, you don't need to run entirely the Kaldi baseline with all the features. You just have to create them with the make_*.sh corresponding. You just need to combine the features in the cfg following: https://github.com/mravanelli/pytorch-kaldi/blob/master/cfg/TIMIT_baselines/TIMIT_mfcc_fbank_fmllr_liGRU_best.cfg

For the first part ... it's weird. It might looks like a problem of version of something ... Have you tried to clean entirely the Kaldi TIMIT directory and run everything again from scratch?
