### ISSUE TITLE
feats_raw.scp (TIMIT_CNN_raw.conf)

### ISSUE THREAD

**Issue by dori2063** [mravanelli/pytorch-kaldi#21]
Hi!
Thanks to your help, I'm understanding how it works.

This time, I'm trying to check "TIMIT_CNN_raw.conf", inserting "feats_raw.scp" as "wav.scp"
And it did not work.
I think I don't know how to extract correct .scp for this conf.
I could not find any proper "steps/make_**".

**Comment by mravanelli** [comment]
Hi!,
to feed the system directly with the raw samples, you can take a look into the section "Speech recognition from the raw waveform with SincNet" in the documentation. There is a step that first saves the raw features into the kaldi format and then use it within pytorch-kaldi

**Comment by dori2063** [comment]
Oh, I missed it. Thank you!
