### ISSUE TITLE
Online speech recognition

### ISSUE THREAD

**Issue by victornoriega** [mravanelli/pytorch-kaldi#210]
I know this was asked in #56 and #101 and I know it is a lot of work, but I would like to know if there will be support for this in the future? Since it is not in the documentation.

**Comment by TParcollet** [comment]
Hey! Unfortunately not on Pytorch-Kaldi. It will be supported on SpeechBrain!

**Comment by victornoriega** [comment]
Thank you. When are you expecting to release a public version of SpeechBrain here on Github?

**Comment by TParcollet** [comment]
https://speechbrain.github.io/

June !

**Comment by mravanelli** [comment]
Actually,
the first version of SpeechBrain won't support online speech recognition
too. We plan to address off-line processing during all the first year and
then extend everything to the on-line case during the second year.

Best,

Mirco

**Comment by victornoriega** [comment]
Thanks, Mirco.
