### ISSUE TITLE
Problem with loading rawwav as feature, it costs too much time

### ISSUE THREAD

**Issue by liuzz13** [mravanelli/pytorch-kaldi#212]
Hi
Recently, I did some experiments with pytorch-kaldi. I find that it cost too much time to load data when using raw wav as feature, even more than training time. Do we have a batter dataloader? Or how can I reduce the time to load data?

**Comment by mravanelli** [comment]
Yes, we are aware of it. That's because the toolkit is designed to read
features in kaldi format rather than waveforms. For the speechbrain project
we are developing a totally new dataloader that can read any kind of
features (including waveforms) in a very very fast way.

Best,

Mirco

**Comment by lezasantaizi** [comment]
> Hi
> Recently, I did some experiments with pytorch-kaldi. I find that it cost too much time to load data when using raw wav as feature, even more than training time. Do we have a batter dataloader? Or how can I reduce the time to load data?

transform wav to feature
