### ISSUE TITLE
Support more models of kaldi like chain model

### ISSUE THREAD

**Issue by a550461053** [mravanelli/pytorch-kaldi#222]
Will we continue to support more models of kaldi like chain model? If not, can you give me some advices  on implementing the chain model by myself?

**Comment by TParcollet** [comment]
With the launch of SpeechBrain, Pytorch-Kaldi support will only be basic (bugs fixes). Thus we don't plan to integrate chain models (lattice free mmi etc ...) in Pytorch-Kaldi. 

I would say that this is not going to be easy with the current Pytorch-Kaldi version. You must modify so much things that it could be better for you to just re-use some of our code to develop your own Kaldi interface for chain models ... (Or wait for speech brain)

**Comment by a550461053** [comment]
> With the launch of SpeechBrain, Pytorch-Kaldi support will only be basic (bugs fixes). Thus we don't plan to integrate chain models (lattice free mmi etc ...) in Pytorch-Kaldi.
> 
> I would say that this is not going to be easy with the current Pytorch-Kaldi version. You must modify so much things that it could be better for you to just re-use some of our code to develop your own Kaldi interface for chain models ... (Or wait for SpeechBrain)

OK, Thank you. Wait for SpeechBrain :)
