### ISSUE TITLE
Loss not decreasing for Hybrid CNN+DNN and CNN+BLSTM models.

### ISSUE THREAD

**Issue by XMarusic** [mravanelli/pytorch-kaldi#223]
Hi,

I've been trying to build hybrid models on raw input signals. The raw input signals are sampled with a sampling length of 25ms * 16000Hz = 400 frame width. 

These are the two config files I've been using (with some variations). I've tried playing with the dropout, normalizations, tried making the architecture simpler but the loss isn't decreasing. 

For CNN + DNN model, the loss is pretty much constant, while for CNN + BLSTM model, the loss is sometimes increasing, sometimes decreasing and sometimes going Nan. Please have a look at the config files, 
[CNN.txt](https://github.com/mravanelli/pytorch-kaldi/files/4532111/CNN.txt)
[CNN_LSTM_raw.txt](https://github.com/mravanelli/pytorch-kaldi/files/4532112/CNN_LSTM_raw.txt)

**Comment by TParcollet** [comment]
Are you able to run the experiment that we provide for SincNet?
