### ISSUE TITLE
Librispeech: Adding lattice rescoring 

### ISSUE THREAD

**Issue by omprakashsonie** [mravanelli/pytorch-kaldi#232]
Hi Ravanelli,
Following steps are mentioned on GitHub:
You can improve the performance by adding lattice rescoring in this way (run it from the kaldi_decoding_script folder of Pytorch-Kaldi):

data_dir=/data/milatmp1/ravanelm/librispeech/s5/data/
dec_dir=/u/ravanelm/pytorch-Kaldi-new/exp/libri_fmllr/decode_test_clean_out_dnn1/
out_dir=/u/ravanelm/pytorch-kaldi-new/exp/libri_fmllr/

steps/lmrescore_const_arpa.sh  $data_dir/lang_test_{tgsmall,fglarge} \
          $data_dir/test_clean $dec_dir $out_dir/decode_test_clean_fglarge   || exit 1;

But I don't see following:

1. exp/libri_fmllr
What should be in this directory?

I see fuller in folder ~/kaldi/egs/librispeech/s5-960

2. There is no steps directory in kaldi_decoding_script folder. It has following:
~/pytorch-kaldi/kaldi_decoding_scripts$ ls
cmd.sh  conf  decode_dnn.sh  local  parse_options.sh  path.sh  split_data.sh  utils

steps/lmrescore_const_arpa.sh is in folder: ~/kaldi/egs/librispeech/s5-960

Should give full path for steps/lmrescore_const_arpa.sh ?

3.
I had run upto 13 steps of Kaldi on 960hrs data

Does it mean the following steps I ran for Librispeech were on 960hrs of data and I should compare numbers with 960hrs experiment?
   - Run the Kaldi recipe for librispeech at least until Stage 13 (included)
   - Copy exp/tri4b/trans.* files into exp/tri4b/decode_tgsmall_train_clean_100/
   - Compute the fmllr features by running the following script.
   - compute aligmenents
   - run the experiments with the following command:
     python run_exp.py cfg/Librispeech_baselines/libri_MLP_fmllr.cfg

Any help will be appreciated.

**Comment by omprakashsonie** [comment]
Hi Ravanelli,
Any help will be appreciated.

**Comment by TParcollet** [comment]
Hi,

Sorry for the delay. Did you change the path in data_dir=/data/milatmp1/ravanelm/librispeech/s5/data/
dec_dir=/u/ravanelm/pytorch-Kaldi-new/exp/libri_fmllr/decode_test_clean_out_dnn1/
out_dir=/u/ravanelm/pytorch-kaldi-new/exp/libri_fmllr/ 

Accordingly to your setup?

**Comment by omprakashsonie** [comment]
I am just starting/

1.  ill change:
data_dir=<my_dir>librispeech/s5/data/

2. The question is for
dec_dir=<my_dir>/exp/libri_fmllr/decode_test_clean_out_dnn1/

there is no 'libri-fmllr' in directory 'exp' and no further 'sub-directory 'decode_test_clean_out_dnn1'

How are these created and what is stored in it?

3. 
Will change path once I get through step 2
out_dir=/u/ravanelm/pytorch-kaldi-new/exp/libri_fmllr/

**Comment by TParcollet** [comment]
I am sorry but I don't understand where you current are. 

Did you do step one: Run the Kaldi recipe, and you are able to see all the correct dirs created on exp/ ? Such as mono, tri2, tri3 etc etc ?

**Comment by omprakashsonie** [comment]
I have completed following:
<img width="937" alt="image" src="https://user-images.githubusercontent.com/8159628/84565531-6a125d00-ad87-11ea-98ce-26c81474e532.png">

Now trying to follow these steps:
<img width="886" alt="image" src="https://user-images.githubusercontent.com/8159628/84565545-81514a80-ad87-11ea-8018-2938f945f46e.png">

**Comment by TParcollet** [comment]
So I'm pretty sure that steps/lmrescore_const_arpa.sh is called from the Kaldi directory. You can basically call it from here OR specify the full steps/lmrescore_const_arpa.sh path (Kaldi one)

**Comment by omprakashsonie** [comment]
ok, will provide full path for steps/lmrescore...

As 'libri_fmllr'  and 'decode_test_clean_out_dnn1' directories don't exist, should I create them and run lmrescore..?

**Comment by TParcollet** [comment]
No, they should be created by steps 3.

**Comment by omprakashsonie** [comment]
Thanks a lot TParcollet for your inputs.

I was looking for directory 'libri_fmllr' in pytorch-kaldi 'exp' directory.

Looks like name has changed to 'libri_MLP_fmllr'

After correcting directory:
data_dir=/home/omprakash.s/pytorch-kaldi/exp/libri_MLP_fmllr

dec_dir=/home/omprakash.s/pytorch-kaldi/exp/libri_MLP_fmllr/decode_test_clean_out_dnn1

out_dir=/home/omprakash.s/pytorch-kaldi/exp/libri_MLP_fmllr/

/home/omprakash.s/kaldi/egs/librispeech/s5-960/steps/lmrescore_const_arpa.sh  $data_dir/lang_test_{tgsmall,fglarge} $data_dir/test_clean $dec_dir $out_dir/decode_test_clean_fglarge   || exit 1;


Getting following error::
/home/omprakash.s/kaldi/egs/librispeech/s5-960/steps/lmrescore_const_arpa.sh /home/omprakash.s/pytorch-kaldi/exp/libri_MLP_fmllr/lang_test_{tgsmall,fglarge} /home/omprakash.s/pytorch-kaldi/exp/libri_MLP_fmllr/test_clean /home/omprakash.s/pytorch-kaldi/exp/libri_MLP_fmllr/decode_test_clean_out_dnn1/ /home/omprakash.s/pytorch-kaldi/exp/libri_MLP_fmllr//decode_test_clean_fglarge
Does language model rescoring of lattices (remove old LM, add new LM)
Usage: /home/omprakash.s/kaldi/egs/librispeech/s5-960/steps/lmrescore_const_arpa.sh [options] <old-lang-dir> <new-lang-dir> \
                   <data-dir> <input-decode-dir> <output-decode-dir>
options: [--cmd (run.pl|queue.pl [queue opts])]

**Comment by omprakashsonie** [comment]
Any help will be appreciated.

**Comment by TParcollet** [comment]
You are having trouble with your paths on the Kaldi side. I am sorry that I cannot help here, but you have to fix your paths. does exp/libri_MLP_fmllr/lang_test_tgsmall/G.fst exists ? or is it exp/libri_fmllr/lang_test_tgsmall/G.fst ? The best solution for you is to look at https://github.com/kaldi-asr/kaldi/blob/master/egs/wsj/s5/steps/lmrescore_const_arpa.sh and understand properly what this script requires as arguments. Then you can reorder your paths accordingly.

**Comment by omprakashsonie** [comment]
I think the issue is with step 3. May be either there is different step 3 script for lmrescore or some issue with current step 3.

It is not creating 'lang_test_tgsmall' or having file G.fst or other required files for which lmrescore_const_arpa.sh is throwing error.
