### ISSUE TITLE
How to setup parameters in "cfg/TIMIT_baselines/TIMIT_liGRU_fmllr.cfg"?

### ISSUE THREAD

**Issue by ReinholdM** [mravanelli/pytorch-kaldi#238]
I want to follow the config in `cfg/TIMIT_baselines/TIMIT_liGRU_fmllr.cfg`, but confused by the three types of features.  
 Shall I run the `run.sh` with three types of features three times and change paths like `fea_lst` and ``--utt2spk=?  
Should the `$KALDI-ROOT/egs/timit/s5/data/train/feats.scp` different across different feature types such as `$KALDI-ROOT/egs/timit/s5/data/train/feats.scp` and `$KALDI-ROOT/egs/timit/s5/data-fmllr-tri3/train/feats.scp` ?

**Comment by TParcollet** [comment]
Hi ! We added the three kind of features so you just have to swap the name in the cfg file to try with different features. Therefore, you just have to do the normal Kaldi run.sh, and then compute the Fmllr as explained in the tutorial !

**Comment by ReinholdM** [comment]
Thanks for your reply. Can I understand that I should do the `run.sh` three times for three types of features and change the name respectively in the cfg file?

**Comment by TParcollet** [comment]
in the pytorch-kaldi cfg file, you can remove the features that are not used so you don't have the error anymore if they do not exist. Then you just need to run the run.sh once, and call the command to generate the fmllr (fmllr are computed in top of traditional features).

**Comment by ReinholdM** [comment]
got it! It's just what I want to ask, the simple question. Forgive me for incompletely understanding this toolkit. Thanks again!

**Comment by TParcollet** [comment]
No problem! Happy that this toolkit can help your work. Note that SpeechBrain will come out soon (Fall-winter), and will be way better and easier.

**Comment by ReinholdM** [comment]
Hi! There still some problems when running the `cfg/TIMIT_baslines/TIMIT_liGRU_fmllr.cfg`.
I delete the `mfcc `and `fbank `fea_lst section and only change the path of `fmllr `feats.scp, as well as specify the fea_opts as follows
![image](https://user-images.githubusercontent.com/37702076/88446894-6252d780-ce60-11ea-94eb-a1ecb74ee276.png)
But error information like this happened
![image](https://user-images.githubusercontent.com/37702076/88446927-ac3bbd80-ce60-11ea-8496-cc5dd8b3f384.png)
So how can I fix it next? Thx
