### ISSUE TITLE
Train with LF-MMI in Kaldi

### ISSUE THREAD

**Issue by yangxueruivs** [mravanelli/pytorch-kaldi#24]
Does this support LF-MMI training in Kaldi, Or have you compared the results between LF-MMI in Kaldi and Pytorch?
Thank you!

**Comment by mravanelli** [comment]
Hi,
we haven't implemented MMI yet and I think it could be helpful if someone does it. In general, with the pytorch-kaldi toolkit we have seen often better results than using standard kaldi with MMi. As reported in the reference paper, we implemented several tricks that help to boost the recognition performance.
