### ISSUE TITLE
Use final_architecture1.pkl for live test

### ISSUE THREAD

**Issue by spacecd** [mravanelli/pytorch-kaldi#255]
Hi Sir, 
Thanks for the detailed README.md, I managed to finish model training  following Librispeech tutorial using libri_MLP_fmllr.cfg and got the result:
%WER 9.54 [ 5018 / 52576, 558 ins, 643 del, 3817 sub ] /pytorch-kaldi/repo/exp_torch/libri_MLP_fmllr_GPU_ c75_batch256/decode_test_clean_out_dnn1/wer_13_0.0, 

I’d like to move the trained model exp_files/final_architecture1.pkl to one of our hardware recognition system for live test.  Since our existing system loads final.mdl in Kaldi format, does anyone can give any idea for converting final_architecture1.pkl to Kaldi format?   Thanks in advance :-D

**Comment by mravanelli** [comment]
Hi,
we aren't supporting pytorch-kaldi anymore because we now haveca much
better toolkit called speechbrain. My suggestion is to switch to it.

**Comment by spacecd** [comment]
Thanks Mirco for the reply.
I’ve heard the name of SpeechBrain in the community, and will start follow it :-D

A quick question, is it possible that we convert the ASR model trained by SpeechBrain to Kaldi format?
I ask this because our existing hardware recognition system is running C optimized kaldi decoder.

**Comment by mravanelli** [comment]
Unfortunately this is not possible..

**Comment by spacecd** [comment]
Thanks Micro for your kindly help
