### ISSUE TITLE
Parallel decoding w/o reloading

### ISSUE THREAD

**Issue by PCerles** [mravanelli/pytorch-kaldi#27]
Hey, have you thought of any way to do parallel Kaldi decoding w/o reloading the fst graph
(like this class http://kaldi-asr.org/doc/decoder-wrappers_8cc_source.html called in https://github.com/kaldi-asr/kaldi/blob/master/src/nnet3bin/nnet3-latgen-faster-parallel.cc)

Seems like this parallel method will simply reload the HCLG.fst in every process, making it much slower than just loading it once and doing it serially.
https://github.com/mravanelli/pytorch-kaldi/blob/master/kaldi_decoding_scripts/decode_dnn.sh#L85

Maybe I'm misinterpreting how this works? Relatively new to Kaldi, but I'm working on integrating parallel lattice decoding w/ Torch on my own right now, and running into enough issues that I'm considering 
A) Using the new PyTorch 1.0 c++ frontend
B) Torch --> ark files --> parallel decoder. 

Are you guys looking into this problem? Happy to help if you are.

**Comment by mravanelli** [comment]
Hi,
the current version of the toolkit we directly inherits the decoding
algorithm of the kaldi timit/s5 recipe. In the config file, however, the
user can specify which decoding algorithm use. It could be great if someone
can create a new version of the decoding.sh script that is faster.

Mirco
