### ISSUE TITLE
Usage case for Kaldi

### ISSUE THREAD

**Issue by numericlee** [mravanelli/pytorch-kaldi#3]
Mirko,
Thanks for posting this. 

I have digits  decoded by LeNet5 and I want an HMM to combine the probability vector for each character position with a prior distribution of words to get the posterior distribution of the word.

How would I adapt Kaldi to do so?

**Comment by mravanelli** [comment]
Hi,
thank you for your interest in my code. Actually digit recognition is out of the scope of this repository. Also Kaldi itself is pretty biased to speech recognition, but you one can find a way the adapt it for digit recognition. It could make sense to use a more general HMM-based framework like HTK (http://htk.eng.cam.ac.uk/). It is a quite old software but works very well and it's very well documented.

Mirco
