### ISSUE TITLE
python2 or python3 ?

### ISSUE THREAD

**Issue by dahu1** [mravanelli/pytorch-kaldi#30]
Could you tell me this projuct support which python ? 
I installed python3 with torch and other libs . But, it has some error:
`python3 run_exp.py cfg/TIMIT_baselines/TIMIT_MLP_mfcc_basic.cfg
Traceback (most recent call last):
  File "run_exp.py", line 48, in <module>
    [config,name_data,name_arch]=check_cfg(cfg_file,config,cfg_file_proto)
  File "/mnt/lustre/asrdata/users/xch27/experiments/pytorch_kaldi/pytorch-kaldi/utils.py", line 501, in check_cfg
    N_out=int(output.decode().rstrip())
ValueError: invalid literal for int() with base 10: ''`
May be I should try python2 ... But matplotlib doesn't support python2.x , I feel a bit confused.

**Comment by TParcollet** [comment]
Hi could you please provide a print() of the output.decode().rstrip() right before this line ? 
pytorch-kaldi has been tested with both python 2.x and 3.x so it should work.

Thanks you !

**Comment by dahu1** [comment]
It really works!   
BUT I meet a new error ... I don't know how to describe it.  I don't know if it was caused by the change of the above code.

### $ python3 run_exp.py cfg/TIMIT_baselines/TIMIT_MLP_mfcc_basic.cfg

- Reading config file......OK!
- Chunk creation......OK!

------------------------------ Epoch 000 / 023 ------------------------------
Training TIMIT_tr chunk = 1 / 5
ERROR: training epoch 0, chunk 0 not done! File exp/TIMIT_MLP_basic/exp_files/train_TIMIT_tr_ep000_ck00.info does not exist.
See exp/TIMIT_MLP_basic/log.log  

### $ cat exp/TIMIT_MLP_basic/log.log
copy-feats scp:exp/TIMIT_MLP_basic/exp_files/train_TIMIT_tr_ep000_ck00_mfcc.lst ark:- 
apply-cmvn --utt2spk=ark:/mnt/lustre/asrdata/users/xch27/experiments/kaldi/egs/timit/s5/data/train/utt2spk ark:/mnt/lustre/asrdata/users/xch27/experiments/kaldi/egs/timit/s5/mfcc/cmvn_train.ark ark:- ark:- 
add-deltas --delta-order=2 ark:- ark:- 
LOG (copy-feats[5.5.145~1-b50a]:main():copy-feats.cc:143) Copied 739 feature matrices.
LOG (apply-cmvn[5.5.145~1-b50a]:main():apply-cmvn.cc:162) Applied cepstral mean normalization to 739 utterances, errors on 0
ali-to-pdf /mnt/lustre/asrdata/users/xch27/experiments/kaldi/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_ali/final.mdl ark:- ark:- 
LOG (ali-to-pdf[5.5.145~1-b50a]:main():ali-to-pdf.cc:68) Converted 3696 alignments to pdf sequences.
Traceback (most recent call last):
  File "run_nn.py", line 109, in <module>
    [nns,costs]=model_init(inp_out_dict,model,config,arch_dict,use_cuda,multi_gpu,to_do)
  File "/mnt/lustre/asrdata/users/xch27/experiments/pytorch_kaldi/pytorch-kaldi/utils.py", line 1442, in model_init
    net=nn_class(config[arch_dict[inp1][0]],inp_dim)
  File "/mnt/lustre/asrdata/users/xch27/experiments/pytorch_kaldi/pytorch-kaldi/neural_networks.py", line 113, in __init__
    self.wx.append(nn.Linear(current_input, self.dnn_lay[i],bias=add_bias))
  File "/mnt/lustre/asrdata/users/xch27/experiments/ENV3.6/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 46, in __init__
    self.reset_parameters()
  File "/mnt/lustre/asrdata/users/xch27/experiments/ENV3.6/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 49, in reset_parameters
    stdv = 1. / math.sqrt(self.weight.size(1))
RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

**Comment by TParcollet** [comment]
I'm pretty sure that there is a problem with the loading of N_out. This variable correspond to the number of labels, so 0 is a very bad value, and the int shouldn't be empty. Let's try to see if the problem isn't due to a previous Kaldi error. Could you please print the 'cmd' variable (two lines above the N_out=output.decode[..]) ? And then just try to run this command in a shell and post the hmm-info output ?

**Comment by dahu1** [comment]
Thank you . I make some errors in $PATH .  It is stupid
Now. it works pferfectly! 
THANK YOU .

> 
Testing TIMIT_test chunk = 1 / 1
[========================================] 100% Forwarding | (Batch 192/192))
Decoding TIMIT_test output out_dnn1
%WER 17.9 | 192 7215 | 84.4 11.7 3.9 2.3 17.9 99.5 | -0.722 | /mnt/lustre/asrdata/users/xch27/experiments/pytorch_kaldi/pytorch-kaldi/exp/TIMIT_MLP_basic/decode_TIMIT_
test_out_dnn1/score_5/ctm_39phn.filt.sys
-----
Generating output files and plots ...
OK

**Comment by TParcollet** [comment]
Great :)
