### ISSUE TITLE
Input shape issue

### ISSUE THREAD

**Issue by juansgomez87** [mravanelli/pytorch-kaldi#33]
Hello, 
Thank you for sharing your work! I've been trying to train the baseline (python3 run_exp.py cfg/TIMIT_baselines/TIMIT_MLP_mfcc_basic.cfg), but I get the an input shape error (I'm attaching the log). I already checked a previous issue about the shape, but it seems a different one. I would appreciate any help you could provide!

[log.log](https://github.com/mravanelli/pytorch-kaldi/files/2723689/log.log)

**Comment by mravanelli** [comment]
Hi,
It looks like you have done some iterations with some network dimensions,
and then you change it for some reason.
I would try to delete all the files you find in exp_files and start from
scratch.

Please, let me know if this solves the problem!

Best,

Mirco

**Comment by juansgomez87** [comment]
Thank you for your response Mirco. It solved the problem. Cheers!
