### ISSUE TITLE
Multilingual training

### ISSUE THREAD

**Issue by yonasdw** [mravanelli/pytorch-kaldi#36]
Does pytorch-kaldi support multilingual training support?

**Comment by mravanelli** [comment]
Hi,
thank you very much for the interest in this project.
What do you exactly mean with "multilingual training support?"? Of course,
you can train the speech recognizers with all the speech data you want.

Mirco

**Comment by yonasdw** [comment]
Hi Micro!
thanks for your quick reply! What I mean is training a dnn model on multiple languages (typically used to support low resourced languages). E.g, multilingual Babel nnet3 scripts provides that support. Also, you could look at https://github.com/espnet/espnet/tree/master/egs/babel/asr1

**Comment by mravanelli** [comment]
Hi,
pytorch-kaldi is designed to be as flexible as possible. It is very
natural within this framework to do useful operations like multi-task
learning or pre-training. Moreover, we tried to design the toolkit in order
to allow people to easily plug-in their acoustic models.



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
