### ISSUE TITLE
I am a little confused about the chunk?

### ISSUE THREAD

**Issue by hlthu** [mravanelli/pytorch-kaldi#37]
Does the chunk means to split the all the training dataset? if so, when I set n_chunks to 100, then every chunk has 10833 batchs:

```
------------------------------ Epoch 000 / 001 ------------------------------
Training WSJ0_train chunk = 1 / 100
[=-----------------------------------------] 3.8% Training | (Batch 411/10833)
```
When I change the n_chunks, the number of batchs of every chunk stay the same.
```
------------------------------ Epoch 000 / 001 ------------------------------
Training WSJ0_train chunk = 1 / 10
[====------------------------------------] 9.4% Training | (Batch 1021/10833)
```

So what does the n_chunks  mean?

**Comment by mravanelli** [comment]
Hi,
when you change the number of chunks make sure to change the output folder,
because if the exp_file folder is not empty by default the algorithm starts
with the previous setup.

Does it solve the issue?

Mirco

**Comment by hlthu** [comment]
I have deleted the older output_folder, but it still failed. I look into one of the generated '*ep*ck*.cfg' and find out that fea_lst is not '*ep*ck*.lst'. I will try to figure out the reasons.

```
[data_chunk]
fea = fea_name=mfcc_pitch
	fea_lst=/home/huanglu/project/wsj0_pit_ce/data/feats/tr_feats.scp
	fea_opts=
	cw_left=0
	cw_right=0
lab = lab_name=lab
	lab_folder=ata/align/tr
	lab_opts=ali-to-pdf
	lab_count_file=auto
	lab_data_folder=quick_test/data/train/
	lab_graph=exp/tri4b/graph_tgpr
```

**Comment by mravanelli** [comment]
Tomorrow I can take a look. Keep me updated!

**Comment by hlthu** [comment]
I got the reason: in 'fea = fea_name=mfcc_pitch' , the fea_name should not contain '_', which will cause issues when using regular expression in line 802 utils.py.

**Comment by mravanelli** [comment]
Thank you for pointing out this issue. I can raise an error if people try
to add special characters in some fields of the config file.



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
