### ISSUE TITLE
n_chunks > 100

### ISSUE THREAD

**Issue by curly1** [mravanelli/pytorch-kaldi#49]
Hi,
Setting the number of chunks to a number > 100 doesn't result in an error, but the model will not be trained on all of the data. compute_n_chunks in utils.py will return 99 in this case, due to "02d" formatting of the checkpoint number. So maybe you'd like to add a warning about this, or change the checkpoint number formatting.
Joanna

**Comment by mravanelli** [comment]
Hi Joanna,
thank you for your feedback. We are aware of that and we plan to fix it as
soon as possible!

**Comment by mravanelli** [comment]
We should have fix it. Now the user can specify and arbitrary number of chunks and epochs!
