### ISSUE TITLE
data_io.py doesn't work under Py3k

### ISSUE THREAD

**Issue by appleyib** [mravanelli/pytorch-kaldi#5]
Blender 2.6x comes with its own Python in Version 3.3.x, and in Py3k next() becomes \_\_next\_\_().
Better fix this if you want perfect python 3 compatibility.

Here is the error message in log.log:
File ".../pytorch-kaldi/data_io.py", line 86, in load_counts
    row = f.next().strip().strip('[]').strip()
AttributeError: '_io.TextIOWrapper' object has no attribute 'next'

I was using python 3.6.2 with Anaconda.

**Comment by mravanelli** [comment]
Hi!, thank you for pointing out this compatibility issue. Next version of the project will consider this problem!
