### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by vikashchaurasia00** [mravanelli/pytorch-kaldi#50]
I have installed all the required dependencies mentioned in the readme file. But while running the command mentioned below
python run_exp.py cfg/TIMIT_baselines/TIMIT_MLP_mfcc_basic.cfg
I am facing the issues as following
![screenshot from 2019-02-13 19-44-08](https://user-images.githubusercontent.com/25932531/52737106-8fefec00-2ff1-11e9-8901-93ca4329e204.png)

**Comment by mravanelli** [comment]
Hi!
It seems there is a problem loading the first dev chunk. Could you check if
all the paths in "TIMIT_dev" all exists?
Try to also check within dev/feats.scp in the files exists or if the folder
"timit/s5/exp/dnn4_pretrain-dbn_dnn_ali_dev" actually contains the
alignments.

Mirco

**Comment by vikashchaurasia00** [comment]
Hi @mravanelli ,
Thank You for your quick response.
Now, Issue is resolved with the help of your suggestion, Thank You Again.

**Comment by mravanelli** [comment]
You are welcome!
