### ISSUE TITLE
BLSTM

### ISSUE THREAD

**Issue by narcise** [mravanelli/pytorch-kaldi#51]
Is there any configuration for Bidirectional LSTM in Pytorch-KALDI? What is your best suggestion to train my data with BLSTM?

**Comment by mravanelli** [comment]
Sure,
if you take a look into config file
"cfg/TIMIT_baselines/TIMIT_LSTM_fmllr.cfg you can see that the lstm
architecture has a flag called "lstm_bidir=True". When true, you have a
bidirectional rnn, when false a unidirectional one. Note that a similar
flag is available for the other rnn models that we have implemented such as
the GRU and light GRU models. I suggest to derive your own application
starting from these simple examples (see librispeech or timit cfg files).

Mirco

**Comment by narcise** [comment]
I appreciate your help.
