### ISSUE TITLE
TIMIT_LSTM_fbank.cfg

### ISSUE THREAD

**Issue by narcise** [mravanelli/pytorch-kaldi#53]
I am using the TIMIT_LSTM_fbank.cfg for my own dataset which has been completely experimented with the Timit-Kaldi recipe. 
when I run the 
python run_exp.py cfg/TIMIT_baselines/TIMIT_LSTM_fbank.cfg

I receive this error in my exp/EMA_MAE_LSTM_fbank/log.log:

Traceback (most recent call last):
  File "run_nn.py", line 206, in <module>
    outs_dict=forward_model(fea_dict,lab_dict,arch_dict,model,nns,costs,inp,inp_out_dict,max_len,batch_size,to_do,forward_outs)
  File "*/pytorch-kaldi/utils.py", line 1658, in forward_model
    err = torch.mean((pred!=lab_dnn).float())
RuntimeError: CUDA error: device-side assert triggered
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [3,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [4,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [11,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [12,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [19,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [20,0,0] Assertion `t >= 0 && t < n_classes` failed.
Could you help me with this please?

**Comment by mravanelli** [comment]
It looks like the number of outputs is not detected correctly. The number
of DNN outputs (e.g., N_out_lab_cd and N_out_lab_mono) is automatically
computed by running the "hmm-info" kaldi command on the model that is found
in "lab_dir/final.mdl". Could you post your complete cfg file to understand
better what is going on?

**Comment by narcise** [comment]
`[cfg_proto]
cfg_proto = proto/global.proto
cfg_proto_chunk = proto/global_chunk.proto

[exp]
cmd = 
run_nn_script = run_nn.py
out_folder = exp/EMA_MAE_LSTM_fbank
seed = 2234
use_cuda = True
multi_gpu = False
save_gpumem = False
n_epochs_tr = 24

[dataset1]
data_name = EMA_MAE_tr
fea = fea_name=mfcc
	fea_lst=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/data/train/feats_mfcc.scp
	fea_opts=apply-cmvn --utt2spk=ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/data/train/utt2spk  ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/mfcc/cmvn_train.ark.ark ark:- ark:- | add-deltas --delta-order=2 ark:- ark:- |
	cw_left=0
	cw_right=0
	
	fea_name=fbank
	fea_lst=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/data/train/feats_fbank.scp
	fea_opts=apply-cmvn --utt2spk=ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/data/train/utt2spk  ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/fbank/cmvn_train.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
	cw_left=0
	cw_right=0
	
	fea_name=fmllr
	fea_lst=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/data/train/feats_fmllr.scp
	fea_opts=apply-cmvn --utt2spk=ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/data/train/utt2spk  ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/data-fmllr-tri3/train/cmvn_fmllr.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
	cw_left=0
	cw_right=0
lab = lab_name=lab_cd
	lab_folder=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/exp/dnn4_pretrain-dbn_dnn_ali
	lab_opts=ali-to-pdf
	lab_count_file=auto
	lab_data_folder=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/data/train/
	lab_graph=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/exp/tri3/graph
	
	lab_name=lab_mono
	lab_folder=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/exp/dnn4_pretrain-dbn_dnn_ali
	lab_opts=ali-to-phones --per-frame=true
	lab_count_file=none
	lab_data_folder=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/data/train/
	lab_graph=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/exp/tri3/graph
n_chunks = 5

[dataset2]
data_name = EMA_MAE_dev
fea = fea_name=mfcc
	fea_lst=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/data/dev/feats_mfcc.scp
	fea_opts=apply-cmvn --utt2spk=ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/data/dev/utt2spk  ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/mfcc/cmvn_dev.ark ark:- ark:- | add-deltas --delta-order=2 ark:- ark:- |
	cw_left=0
	cw_right=0
	
	fea_name=fbank
	fea_lst=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/data/dev/feats_fbank.scp
	fea_opts=apply-cmvn --utt2spk=ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/data/dev/utt2spk  ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/fbank/cmvn_dev.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
	cw_left=0
	cw_right=0
	
	fea_name=fmllr
	fea_lst=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/data/dev/feats_fmllr.scp
	fea_opts=apply-cmvn --utt2spk=ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/data/dev/utt2spk  ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/data-fmllr-tri3/dev/cmvn_fmllr.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
	cw_left=0
	cw_right=0
lab = lab_name=lab_cd
	lab_folder=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/exp/dnn4_pretrain-dbn_dnn_ali_dev
	lab_opts=ali-to-pdf
	lab_count_file=auto
	lab_data_folder=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/data/dev/
	lab_graph=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/exp/tri3/graph
	
	lab_name=lab_mono
	lab_folder=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/exp/dnn4_pretrain-dbn_dnn_ali_dev
	lab_opts=ali-to-phones --per-frame=true
	lab_count_file=none
	lab_data_folder=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/data/dev/
	lab_graph=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/exp/tri3/graph
n_chunks = 1

[dataset3]
data_name = EMA_MAE_test
fea = fea_name=mfcc
	fea_lst=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/data/test/feats_mfcc.scp
	fea_opts=apply-cmvn --utt2spk=ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/data/test/utt2spk  ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/mfcc/cmvn_test.ark ark:- ark:- | add-deltas --delta-order=2 ark:- ark:- |
	cw_left=0
	cw_right=0
	
	fea_name=fbank
	fea_lst=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/data/test/feats_fbank.scp
	fea_opts=apply-cmvn --utt2spk=ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/data/test/utt2spk  ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/fbank/cmvn_test.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
	cw_left=0
	cw_right=0
	
	fea_name=fmllr
	fea_lst=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/data/test/feats_fmllr.scp
	fea_opts=apply-cmvn --utt2spk=ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/data/test/utt2spk  ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/data-fmllr-tri3/test/cmvn_fmllr.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
	cw_left=0
	cw_right=0
lab = lab_name=lab_cd
	lab_folder=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/exp/dnn4_pretrain-dbn_dnn_ali_test
	lab_opts=ali-to-pdf
	lab_count_file=auto
	lab_data_folder=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/data/test/
	lab_graph=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/exp/tri3/graph
	
	lab_name=lab_mono
	lab_folder=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/exp/dnn4_pretrain-dbn_dnn_ali_test
	lab_opts=ali-to-phones --per-frame=true
	lab_count_file=none
	lab_data_folder=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/data/test/
	lab_graph=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/exp/tri3/graph
n_chunks = 1

[data_use]
train_with = EMA_MAE_tr
valid_with = EMA_MAE_dev
forward_with = EMA_MAE_test

[batches]
batch_size_train = 8
max_seq_length_train = 1000
increase_seq_length_train = True
start_seq_len_train = 100
multply_factor_seq_len_train = 2
batch_size_valid = 8
max_seq_length_valid = 1000

[architecture1]
arch_name = LSTM_cudnn_layers
arch_proto = proto/LSTM.proto
arch_library = neural_networks
arch_class = LSTM
arch_pretrain_file = none
arch_freeze = False
arch_seq_model = True
lstm_lay = 550,550,550,550
lstm_drop = 0.2,0.2,0.2,0.2
lstm_use_laynorm_inp = False
lstm_use_batchnorm_inp = False
lstm_use_laynorm = False,False,False,False
lstm_use_batchnorm = True,True,True,True
lstm_bidir = True
lstm_act = tanh,tanh,tanh,tanh
lstm_orthinit = True
arch_lr = 0.0016
arch_halving_factor = 0.5
arch_improvement_threshold = 0.001
arch_opt = rmsprop
opt_momentum = 0.0
opt_alpha = 0.95
opt_eps = 1e-8
opt_centered = False
opt_weight_decay = 0.0

[architecture2]
arch_name = MLP_layers
arch_proto = proto/MLP.proto
arch_library = neural_networks
arch_class = MLP
arch_pretrain_file = none
arch_freeze = False
arch_seq_model = False
dnn_lay = N_out_lab_cd
dnn_drop = 0.0
dnn_use_laynorm_inp = False
dnn_use_batchnorm_inp = False
dnn_use_batchnorm = False
dnn_use_laynorm = False
dnn_act = softmax
arch_lr = 0.0016
arch_halving_factor = 0.5
arch_improvement_threshold = 0.001
arch_opt = rmsprop
opt_momentum = 0.0
opt_alpha = 0.95
opt_eps = 1e-8
opt_centered = False
opt_weight_decay = 0.0

[architecture3]
arch_name = MLP_layers2
arch_proto = proto/MLP.proto
arch_library = neural_networks
arch_class = MLP
arch_pretrain_file = none
arch_freeze = False
arch_seq_model = False
dnn_lay = 48
dnn_drop = 0.0
dnn_use_laynorm_inp = False
dnn_use_batchnorm_inp = False
dnn_use_batchnorm = False
dnn_use_laynorm = False
dnn_act = softmax
arch_lr = 0.0004
arch_halving_factor = 0.5
arch_improvement_threshold = 0.001
arch_opt = rmsprop
opt_momentum = 0.0
opt_alpha = 0.95
opt_eps = 1e-8
opt_centered = False
opt_weight_decay = 0.0

[model]
model_proto = proto/model.proto
model = out_dnn1=compute(LSTM_cudnn_layers,fbank)
	out_dnn2=compute(MLP_layers,out_dnn1)
	out_dnn3=compute(MLP_layers2,out_dnn1)
	loss_mono=cost_nll(out_dnn3,lab_mono)
	loss_mono_w=mult_constant(loss_mono,1.0)
	loss_cd=cost_nll(out_dnn2,lab_cd)
	loss_final=sum(loss_cd,loss_mono_w)
	err_final=cost_err(out_dnn2,lab_cd)

[forward]
forward_out = out_dnn2
normalize_posteriors = True
normalize_with_counts_from = lab_cd
save_out_file = False
require_decoding = True

[decoding]
decoding_script_folder = kaldi_decoding_scripts/
decoding_script = decode_dnn.sh
decoding_proto = proto/decoding.proto
min_active = 200
max_active = 7000
max_mem = 50000000
beam = 13.0
latbeam = 8.0
acwt = 0.2
max_arcs = -1
skip_scoring = false
scoring_script = local/score.sh
scoring_opts = "--min-lmwt 1 --max-lmwt 10"
norm_vars = False
`

**Comment by mravanelli** [comment]
Ok,
you just have to replace dnn_lay=48 with dnn_lay = N_out_lab_mono
48 is the number of monophones for timit and it is not valid in general. We
recently added the reserved keyword "N_out_lab_mono" to automatically infer
this value from the right model.
Please, let me know if this solves the issue.

Mirco

**Comment by narcise** [comment]
Now I have this error:

copy-feats scp:exp/EMA_MAE_LSTM_fbank/exp_files/train_EMA_MAE_tr_ep000_ck00_fbank.lst ark:- 
apply-cmvn --utt2spk=ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/data/train/utt2spk ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/fbank/cmvn_train.ark ark:- ark:- 
add-deltas --delta-order=0 ark:- ark:- 
LOG (copy-feats[5.5.193~1-05d9a]:main():copy-feats.cc:143) Copied 4213 feature matrices.
LOG (apply-cmvn[5.5.193~1-05d9a]:main():apply-cmvn.cc:162) Applied cepstral mean normalization to 4213 utterances, errors on 0
ali-to-phones --per-frame=true /audio/kaldi/kaldi/egs/ORG_EMA_MAE/exp/dnn4_pretrain-dbn_dnn_ali/final.mdl ark:- ark:- 
LOG (ali-to-phones[5.5.193~1-05d9a]:main():ali-to-phones.cc:134) Done 21066 utterances.
copy-feats scp:exp/EMA_MAE_LSTM_fbank/exp_files/train_EMA_MAE_tr_ep000_ck00_fbank.lst ark:- 
apply-cmvn --utt2spk=ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/data/train/utt2spk ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/fbank/cmvn_train.ark ark:- ark:- 
add-deltas --delta-order=0 ark:- ark:- 
LOG (copy-feats[5.5.193~1-05d9a]:main():copy-feats.cc:143) Copied 4213 feature matrices.
LOG (apply-cmvn[5.5.193~1-05d9a]:main():apply-cmvn.cc:162) Applied cepstral mean normalization to 4213 utterances, errors on 0
ali-to-pdf /audio/kaldi/kaldi/egs/ORG_EMA_MAE/exp/dnn4_pretrain-dbn_dnn_ali/final.mdl ark:- ark:- 
LOG (ali-to-pdf[5.5.193~1-05d9a]:main():ali-to-pdf.cc:68) Converted 21066 alignments to pdf sequences.
THCudaCheck FAIL file=/pytorch/aten/src/THC/generic/THCTensorMath.cu line=14 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "run_nn.py", line 212, in <module>
    outs_dict['loss_final'].backward()
  File "/usr/local/lib/python3.7/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.7/site-packages/torch/autograd/__init__.py", line 84, in backward
    grad_tensors = _make_grads(tensors, grad_tensors)
  File "/usr/local/lib/python3.7/site-packages/torch/autograd/__init__.py", line 29, in _make_grads
    new_grads.append(torch.ones_like(out))
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/generic/THCTensorMath.cu:14
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [3,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [4,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [11,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [12,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [19,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [20,0,0] Assertion `t >= 0 && t < n_classes` failed.

**Comment by mravanelli** [comment]
Which version of pytorch are you using? Are you able to replicate our TIMIT
results?

**Comment by narcise** [comment]
Yes, I run that successfully for the TIMIT_MLP_mfcc_basic.cfg

**Comment by narcise** [comment]
$ python -c "import torch; print(torch.__version__)"
1.0.0

**Comment by mravanelli** [comment]
The error seems still to suggest and error in the output dimension. Let's
try to isolate it. What happens if you temporary disable the monophone
regularization? You can do it by replacing the previous [model] section
with this one:

[model]
model_proto = proto/model.proto
model = out_dnn1=compute(liGRU_layers,fmllr)
out_dnn2=compute(MLP_layers,out_dnn1)
loss_final=cost_nll(out_dnn2,lab_cd)
err_final=cost_err(out_dnn2,lab_cd)

Do you have the same error or the training starts this time?

Mirco

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by narcise** [comment]
It messaged:
ERROR: the output "out_dnn2" in the section "forward_out" is not defined in section model)

**Comment by mravanelli** [comment]
Sorry, in your case should be:

[model]
model_proto = proto/model.proto
model = out_dnn1=compute(LSTM_cudnn_layers,fbank)
out_dnn2=compute(MLP_layers,out_dnn1)
loss_final=cost_nll(out_dnn2,lab_cd)
err_final=cost_err(out_dnn2,lab_cd)

I would also ask you if you can post the config file that you find in
output_folder/conf.cfg. In this config file we expanded the output
dimension and I would like to make sure that this is done correctly. Last,
when is the last time you have updated pytorch-kaldi?

**Comment by narcise** [comment]
The error would be :
ERROR: the architecture "liGRU_layers" is not in the architecture lists of the config file (possible architectures are ['LSTM_cudnn_layers', 'MLP_layers', 'MLP_layers2'])

**Comment by mravanelli** [comment]
Yes, in the model section I sent you I replaced liGRU_layers with
LSTM_cudnn_layers..

**Comment by mravanelli** [comment]
In summary I would suggest to do the following:
1- Update your version of PyTorch-Kaldi with the last version available on
gitthub. Once done that, try do run again the experiment. Remember to
change the line "dnn_lay = 48" of [architecture3] with "dnn_lay =
N_out_lab_mono".
2- Post here the config file that you find
in exp/EMA_MAE_LSTM_fbank/conf.cfg. This is the version of the config file
where we expanded the output dimensionalities. It is important to check if
there is something weird here.
3. Type "hmm-info
/audio/kaldi/kaldi/egs/ORG_EMA_MAE/exp/dnn4_pretrain-dbn_dnn_ali/final.mdl"
and post here the output. This command shows the number of
context-dependent phone states (i.e., the output of [architecture2]) and
the number of monophones (i.e., the output of [architecture3]). It is
important to check that the dimensionalities observed with hmm-info are the
same that appears in  exp/EMA_MAE_LSTM_fbank/conf.cfg.
4. Try to disable (for the moment) the monophone regularization. Do to it
replace the [model] sections with exactly the following lines:
[model]
model_proto = proto/model.proto
model = out_dnn1=compute(LSTM_cudnn_layers,fbank)
out_dnn2=compute(MLP_layers,out_dnn1)
loss_final=cost_nll(out_dnn2,lab_cd)
err_final=cost_err(out_dnn2,lab_cd)
and check if the training is started now.

Please, keep me updated!

Mirco

**Comment by narcise** [comment]
Thank you very much Micro, my data is larger than Timit and it is still running for model 
[model]
 model_proto = proto/model.proto
 model = out_dnn1=compute(LSTM_cudnn_layers,fbank) 
out_dnn2=compute(MLP_layers,out_dnn1)
 loss_final=cost_nll(out_dnn2,lab_cd) 
err_final=cost_err(out_dnn2,lab_cd)
I will post the in exp/EMA_MAE_LSTM_fbank/conf.cfg as soon as it finished.
my current Epoch is:
------------------------------ Epoch 011 / 023 ------------------------------

Narjes

**Comment by mravanelli** [comment]
Ok, so my guess is that you don't have an updated version of pytorch-kaldi
and the system wasn't able to recognize the new keyword "N_out_lab_mono".

Mirco

**Comment by narcise** [comment]
Thanks. I've tried it with the newer version and apparently it is running now.

**Comment by mravanelli** [comment]
Great!
