### ISSUE TITLE
online speech recognition

### ISSUE THREAD

**Issue by Johe-cqu** [mravanelli/pytorch-kaldi#56]
Hi,I have completed the training of the acoustic model. How can I use it for online speech recognition?look forward to your kind advice.

**Comment by Rpersie** [comment]
The trained model is offline so it can not directly be used for online  speech recognition.  it requires the models to be trained with online CMN or something like that. Then use the kaldi-online decoder.  You can find some online issues on kaldi 
https://github.com/kaldi-asr/kaldi/issues/2801

**Comment by mravanelli** [comment]
The current version natively supports off-line speech recognition only. As
outlined by @Rpersie working on on-line ASR requires different
normalization and decoding strategies. We plan to support on-line ASR in
one of the future version of the toolkit.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Johe-cqu** [comment]
thank you! Looking forward to your update！

**Comment by Johe-cqu** [comment]
> The trained model is offline so it can not directly be used for online speech recognition. it requires the models to be trained with online CMN or something like that. Then use the kaldi-online decoder. You can find some online issues on kaldi
> [kaldi-asr/kaldi#2801](https://github.com/kaldi-asr/kaldi/issues/2801)
thanks

**Comment by Johe-cqu** [comment]
@Rpersie thank you!

**Comment by Johe-cqu** [comment]
@mravanelli @Rpersie  By the way, Why on-line ASR requires different normalization and decoding strategies? It requires faster decoding speed？

**Comment by Rpersie** [comment]
As the offline cmvn is the mean and var of all frames，in the online mode you can not get all the frames. If you just do the online-cmvn, this will bring the mismatch between the training and test. As for decoding, the feats are loaded segments by segments in the online mode. So we should memory the wfst state of the previous segments. When the next segment is loaded, we can follow the wfst token states of previous. So the usual decoder can not be used and need online decoder.

**Comment by mravanelli** [comment]
Yes, as outlined by @Rpersie the systems are different. In online ASR we
start the decoding while recording the signal itself and we thus don't have
access to the future.
We will deal with it the the future!
