### ISSUE TITLE
ERROR: hmm-info command doesn't exist. Make sure your .bashrc contains the Kaldi paths and correctly exports it.

### ISSUE THREAD

**Issue by wentaoxandry** [mravanelli/pytorch-kaldi#57]
Hi, I'm running the run_exp.py, but I have got an error:
ERROR: hmm-info command doesn't exist. Make sure your .bashrc contains the Kaldi paths and correctly exports it.

But I have already make kaldi path in bashrc and try run hmm-info in bash, and I got this info
~$ hmm-info
hmm-info 

Write to standard output various properties of HMM-based transition model
Usage:  hmm-info [options] <model-in>
e.g.:
 hmm-info trans.mdl

Standard options:
  --config                    : Configuration file to read (this option may be repeated) (string, default = "")
  --help                      : Print out usage message (bool, default = false)
  --print-args                : Print the command line arguments (to stderr) (bool, default = true)
  --verbose                   : Verbose level (higher->more logging) (int, default = 0)
I'm trying figure out what is the problem but I can't find out, can you please help me? Thanks.
in run_shell(cmd,log_file): my cmd is 'hmm-info /media/wentao/wentaodisk/pytorch_kaldi/kaldi_prepare/exp/tri4a_pt/final.mdl | awk \\'/pdfs/{print $4}\\''. 
But after p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True) and (output, err) = p.communicate() the output=b'' and err=b'/bin/sh: 1: hmm-info: not found\n'

**Comment by TParcollet** [comment]
Could you please try to call this cmd outside of the subprocess call ? Just before it, to see if the PATH are missing only when calling inside of a subprocess.

**Comment by wentaoxandry** [comment]
Thank you for your answer, do you mean call the cmd in bash? I have try it and got the results like this 
~$ hmm-info /media/wentao/wentaodisk/pytorch_kaldi/kaldi_prepare/exp/tri4a_pt/final.mdl | awk '/pdfs/{print $4}'
hmm-info /media/wentao/wentaodisk/pytorch_kaldi/kaldi_prepare/exp/tri4a_pt/final.mdl 
3824

**Comment by TParcollet** [comment]
If I understand well, when you call cmd inside the .py file just before run_cmd() it is also not working ?

**Comment by wentaoxandry** [comment]
No, It still not working

**Comment by wentaoxandry** [comment]
I have tried use os.environ["PATH"] manually set the path, and now it work, before that PATH includes no kaldi dir
