### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (446,1,1100) (3440,) 

### ISSUE THREAD

**Issue by Johe-cqu** [mravanelli/pytorch-kaldi#60]
**_Hi, when I tested thchs30_test chunk,  an error has occurred._** 

**_The details show as follows:_**

```
 Testing thchs30_test chunk = 1 / 10
Traceback (most recent call last):
  File "run_exp.py", line 330, in <module>
[data_name,data_set,data_end_index,fea_dict,lab_dict,arch_dict]=run_nn(data_name,data_set,data_end_index,fea_dict,lab_dict,arch_dict,config_chunk_file,processed_first,next_config_file)
  File "/home/server/pytorch-kaldi-thchs30/core.py", line 233, in run_nn
    out_save=out_save-np.log(counts/np.sum(counts))             
ValueError: operands could not be broadcast together with shapes (446,1,1100) (3440,) 
```

**_Many warnings appear during the training process._**

` OMP: Warning #190: Forking a process while a parallel region is active is potentially unsafe.`

**_What caused this error?_**
**_BTW, I guess it may related to the value of  n_chunks._**

**Comment by TParcollet** [comment]
Could you please post your cfg file ?

Thanks you.

**Comment by Johe-cqu** [comment]
[cfg_proto]
cfg_proto = proto/global.proto
cfg_proto_chunk = proto/global_chunk.proto

[exp]
cmd = 
run_nn_script = run_nn
out_folder = exp/thchs30_GRU_mfcc
seed = 1234
use_cuda = True
multi_gpu = False
save_gpumem = False
n_epochs_tr = 2
production = False

[dataset1]
data_name = thchs30_tr
fea = fea_name=mfcc
	fea_lst=/home/server/kaldi/egs/thchs30/s5/data/mfcc/train/feats.scp
	fea_opts=apply-cmvn --utt2spk=ark:/home/server/kaldi/egs/thchs30/s5/data/mfcc/train/utt2spk  ark:/home/server/kaldi/egs/thchs30/s5/mfcc/train/cmvn_train.ark ark:- ark:- | add-deltas --delta-order=2 ark:- ark:- |
	cw_left=5
	cw_right=5
lab = lab_name=lab_cd
	lab_folder=/home/server/kaldi/egs/thchs30/s5/exp/tri4b_ali/
	lab_opts=ali-to-pdf
	lab_count_file=auto
	lab_data_folder=/home/server/kaldi/egs/thchs30/s5/data/mfcc/train/
	lab_graph=/home/server/kaldi/egs/thchs30/s5/exp/tri4b/graph_word/
n_chunks = 80

[dataset2]
data_name = thchs30_dev
fea = fea_name=mfcc
	fea_lst=/home/server/kaldi/egs/thchs30/s5/data/mfcc/dev/feats.scp
	fea_opts=apply-cmvn --utt2spk=ark:/home/server/kaldi/egs/thchs30/s5/data/mfcc/dev/utt2spk  ark:/home/server/kaldi/egs/thchs30/s5/mfcc/dev/cmvn_dev.ark ark:- ark:- | add-deltas --delta-order=2 ark:- ark:- |
	cw_left=5
	cw_right=5
lab = lab_name=lab_cd
	lab_folder=/home/server/kaldi/egs/thchs30/s5/exp/tri4b_ali_dev/
	lab_opts=ali-to-pdf
	lab_count_file=auto
	lab_data_folder=/home/server/kaldi/egs/thchs30/s5/data/mfcc/dev/
	lab_graph=/home/server/kaldi/egs/thchs30/s5/exp/tri4b/graph_word/
n_chunks = 20

[dataset3]
data_name = thchs30_test
fea = fea_name=mfcc
	fea_lst=/home/server/kaldi/egs/thchs30/s5/data/mfcc/test/feats.scp
	fea_opts=apply-cmvn --utt2spk=ark:/home/server/kaldi/egs/thchs30/s5/data/mfcc/test/utt2spk  ark:/home/server/kaldi/egs/thchs30/s5/mfcc/test/cmvn_test.ark ark:- ark:- | add-deltas --delta-order=2 ark:- ark:- |
	cw_left=5
	cw_right=5
lab = lab_name=lab_cd
	lab_folder=/home/server/kaldi/egs/thchs30/s5/exp/tri4b_ali_test_phone/
	lab_opts=ali-to-pdf
	lab_count_file=auto
	lab_data_folder=/home/server/kaldi/egs/thchs30/s5/data/mfcc/test/
	lab_graph=/home/server/kaldi/egs/thchs30/s5/exp/tri4b/graph_word/
n_chunks = 10

[data_use]
train_with = thchs30_tr
valid_with = thchs30_dev
forward_with = thchs30_test

[batches]
batch_size_train = 16
max_seq_length_train = 500
increase_seq_length_train = True
start_seq_len_train = 100
multply_factor_seq_len_train = 2
batch_size_valid = 8
max_seq_length_valid = 1000

[architecture1]
arch_name = GRU_layers
arch_proto = proto/GRU.proto
arch_library = neural_networks
arch_class = GRU
arch_pretrain_file = none
arch_freeze = False
arch_seq_model = True
gru_lay = 550,550,550,550,550
gru_drop = 0.2,0.2,0.2,0.2,0.2
gru_use_laynorm_inp = False
gru_use_batchnorm_inp = False
gru_use_laynorm = False,False,False,False,False
gru_use_batchnorm = True,True,True,True,True
gru_bidir = True
gru_act = tanh,tanh,tanh
gru_orthinit = True
arch_lr = 0.0004
arch_halving_factor = 0.5
arch_improvement_threshold = 0.001
arch_opt = rmsprop
opt_momentum = 0.0
opt_alpha = 0.95
opt_eps = 1e-8
opt_centered = False
opt_weight_decay = 0.0

[architecture2]
arch_name = MLP_layers
arch_proto = proto/MLP.proto
arch_library = neural_networks
arch_class = MLP
arch_pretrain_file = none
arch_freeze = False
arch_seq_model = False
dnn_lay = 3440
dnn_drop = 0.0
dnn_use_laynorm_inp = False
dnn_use_batchnorm_inp = False
dnn_use_batchnorm = False
dnn_use_laynorm = False
dnn_act = softmax
arch_lr = 0.0004
arch_halving_factor = 0.5
arch_improvement_threshold = 0.001
arch_opt = rmsprop
opt_momentum = 0.0
opt_alpha = 0.95
opt_eps = 1e-8
opt_centered = False
opt_weight_decay = 0.0

[model]
model_proto = proto/model.proto
model = out_dnn1=compute(GRU_layers,mfcc)
	out_dnn2=compute(MLP_layers,out_dnn1)
	loss_final=cost_nll(out_dnn2,lab_cd)
	err_final=cost_err(out_dnn2,lab_cd)

[forward]
forward_out = out_dnn1
normalize_posteriors = True
normalize_with_counts_from = exp/thchs30_GRU_mfcc/exp_files/forward_out_dnn1_lab_cd.count
save_out_file = True
require_decoding = True

[decoding]
decoding_script_folder = kaldi_decoding_scripts/
decoding_script = decode_dnn.sh
decoding_proto = proto/decoding.proto
min_active = 200
max_active = 7000
max_mem = 50000000
beam = 20.0
latbeam = 8.0
acwt = 0.2
max_arcs = -1
skip_scoring = false
scoring_script = local/score.sh
scoring_opts = "--min-lmwt 4 --max-lmwt 23"
norm_vars = False

**Comment by Johe-cqu** [comment]
**_I lowered the value of n_chunks. it is being retrained now,but there are no warnings yet._**

**Comment by TParcollet** [comment]
Warnings are due to the parallel pre-loading of chunks, they are not the problem here. @mravanelli Can you take a look at this issue ? Seems to be a problem with the counts ?

**Comment by Johe-cqu** [comment]
ohoh,thank you! @TParcollet

**Comment by Johe-cqu** [comment]
I reduced the value of n_chunks and the number of layers in the net. But the error still appears.

**Comment by mravanelli** [comment]
It seems a mismatch between the declared number of softmax outputs and the
actual number of output detected  in the count file. Let me take a closer
look later!

**Comment by mravanelli** [comment]
I saw you set "dnn_lay = 3440" in the [architecture2]. How do you selected
this number?
In pytorch-kaldi you can use "dnn_lay = N_out_lab_cd" to automatically
detected the number of outputs. Could you try to type the following command
in a bash shell?
"hmm-info
/home/server/kaldi/egs/thchs30/s5/exp/tri4b_ali_test_phone/final.mdl".
Please post here the output. My feeling is that 3440 is the the actual
number of outputs.

There are also other stuff that looks a bit weird (but are not the cause of
this error):

1- n_epochs_tr = 2 => this might be good for a first test, but you need to
have much more epochs for a full training

2. n_chunks = 80 => this seems too high. If you have 30 hours, you can
select  n_chunks = 30. You can also drastically reduce the number of chunks
for dev and test as well (e.g., n_chunks=4 n_chunks=2)


Mirco

**Comment by Johe-cqu** [comment]
i remember  i copy this cfg txt from  pytorch-kaldi/exp/…/cf.cfg. So the  N_out_lab_cd was replaced by 3340. 
i will check it tomorrow morning. 
thank you！

**Comment by mravanelli** [comment]
Ok,
it seems that the count file contains only 1100 occurrences. This number
should be the same as the number of output.

Mirco

**Comment by Johe-cqu** [comment]
```
hmm-info /home/server/kaldi/egs/thchs30/s5/exp/tri4b_ali_test_phone/final.mdl 
number of phones 218
number of pdfs 3440
number of transition-ids 7206
number of transition-states 3599
```
_**Before this test, i built a MLP model successfully, the number of output is also 3440.**_ 

_**So count file must be error. What is the use of count file?**_

**Comment by Johe-cqu** [comment]
```
[forward]
forward_out = out_dnn1
normalize_posteriors = True
normalize_with_counts_from = exp/thchs30_GRU_mfcc/exp_files/forward_out_dnn1_lab_cd.count
save_out_file = True
require_decoding = True
```
_**this cfg code is error, I should set**_ `forward_out = out_dnn2` . 
Thank you @mravanelli .

**Comment by mravanelli** [comment]
oh yes, this is the error!
Please, let me know if everything is ok now...

Best,

Mirco

**Comment by Johe-cqu** [comment]
It works well!
BTW,if you want to a thchs30 tutorial, I can give you some help. There are some differences in the scoring.

**Comment by mravanelli** [comment]
Sure! that would be great! We can write in [extra] a section called
"Tutorial on thchs30" where you can highlight all the steps needed to
replicate your results. Feel free to modify the ReadME file with that and
ask for a pull request...

Mirco
