### ISSUE TITLE
Different set of Features

### ISSUE THREAD

**Issue by narcise** [mravanelli/pytorch-kaldi#63]
I am use the BLSTM with deploying the Timit_LSTM_mfcc.cfg. However, I am not using mfccs. I have extracted different set of features and I have computed delta and delta delta and also fmllr for this new data stream. When I run the python run_exp.py cfg/TIMIT_baselines/TIMIT_LSTM_mfcc.cfg for my configuration I get the following error:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/pytorch-kaldi/data_io.py", line 207, in read_lab_fea
    [data_name_fea,data_set_fea,data_end_index_fea]=load_chunk(fea_scp,fea_opts,lab_folder,lab_opts,cw_left,cw_right,max_seq_length, output_folder, fea_only)
  File "/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/pytorch-kaldi/data_io.py", line 123, in load_chunk
    [data_name,data_set,data_lab,end_index]=load_dataset(fea_scp,fea_opts,lab_folder,lab_opts,left,right, max_sequence_length, output_folder, fea_only)
  File "/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/pytorch-kaldi/data_io.py", line 77, in load_dataset
    fea_conc,lab_conc = zip(*fea_sorted)
ValueError: not enough values to unpack (expected 2, got 0)

Traceback (most recent call last):
  File "run_exp.py", line 195, in <module>
    [data_name,data_set,data_end_index,fea_dict,lab_dict,arch_dict]=run_nn(data_name,data_set,data_end_index,fea_dict,lab_dict,arch_dict,config_chunk_file,processed_first,next_config_file)
  File "/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/pytorch-kaldi/core.py", line 81, in run_nn
    data_name=shared_list[0]
IndexError: list index out of range

**(I have deleted the fbank section from config file since I am not using it and instead of mfcc I am using articulatory features. My 'art' features are in ark format so they look like mfcc).**
cfg:
[cfg_proto]
cfg_proto = proto/global.proto
cfg_proto_chunk = proto/global_chunk.proto

[exp]
cmd = 
run_nn_script = run_nn
out_folder = exp/EMA_MAE_LSTM_mfcc
seed = 2234
use_cuda = True
multi_gpu = False
save_gpumem = False
n_epochs_tr = 24

[dataset1]
data_name = EMA_MAE_tr
fea = fea_name=art
	fea_lst=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/data/train/feats_art.scp
	fea_opts=apply-cmvn --utt2spk=ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/data/train/utt2spk  ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/art/train_cmvn_speaker.ark ark:- ark:- | add-deltas --delta-order=2 ark:- ark:- |
	cw_left=0
	cw_right=0
	
	fea_name=fmllr
	fea_lst=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/data/train/feats_fmllr.scp
	fea_opts=apply-cmvn --utt2spk=ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/data/train/utt2spk  ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/data-fmllr-tri3/train/train_cmvn.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
	cw_left=0
	cw_right=0
lab = lab_name=lab_cd
	lab_folder=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/exp/dnn4_pretrain-dbn_dnn_ali
	lab_opts=ali-to-pdf
	lab_count_file=auto
	lab_data_folder=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/data/train/
	lab_graph=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/exp/tri3/graph
	
	lab_name=lab_mono
	lab_folder=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/exp/dnn4_pretrain-dbn_dnn_ali
	lab_opts=ali-to-phones --per-frame=true
	lab_count_file=none
	lab_data_folder=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/data/train/
	lab_graph=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/exp/tri3/graph
n_chunks = 5

[dataset2]
data_name = EMA_MAE_dev
fea = fea_name=art
	fea_lst=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/data/dev/feats_art.scp
	fea_opts=apply-cmvn --utt2spk=ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/data/dev/utt2spk  ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/art/dev_cmvn_speaker.ark ark:- ark:- | add-deltas --delta-order=2 ark:- ark:- |
	cw_left=0
	cw_right=0
	
	fea_name=fmllr
	fea_lst=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/data/dev/feats_fmllr.scp
	fea_opts=apply-cmvn --utt2spk=ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/data/dev/utt2spk  ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/data-fmllr-tri3/dev/dev_cmvn.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
	cw_left=0
	cw_right=0
lab = lab_name=lab_cd
	lab_folder=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/exp/dnn4_pretrain-dbn_dnn_ali_dev
	lab_opts=ali-to-pdf
	lab_count_file=auto
	lab_data_folder=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/data/dev/
	lab_graph=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/exp/tri3/graph
	
	lab_name=lab_mono
	lab_folder=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/exp/dnn4_pretrain-dbn_dnn_ali_dev
	lab_opts=ali-to-phones --per-frame=true
	lab_count_file=none
	lab_data_folder=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/data/dev/
	lab_graph=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/exp/tri3/graph
n_chunks = 1

[dataset3]
data_name = EMA_MAE_test
fea = fea_name=art
	fea_lst=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/data/test/feats_art.scp
	fea_opts=apply-cmvn --utt2spk=ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/data/test/utt2spk  ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/art/test_cmvn_speaker.ark ark:- ark:- | add-deltas --delta-order=2 ark:- ark:- |
	cw_left=0
	cw_right=0
	
	
	fea_name=fmllr
	fea_lst=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/data/test/feats_fmllr.scp
	fea_opts=apply-cmvn --utt2spk=ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/data/test/utt2spk  ark:/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/data-fmllr-tri3/test/test_cmvn.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
	cw_left=0
	cw_right=0
lab = lab_name=lab_cd
	lab_folder=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/exp/dnn4_pretrain-dbn_dnn_ali_test
	lab_opts=ali-to-pdf
	lab_count_file=auto
	lab_data_folder=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/data/test/
	lab_graph=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/graph
	
	lab_name=lab_mono
	lab_folder=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/exp/dnn4_pretrain-dbn_dnn_ali_test
	lab_opts=ali-to-phones --per-frame=true
	lab_count_file=none
	lab_data_folder=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/data/test/
	lab_graph=/audio/kaldi/kaldi/egs/ORG_EMA_MAE/Articulatory/graph
n_chunks = 1

[data_use]
train_with = EMA_MAE_tr
valid_with = EMA_MAE_dev
forward_with = EMA_MAE_test

[batches]
batch_size_train = 8
max_seq_length_train = 1000
increase_seq_length_train = True
start_seq_len_train = 100
multply_factor_seq_len_train = 2
batch_size_valid = 8
max_seq_length_valid = 1000

[architecture1]
arch_name = LSTM_cudnn_layers
arch_proto = proto/LSTM.proto
arch_library = neural_networks
arch_class = LSTM
arch_pretrain_file = none
arch_freeze = False
arch_seq_model = True
lstm_lay = 550,550,550,550
lstm_drop = 0.2,0.2,0.2,0.2
lstm_use_laynorm_inp = False
lstm_use_batchnorm_inp = False
lstm_use_laynorm = False,False,False,False
lstm_use_batchnorm = True,True,True,True
lstm_bidir = True
lstm_act = tanh,tanh,tanh,tanh
lstm_orthinit = True
arch_lr = 0.0016
arch_halving_factor = 0.5
arch_improvement_threshold = 0.001
arch_opt = rmsprop
opt_momentum = 0.0
opt_alpha = 0.95
opt_eps = 1e-8
opt_centered = False
opt_weight_decay = 0.0

[architecture2]
arch_name = MLP_layers
arch_proto = proto/MLP.proto
arch_library = neural_networks
arch_class = MLP
arch_pretrain_file = none
arch_freeze = False
arch_seq_model = False
dnn_lay = N_out_lab_cd
dnn_drop = 0.0
dnn_use_laynorm_inp = False
dnn_use_batchnorm_inp = False
dnn_use_batchnorm = False
dnn_use_laynorm = False
dnn_act = softmax
arch_lr = 0.0016
arch_halving_factor = 0.5
arch_improvement_threshold = 0.001
arch_opt = rmsprop
opt_momentum = 0.0
opt_alpha = 0.95
opt_eps = 1e-8
opt_centered = False
opt_weight_decay = 0.0

[architecture3]
arch_name = MLP_layers2
arch_proto = proto/MLP.proto
arch_library = neural_networks
arch_class = MLP
arch_pretrain_file = none
arch_freeze = False
arch_seq_model = False
dnn_lay = N_out_lab_mono
dnn_drop = 0.0
dnn_use_laynorm_inp = False
dnn_use_batchnorm_inp = False
dnn_use_batchnorm = False
dnn_use_laynorm = False
dnn_act = softmax
arch_lr = 0.0004
arch_halving_factor = 0.5
arch_improvement_threshold = 0.001
arch_opt = rmsprop
opt_momentum = 0.0
opt_alpha = 0.95
opt_eps = 1e-8
opt_centered = False
opt_weight_decay = 0.0

[model]
model_proto = proto/model.proto
model = out_dnn1=compute(LSTM_cudnn_layers,art)
	out_dnn2=compute(MLP_layers,out_dnn1)
	out_dnn3=compute(MLP_layers2,out_dnn1)
	loss_mono=cost_nll(out_dnn3,lab_mono)
	loss_mono_w=mult_constant(loss_mono,1.0)
	loss_cd=cost_nll(out_dnn2,lab_cd)
	loss_final=sum(loss_cd,loss_mono_w)
	err_final=cost_err(out_dnn2,lab_cd)

[forward]
forward_out = out_dnn2
normalize_posteriors = True
normalize_with_counts_from = lab_cd
save_out_file = False
require_decoding = True

[decoding]
decoding_script_folder = kaldi_decoding_scripts/
decoding_script = decode_dnn.sh
decoding_proto = proto/decoding.proto
min_active = 200
max_active = 7000
max_mem = 50000000
beam = 13.0
latbeam = 8.0
acwt = 0.2
max_arcs = -1
skip_scoring = false
scoring_script = local/score.sh
scoring_opts = "--min-lmwt 1 --max-lmwt 10"
norm_vars = False

**Comment by mravanelli** [comment]
*"fea_conc,lab_conc = zip(*fea_sorted)ValueError: not enough values to
unpack (expected 2, got 0)"*

This part means that the features are not imported correctly. As a fist
check make sure that the paths contained in the .scp file exists.
Then you can try to add some prints in the function load_dataset of
data_io.py. For instance you can take a look into the dictionaries "lab"
and "fea"
and check them.  Sometimes the dictionaries could be empty simply because
you are using a different sentence_id for the labels and features...

Mirco

**Comment by narcise** [comment]
Thank you very much. I found the mistake.
