### ISSUE TITLE
LightGRU-error after epoch 1

### ISSUE THREAD

**Issue by ravikirancap** [mravanelli/pytorch-kaldi#64]
I am trying to use the Light GRU model for Indian accent data. The model is failing with the following error after epoch 1. I am just using the MFCC features and running on my local(no GPU). Attaching the config file I used for your reference. What could be the possible reason?

- Reading config file......OK!
- Chunk creation......OK!

------------------------------ Epoch 00 / 23 ------------------------------
Training train_indian chunk = 1 / 10
OMP: Warning #190: Forking a process while a parallel region is active is potentially unsafe.
[========================================] 100% Training | (Batch 242/242)) | L:5.732
Training train_indian chunk = 2 / 10
[========================================] 100% Training | (Batch 243/243)) | L:4.848
Training train_indian chunk = 3 / 10
[=======================================-] 97.5% Training | (Batch 235/240) | L:4.297
[========================================] 100% Training | (Batch 240/240)) | L:4.308
Training train_indian chunk = 4 / 10
[========================================] 100% Training | (Batch 237/237)) | L:4.047
Training train_indian chunk = 5 / 10
[=============---------------------------] 33.3% Training | (Batch 82/243) | L:3.561
[========================================] 100% Training | (Batch 243/243)) | L:3.813
Training train_indian chunk = 6 / 10
[=====================-------------------] 53.7% Training | (Batch 133/246) | L:3.445
[========================================] 100% Training | (Batch 246/246)) | L:3.625
Training train_indian chunk = 7 / 10
[=========-------------------------------] 21.6% Training | (Batch 55/250) | L:3.438
[========================================] 100% Training | (Batch 250/250)) | L:3.528
Training train_indian chunk = 8 / 10
OMP: Warning #190: Forking a process while a parallel region is active is potentially unsafe.
[========================================] 100% Training | (Batch 251/251)) | L:3.392
Training train_indian chunk = 9 / 10
[========================================] 100% Training | (Batch 243/243)) | L:3.351
Training train_indian chunk = 10 / 10
Exception in thread Thread-31:-----------] 0.0% Training | (Batch 1/246) | L:3.661
Traceback (most recent call last):
  File "/Users/ravikiran.d/anaconda3/envs/CPG/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/ravikiran.d/anaconda3/envs/CPG/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ravikiran.d/Desktop/gitrepos/pytorch-kaldi/data_io.py", line 207, in read_lab_fea
    [data_name_fea,data_set_fea,data_end_index_fea]=load_chunk(fea_scp,fea_opts,lab_folder,lab_opts,cw_left,cw_right,max_seq_length, output_folder, fea_only)
  File "/Users/ravikiran.d/Desktop/gitrepos/pytorch-kaldi/data_io.py", line 123, in load_chunk
    [data_name,data_set,data_lab,end_index]=load_dataset(fea_scp,fea_opts,lab_folder,lab_opts,left,right, max_sequence_length, output_folder, fea_only)
  File "/Users/ravikiran.d/Desktop/gitrepos/pytorch-kaldi/data_io.py", line 77, in load_dataset
    fea_conc,lab_conc = zip(*fea_sorted)
ValueError: not enough values to unpack (expected 2, got 0)

[========================================] 100% Training | (Batch 246/246)) | L:3.203
Traceback (most recent call last):
  File "run_exp.py", line 195, in <module>
    [data_name,data_set,data_end_index,fea_dict,lab_dict,arch_dict]=run_nn(data_name,data_set,data_end_index,fea_dict,lab_dict,arch_dict,config_chunk_file,processed_first,next_config_file)
  File "/Users/ravikiran.d/Desktop/gitrepos/pytorch-kaldi/core.py", line 298, in run_nn
    data_name=shared_list[0]
IndexError: list index out of range

[libri_liGRU_fmllr.txt](https://github.com/mravanelli/pytorch-kaldi/files/2950915/libri_liGRU_fmllr.txt)

**Comment by TParcollet** [comment]
Hi ! Could you please verify that the path are correct and that the files specified on the test section of your cfg file exist ?

**Comment by mravanelli** [comment]
Yes, you have to check the validation data....

**Comment by ravikirancap** [comment]
I did not have a dev data set in this case. So I have specified the test data as dev as well. Is it because of that?

**Comment by TParcollet** [comment]
No it is not. You can have a single dataset used for the three fields. Nonetheless, this error is due to a problem when trying to read the input features, that can be due to bad paths.

**Comment by mravanelli** [comment]
Yes,
you would have to:
1- Check if the paths contained in the .scp file of your dev/test data
exist.
2- Then you can try to add some prints in the function load_dataset of
data_io.py. For instance you can take a look into the dictionaries "lab"
and "fea"and check them.  Sometimes the dictionaries could be empty simply
because you are using a different sentence_id for the labels and features...

**Comment by ravikirancap** [comment]
Thank you @TParcollet @mravanelli 
It's resolved now. I have given the path of train alignments directory where I should have given the test alignment directory. 

I have one another question though. The decoding script is unable to get the configs (and hence unable to cd to the required directory) from sourcing `source <(grep = $cfg_file | sed 's/ *= */=/g')` . I tried a workaround by dumping the sed output to a temporary file and sourcing it instead. Any thoughts on this?

**kaldi_decoding_scripts/decode_dnn.sh: line 25: ./path.sh: No such file or directory
kaldi_decoding_scripts/decode_dnn.sh: line 26: ./cmd.sh: No such file or directory
kaldi_decoding_scripts/decode_dnn.sh: line 37: ./parse_options.sh: No such file or directory**

**Comment by mravanelli** [comment]
Hi,
are you running the decoding script manually? If so, remember to do it
within the *kaldi_decoding_scripts *folder.

Mirco

**Comment by ravikirancap** [comment]
No. I am not running it manually. But even if I do, does it matter? There is a `cd $kaldi_decoding_scripts` line in the script which should take care of it. Problem is that it is unable to fetch the $kaldi_decoding_scripts variable
