### ISSUE TITLE
How to avoid alingments from test?

### ISSUE THREAD

**Issue by HardikSailor** [mravanelli/pytorch-kaldi#65]
Hi,

First of all, thank you for this nice toolkit. Currently, we are trying to build models for Aurora 4 dataset. I am facing a problem with decoding the test set. I have a few doubts:

1. Why alignments for final test sets are required? Yes, dev set can be used for validation, however, I don't know where test alignments used.
2. Due to test alignments in Kaldi, of course, some of the test utterances are not aligned properly. This now has a negative impact on reduces test utterances in pytorch DNN decoding. So every time I am decoding results with the label [PARTIAL] in WER. How to avoid this problem and get decoding on all utterances?
Kindly help me regarding this. Thank you so much.

**Comment by Johe-cqu** [comment]
**Hi,**

**I think alignments for final test sets are not required too. You may click this link for answer. [https://github.com/mravanelli/pytorch-kaldi/issues/62](url)**

**I tried to avoid aligning the test set when creating the model, but that seems impossible. You can see the `load_dataset` function in `data-io.py`.It seems that we have to use the alignment dataset (train dec test ) when we need to train the model.**
```
if not fea_only:    
      lab = { k:v for k,v in read_vec_int_ark('gunzip -c '+lab_folder+'/ali*.gz | '+lab_opts+' '+lab_folder+'/final.mdl ark:- ark:-|',output_folder)  if k in fea} # Note that I'm copying only the aligments of the loaded fea
      fea = {k: v for k, v in fea.items() if k in lab} # This way I remove all the features without an aligment (see log file in alidir "Did not Succeded")
```
**So I used other methods. If you want to avoid alignments from test, there are two steps:**
step1: you may need to complete a training process. 
step2: set [dataset3] lab_name = none, Do as "How can I transcript my own audio files".

**This is just my own opinion, I hope that would be useful for you.**

**John**

**Comment by HardikSailor** [comment]
Thank you John. I have tried your suggestions. One another issue I got with this is when we specify chunks to 5, decoding started with lists, however, some list of test are still under preparation. Hence, actual batch has less files than it should since list is still under preparation. When I keep chunk=1, it is taking huge time to start the decoding. Kindly give some suggestions here too.

**Comment by Johe-cqu** [comment]
Hi, @HardikSailor 

I know what you mean，but I don't know what problem you want to solve. (Face with Tears of Joy)

John

**Comment by HardikSailor** [comment]
Hi John Thanks for quick response. I have trained AURORA 4 with pytorch-KALDI. Due to lab_cd options (without none), it only decoded 4111 utts (by seeing alingment stats in KALDI). Now I am trying to decoding again (without training) with lab_cd options to none.  When I do that they start at the same time!
Example for setting chunk=2 for final test. See the second batch is not well created with all 2310 files!. Total test files are 4620.

Forwarding test_eval92 chunk = 1 / 2
[========================================] 100% Forwarding | (Batch 2310/2310))
Forwarding test_eval92 chunk = 2 / 2
[========================================] 100% Forwarding | (Batch 219/219))

**Comment by Johe-cqu** [comment]
Hi, @HardikSailor 

I'm sorry, I can't solve this problem.

(1) "lab_cd options (without none), it only decoded 4111 utts", If you use `align_fmllr.sh` to aligning the test set, this problem may be due to the small value of `beam` and `retry_beam`. You can see this two value in `/home/~/kaldi/eg/aurora4/steps/align_fmllr.sh`.  And you can find some clues in alingment's log file.
(2)You can try to use mfcc feats with lab_cd options to none. I can't solve this problem.

@mravanelli Can you give us some help?

John

**Comment by mravanelli** [comment]
Hi,
regarding the first issue, we will allow users to avoid specifying test
alignments in the next version.
Regarding the second issue, I have to investigate a little bit more on that
because I haven't observed this issue by myself. It could be related to the
recent multithread data loading that we have added. Let me investigate a
little bit on that and I keep you updated!

**Comment by HardikSailor** [comment]
Thank you Mirco Ravanelli. I look forward to your further responses regarding this.

**Comment by HardikSailor** [comment]
Hi, Mirco Ravanelli

I found another issue. During production stage (i.e. testing phase) to transcribe audio why it is again calculating training feature matrices? How to avoid it since it is taking too much time and decoding started with limited test features (since some test chunk still not completed due to training chunk creation)? Kindly help with this.

**Comment by TParcollet** [comment]
Hi ! What do you mean by production stage ? Is it with lab_name=none ? How and where do you see that it is still calculating training matrices ?

**Comment by HardikSailor** [comment]
Hi, Parcollet Titouan
Thanks for response. After training the DNN, I am training to decode the test data with lab_name=none flag. After running the script, when I see log, it shows copy-feats, applying cmvn, etc for training and dev set also!! How to avoid it and only process test features followed by decoding. Since if I don't avoid, ark files created during decoding is not complete (not use all test files) due to test feats not ready!

**Comment by TParcollet** [comment]
Could you please paste your .cfg ?

**Comment by HardikSailor** [comment]
[cfg_proto]
cfg_proto=proto/global.proto
cfg_proto_chunk=proto/global_chunk.proto

[exp]
cmd=
run_nn_script=run_nn
out_folder=exp/aurora4_MLP_fbank_1024_4_09032019
seed=1234
use_cuda=True
multi_gpu=False
save_gpumem=False
N_epochs_tr=19

[dataset1]
data_name=train_si84_clean_tr90
fea:fea_name=fbank
    fea_lst=/share/spandh.ami1/asr/framework/builds/kaurora4_08032019-kaldimonotriphone_aurora4_08032019_20190308_1/data-fbank/train_si84_clean_tr90/feats.scp
    fea_opts=apply-cmvn --utt2spk=ark:/share/spandh.ami1/asr/framework/builds/kaurora4_08032019-kaldimonotriphone_aurora4_08032019_20190308_1/data-fbank/train_si84_clean_tr90/utt2spk ark:/share/spandh.ami1/asr/framework/builds/kaurora4_08032019-kaldimonotriphone_aurora4_08032019_20190308_1/fbank/cmvn_train_si84_clean.ark ark:- ark:- | add-deltas --delta-order=2 ark:- ark:- |
    cw_left=5
    cw_right=5


lab:lab_name=lab_cd
    lab_folder=/share/spandh.ami1/asr/framework/builds/kaurora4_08032019-kaldimonotriphone_aurora4_08032019_20190308_1/kalditraintriphone
    lab_opts=ali-to-pdf 
    lab_count_file=auto
    lab_data_folder=/share/spandh.ami1/asr/framework/builds/kaurora4_08032019-kaldimonotriphone_aurora4_08032019_20190308_1/data-fbank/train_si84_clean_tr90/
    lab_graph=/share/spandh.ami1/asr/framework/builds/kaurora4_08032019-kaldimonotriphone_aurora4_08032019_20190308_1/kaldidecodetriphone/graph_5k

N_chunks=30

[dataset2]
data_name=train_si84_clean_cv10
fea:fea_name=fbank
    fea_lst=/share/spandh.ami1/asr/framework/builds/kaurora4_08032019-kaldimonotriphone_aurora4_08032019_20190308_1/data-fbank/train_si84_clean_cv10/feats.scp
    fea_opts=apply-cmvn --utt2spk=ark:/share/spandh.ami1/asr/framework/builds/kaurora4_08032019-kaldimonotriphone_aurora4_08032019_20190308_1/data-fbank/train_si84_clean_cv10/utt2spk  ark:/share/spandh.ami1/asr/framework/builds/kaurora4_08032019-kaldimonotriphone_aurora4_08032019_20190308_1/fbank/cmvn_train_si84_clean.ark ark:- ark:- | add-deltas --delta-order=2 ark:- ark:- |
    cw_left=5
    cw_right=5


lab:lab_name=lab_cd
    lab_folder=/share/spandh.ami1/asr/framework/builds/kaurora4_08032019-kaldimonotriphone_aurora4_08032019_20190308_1/kaldialigntriphone_train_si84_clean_cv10
    lab_opts=ali-to-pdf 
    lab_count_file=auto
    lab_data_folder=/share/spandh.ami1/asr/framework/builds/kaurora4_08032019-kaldimonotriphone_aurora4_08032019_20190308_1/data-fbank/train_si84_clean_cv10
    lab_graph=/share/spandh.ami1/asr/framework/builds/kaurora4_08032019-kaldimonotriphone_aurora4_08032019_20190308_1/kaldidecodetriphone/graph_5k

N_chunks=4
                                                                                                                                                                                
[dataset3]
data_name=test_eval92
fea:fea_name=fbank
    fea_lst=/share/spandh.ami1/asr/framework/builds/kaurora4_08032019-kaldimonotriphone_aurora4_08032019_20190308_1/data-fbank/test_eval92/feats.scp
    fea_opts=apply-cmvn --utt3spk=ark:/share/spandh.ami1/asr/framework/builds/kaurora4_08032019-kaldimonotriphone_aurora4_08032019_20190308_1/data-fbank/test_eval92/utt2spk  ark:/share/spandh.ami1/asr/framework/builds/kaurora4_08032019-kaldimonotriphone_aurora4_08032019_20190308_1/fbank/cmvn_test_eval92.ark ark:- ark:- | add-deltas --delta-order=2 ark:- ark:- |
    cw_left=5
    cw_right=5


lab:lab_name=none
    lab_data_folder=/share/spandh.ami1/asr/framework/builds/kaurora4_08032019-kaldimonotriphone_aurora4_08032019_20190308_1/data-fbank/test_eval92/
    lab_graph=/share/spandh.ami1/asr/framework/builds/kaurora4_08032019-kaldimonotriphone_aurora4_08032019_20190308_1/kaldidecodetriphone/graph_5k

N_chunks=4


[data_use]
train_with=train_si84_clean_tr90
valid_with=train_si84_clean_cv10
forward_with=test_eval92


[batches]
batch_size_train=128
max_seq_length_train=1000
increase_seq_length_train=False
start_seq_len_train=100
multply_factor_seq_len_train=2
batch_size_valid=128
max_seq_length_valid=1000


[architecture1]
arch_name=MLP_layers
arch_proto=proto/MLP.proto
arch_library=neural_networks
arch_class=MLP
arch_pretrain_file=none
arch_freeze=False
arch_seq_model=False

dnn_lay=1024,1024,1024,1024,N_out_lab_cd
dnn_drop=0.15,0.15,0.15,0.15,0.0
dnn_use_laynorm_inp=False
dnn_use_batchnorm_inp=False
dnn_use_batchnorm=True,True,True,True,False
dnn_use_laynorm=False,False,False,False,False
dnn_act=relu,relu,relu,relu,softmax

arch_lr=0.08
arch_halving_factor=0.5
arch_improvement_threshold=0.001
arch_opt=sgd
opt_momentum=0.0
opt_weight_decay=0.0
opt_dampening=0.0
opt_nesterov=False


[model]
model_proto=proto/model.proto
model:out_dnn1=compute(MLP_layers,fbank)
      loss_final=cost_nll(out_dnn1,lab_cd)
      err_final=cost_err(out_dnn1,lab_cd)


[forward]
forward_out=out_dnn1
normalize_posteriors=True
normalize_with_counts_from=lab_cd
save_out_file=False
require_decoding=True


[decoding]
decoding_script_folder=kaldi_decoding_scripts/
decoding_script=decode_dnn.sh
decoding_proto=proto/decoding.proto
min_active=200
max_active=7000
max_mem=50000000
beam=15.0
latbeam=8.0
acwt=0.10
max_arcs=-1
skip_scoring=false
scoring_script=local/score.sh
scoring_opts="--min-lmwt 4 --max-lmwt 23"
norm_vars=False

**Comment by TParcollet** [comment]
What is the exact process that you are following ? You first train with a .cfg where you do not use test_eval92 during 19 epochs. Then once everything went correctly (training during 19 epoch), you call run_exp.py with this cfg file ?

**Comment by HardikSailor** [comment]
I will tell you the ordering of training and issues.

1, I created config files and necessary scripts for AURORA 4 with similar setup as librispeech
That config files contains train90, cv10 (dev set), and test_eval92 as three datasets. However, as with other demo config files, I kept  lab:lab_name=lab_cd and paths of generated alignments from validation and test sets.

2. Training work well and reasonable WER. However, decoded results are partial!
%WER 26.49 [ 17573 / 66346, 3441 ins, 4072 del, 10060 sub ] [PARTIAL] exp/aurora4_MLP_fbank_1024_4_09032019/decode_test_eval92_out_dnn1_org/wer_14_1.0
Reason: It only choose those test utts that has aligned well in KALDI with HMM system (test_ali kaldi folder)!!! Its natural that some of utts may not aligned. However, one must not find alignments on test data  since its a test data. All demo config files are doing this.
I am doing everything to solve this problem. If I can avoid taking ali of test it should be solved. So next is to get that solved. 
3. To avoid this, I tried lab:lab_name=none in config file and now only execute script for decoding purpose (since I don't need to run training again). With option, I am facing following problem that can be seen in log file:
  -- creating lists, features using copy-feats, etc for test, train, validation data (It must not do this since I am only test)
--- Due to this there is a delay in actual test feats list and other files preparation for decoder
--- And decoding started with whatever test set created (even if actual process of feature preparation for test still running in log.log file). You can see below that only first batch has all chunk files. There are 4 chunks of test_eval92 since all 4 chunks must has 1155 files. The only reason is I found by looking at log files is that the config and data preparation is long process which is parallel going on for train, test, validation (multithread fashion).
-- Forwarding test_eval92 chunk = 1 / 4
[========================================] 100% Forwarding | (Batch 1155/1155))
Forwarding test_eval92 chunk = 2 / 4
[========================================] 100% Forwarding | (Batch 219/219))
Forwarding test_eval92 chunk = 3 / 4
[========================================] 100% Forwarding | (Batch 226/226))
Forwarding test_eval92 chunk = 4 / 4
[========================================] 100% Forwarding | (Batch 232/232))

I hope now you are clear the problem. Its just evacuation and creation of files for decoder that is tampered due to huge processing of train and validation features along with test! This must not be the case when you already have trained model and you are only using for testing.

I need everyone's suggestions to solve this fast since INTERSPEECH deadline is quite near!

**Comment by HardikSailor** [comment]
By the way, it is mismatch (clean training, noisy test) training in AURORA 4 so high %WER is expected.

**Comment by TParcollet** [comment]
Ok, I'm on it. Let me check the code.

**Comment by TParcollet** [comment]
One quick fix you can try is to set.
[data_use]
train_with=test_eval92
valid_with=test_eval92
forward_with=test_eval92

It might exist a problem with our production setup and the new multithreaded loading. Let me try.

**Comment by TParcollet** [comment]
Also, when using this .cfg file you are directly seeing forwarding steps right (no training) ?

**Comment by TParcollet** [comment]
Hi, we pushed corrections to the production case. Your first .cfg should now work without loading train and dev datasets. **PLEASE** note that you must delete your log.log file if you wan't to see what is happening between two calls of the same .cfg file by run_exp.py. Indeed, the loading of the test files (in production) will be appended after the training logs. **WARNING** your call in architecture3 of N_out_lab_cd must be replaced to N_out_lab_none in production mod since lab_cd won't be seen anymore (none flag skip all the datasets that are not used in the forward_with).

**Comment by HardikSailor** [comment]
Hi, Hi, Parcollet Titouan

Thank you so much. Yes, I will try the new setup and let you know.

**Comment by HardikSailor** [comment]
Hi, Parcollet Titouan

I have tried the way you suggested with new pytorch git version (and other ways to solve too!) to solve production mode problem. It throuws following error with the settings you suggested:

ERROR: the count_file "N_out_none" in the section "forward_out" does not exist) when set none option for lab_cd in both architecture1 and normalize_with_counts_from=N_out_none in forward field

Another case:

ERROR: the count_file "lab_cd" in the section "forward_out" does not exist)
when set none option for lab_cd in architecture1 and normalize_with_counts_from=N_out_lab_cd in forward field

Third case:

Same as above error if N_out_lab_cd kept as it it.

Please suggest regarding this.

Thank you.

**Comment by TParcollet** [comment]
Please send me the cfg file that is causing these errors.

**Comment by HardikSailor** [comment]
[cfg_proto]
cfg_proto=proto/global.proto
cfg_proto_chunk=proto/global_chunk.proto

[exp]
cmd=
run_nn_script=run_nn
out_folder=exp/aurora4_MLP_fbank_1024_4_20032019_uttcmvn
seed=1234
use_cuda=True
multi_gpu=False
save_gpumem=False
N_epochs_tr=24

[dataset1]
data_name=train_si84_clean_tr90
fea:fea_name=fbank
    fea_lst=/share/spandh.ami1/asr/framework/builds/kaurora4-kaldimonotriphonednn_aurora4_20190301_3/data-fbank/train_si84_clean_tr90/feats.scp
    fea_opts=apply-cmvn ark:/share/spandh.ami1/asr/framework/builds/kaurora4-kaldimonotriphonednn_aurora4_20190301_3/fbank/cmvn_train_si84_clean.ark ark:- ark:- | add-deltas --delta-order=2 ark:- ark:- |
    cw_left=5
    cw_right=5


lab:lab_name=lab_cd
    lab_folder=/share/spandh.ami1/asr/framework/builds/kaurora4-kaldimonotriphonednn_aurora4_20190301_3/kaldialign_triphone
    lab_opts=ali-to-pdf 
    lab_count_file=auto
    lab_data_folder=/share/spandh.ami1/asr/framework/builds/kaurora4-kaldimonotriphonednn_aurora4_20190301_3/data-fbank/train_si84_clean_tr90/
    lab_graph=/share/spandh.ami1/asr/framework/builds/kaurora4-kaldimonotriphonednn_aurora4_20190301_3/kaldidecodetriphone/graph_5k

N_chunks=30

[dataset2]
data_name=train_si84_clean_cv10
fea:fea_name=fbank
    fea_lst=/share/spandh.ami1/asr/framework/builds/kaurora4-kaldimonotriphonednn_aurora4_20190301_3/data-fbank/train_si84_clean_cv10/feats.scp
    fea_opts=apply-cmvn ark:/share/spandh.ami1/asr/framework/builds/kaurora4-kaldimonotriphonednn_aurora4_20190301_3/fbank/cmvn_train_si84_clean.ark ark:- ark:- | add-deltas --delta-order=2 ark:- ark:- |
    cw_left=5
    cw_right=5


lab:lab_name=lab_cd
    lab_folder=/share/spandh.ami1/asr/framework/builds/kaurora4-kaldimonotriphonednn_aurora4_20190301_3/kaldialigntriphone_train_si84_clean_cv10
    lab_opts=ali-to-pdf 
    lab_count_file=auto
    lab_data_folder=/share/spandh.ami1/asr/framework/builds/kaurora4-kaldimonotriphonednn_aurora4_20190301_3/data-fbank/train_si84_clean_cv10
    lab_graph=/share/spandh.ami1/asr/framework/builds/kaurora4-kaldimonotriphonednn_aurora4_20190301_3/kaldidecodetriphone/graph_5k

N_chunks=4

[dataset3]
data_name=test_C
fea:fea_name=fbank
    fea_lst=/share/spandh.ami1/asr/framework/builds/kaurora4-kaldimonotriphonednn_aurora4_20190301_3/data-fbank/test_C/feats.scp
    fea_opts=apply-cmvn ark:/share/spandh.ami1/asr/framework/builds/kaurora4-kaldimonotriphonednn_aurora4_20190301_3/fbank/cmvn_test_C.ark ark:- ark:- | add-deltas --delta-order=2 ark:- ark:- |
    cw_left=5
    cw_right=5


lab:lab_name=none
    lab_data_folder=/share/spandh.ami1/asr/framework/builds/kaurora4-kaldimonotriphonednn_aurora4_20190301_3/data-fbank/test_C
    lab_graph=/share/spandh.ami1/asr/framework/builds/kaurora4-kaldimonotriphonednn_aurora4_20190301_3/kaldidecodetriphone/graph_5k

N_chunks=1



[data_use]
train_with=train_si84_clean_tr90
valid_with=train_si84_clean_cv10
forward_with=test_C


[batches]
batch_size_train=128
max_seq_length_train=1000
increase_seq_length_train=False
start_seq_len_train=100
multply_factor_seq_len_train=2
batch_size_valid=128
max_seq_length_valid=1000


[architecture1]
arch_name=MLP_layers
arch_proto=proto/MLP.proto
arch_library=neural_networks
arch_class=MLP
arch_pretrain_file=none
arch_freeze=False
arch_seq_model=False

dnn_lay=1024,1024,1024,1024,N_out_none
dnn_drop=0.15,0.15,0.15,0.15,0.0
dnn_use_laynorm_inp=False
dnn_use_batchnorm_inp=False
dnn_use_batchnorm=True,True,True,True,False
dnn_use_laynorm=False,False,False,False,False
dnn_act=relu,relu,relu,relu,softmax

arch_lr=0.08
arch_halving_factor=0.5
arch_improvement_threshold=0.001
arch_opt=sgd
opt_momentum=0.0
opt_weight_decay=0.0
opt_dampening=0.0
opt_nesterov=False


[model]
model_proto=proto/model.proto
model:out_dnn1=compute(MLP_layers,fbank)
      loss_final=cost_nll(out_dnn1,lab_cd)
      err_final=cost_err(out_dnn1,lab_cd)


[forward]
forward_out=out_dnn1
normalize_posteriors=True
normalize_with_counts_from=N_out_lab_cd
save_out_file=False
require_decoding=True


[decoding]
decoding_script_folder=kaldi_decoding_scripts/
decoding_script=decode_dnn.sh
decoding_proto=proto/decoding.proto
min_active=200
max_active=7000
max_mem=50000000
beam=15.0
latbeam=8.0
acwt=0.10
max_arcs=-1
skip_scoring=false
scoring_script=local/score.sh
scoring_opts="--min-lmwt 4 --max-lmwt 23"
norm_vars=False

**Comment by HardikSailor** [comment]
I also tried to set lab_cd=none everywhere however got errors as I mentioned in previous email.

**Comment by mravanelli** [comment]
Could you try to replace "N_out_none" with "N_out_lab_cd"? N_out_none is
not a recognized keyword and you cannot estimate the right number of output
with that...

Mirco

**Comment by TParcollet** [comment]
@mravanelli N_out_lab_cd won't work. As long as production is detected, all the other field are purely removed from the cfg.

**Comment by TParcollet** [comment]
@HardikSailor Please let me work on this a little bit.

**Comment by HardikSailor** [comment]
Yes, sure. Thank you.

**Comment by TParcollet** [comment]
@HardikSailor Please consider pulling the repo and reading the new How to Decode My Own Audio File section.

**Comment by HardikSailor** [comment]
@TParcollet Thank you so much. I will try it ASAP.

**Comment by HardikSailor** [comment]
Thank you everyone. Test mode is now working fine. I am closing this query and will open a new one for different critical issue!
