### ISSUE TITLE
cannot make fmllr for Librispeech

### ISSUE THREAD

**Issue by shigetajima** [mravanelli/pytorch-kaldi#68]
Hi, I am following pytorch-kaldi's Librispeech tutorial. https://github.com/mravanelli/pytorch-kaldi#librispeech-tutorial  I have issues when I do step-2 of this tutorial. In Step-1, I ran kaldi's run.sh for Librispeech until stage 13 (since I noticed this stage has the line "decode using the tri4b model"). I did not see any errors. 

Then in Step-2, I simply copied the script (posted in the tutorial) and saved it as make_fmllr_pytorch_kaldi.sh , and ran it to try to make fmllr. there was no error when I set chunk=train_clean_100, but I got errors when I set chunk=dev_clean or chunk=test_clean . The below error happened when chunk=dev_clean

$ ./make_fmllr_pytorch_kaldi.sh 
steps/nnet/make_fmllr_feats.sh --nj 10 --cmd run.pl --transform-dir exp/tri4b/decode_tgsmall_dev_clean fmllr/dev_clean data/dev_clean exp/tri4b fmllr/dev_clean/log fmllr/dev_clean/data 
steps/nnet/make_fmllr_feats.sh: feature type is lda_fmllr 
apply_map.pl: undefined key 174-50561-0000 in fmllr/dev_clean/utt_map

I looked into the log dir but there was no log file created. I opened utt_map and confirmed that the above key is indeed not found in utt_map. Why is utt_make not made correctly? Or do I need to run more stages when I ran kaldi's recipe? If so, until which stage(s) do I need to run?

The errors I got when chunk=test_clean are below.

WARNING (transform-feats[5.5.203~1-6fc4]:main():transform-feats.cc:87) No fMLLR transform available for utterance 1284-1181-0000, producing no output for this utterance
WARNING (transform-feats[5.5.203~1-6fc4]:main():transform-feats.cc:87) No fMLLR transform available for utterance 1284-1181-0001, producing no output for this utterance
WARNING (transform-feats[5.5.203~1-6fc4]:main():transform-feats.cc:87) No fMLLR transform available for utterance 1284-1181-0002, producing no output for this utterance
...
...
...
ERROR (copy-feats[5.5.203~1-6fc4]:~SequentialTableReaderArchiveImpl():util/kaldi-table-inl.h:678) TableReader: error detected closing archive 'apply-cmvn  --utt2spk=ark:data/test_clean/split10/2/utt2spk scp:data/test_clean/split10/2/cmvn.scp scp:data/test_clean/split10/2/feats.scp ark:- | splice-feats --left-context=3 --right-context=3 ark:- ark:- | transform-feats exp/tri4b/final.mat ark:- ark:- | transform-feats --utt2spk=ark:data/test_clean/split10/2/utt2spk "ark:cat exp/tri4b/decode_tgsmall_test_clean/trans.* |" ark:- ark:- |'

[ Stack-Trace: ]
kaldi::MessageLogger::HandleMessage(kaldi::LogMessageEnvelope const&, char const*)
kaldi::FatalMessageLogger::~FatalMessageLogger()
kaldi::SequentialTableReaderArchiveImpl<kaldi::KaldiObjectHolder<kaldi::Matrix<float> > >::~SequentialTableReaderArchiveImpl()
kaldi::SequentialTableReaderArchiveImpl<kaldi::KaldiObjectHolder<kaldi::Matrix<float> > >::~SequentialTableReaderArchiveImpl()
kaldi::SequentialTableReader<kaldi::KaldiObjectHolder<kaldi::Matrix<float> > >::~SequentialTableReader()
main
__libc_start_main
_start

ERROR (copy-feats[5.5.203~1-6fc4]:~SequentialTableReaderArchiveImpl():util/kaldi-table-inl.h:678) TableReader: error detected closing archive 'apply-cmvn  --utt2spk=ark:data/test_clean/split10/2/utt2spk scp:data/test_clean/split10/2/cmvn.scp scp:data/test_clean/split10/2/feats.scp ark:- | splice-feats --left-context=3 --right-context=3 ark:- ark:- | transform-feats exp/tri4b/final.mat ark:- ark:- | transform-feats --utt2spk=ark:data/test_clean/split10/2/utt2spk "ark:cat exp/tri4b/decode_tgsmall_test_clean/trans.* |" ark:- ark:- |'

[ Stack-Trace: ]
kaldi::MessageLogger::HandleMessage(kaldi::LogMessageEnvelope const&, char const*)
kaldi::MessageLogger::~MessageLogger()
kaldi::FatalMessageLogger::~FatalMessageLogger()
kaldi::SequentialTableReaderArchiveImpl<kaldi::KaldiObjectHolder<kaldi::Matrix<float> > >::~SequentialTableReaderArchiveImpl()
kaldi::SequentialTableReaderArchiveImpl<kaldi::KaldiObjectHolder<kaldi::Matrix<float> > >::~SequentialTableReaderArchiveImpl()
kaldi::SequentialTableReader<kaldi::KaldiObjectHolder<kaldi::Matrix<float> > >::~SequentialTableReader()
main
__libc_start_main
_start

terminate called after throwing an instance of 'std::runtime_error'
  what():
\# Accounting: time=5 threads=1
\# Ended (code 134) at Wed Mar 13 23:40:56 UTC 2019, elapsed time 5 seconds

**Comment by mravanelli** [comment]
Hi,
I think you should simply do the steps decoding steps in the ru.sh
indicated as "decode using the tri4b model". Have you done them?

Mirco

**Comment by shigetajima** [comment]
Hi Mirco, 
Yes,  "decode using the tri4b model" is mentioned in both in stages 12 and 13 of run.sh, so I ran it until stage 13. 
Is that correct?  Thank you.

**Comment by mravanelli** [comment]
I think you should run also the second one...

Mirco

**Comment by shigetajima** [comment]
Do you mean I should repeat running the code until stage 13 ? Or repeat running stage 13 only?

**Comment by mravanelli** [comment]
I think the error is due to the fact that decoding on the dev and test that
are missing for some reason. They are needed to compute the fmllr
transformation...

**Comment by shigetajima** [comment]
Hi Mirco,
Thank you, I reran run.sh until stage 13 (and made sure that the decoding is finished). Then I was able to compute the fMLLR features for train_clean_100, dev_clean, and test_clean datasets. 

But when I did this, I did not see how the folder exp/tri4b/decode_tgsmall_train_clean_100/ was created: it looks like none of the kaldi scripts makes this folder, so I had to make it by hand, and copy the exp/tri4b/trans.* files into this folder in order to run your fmllr script to work with train_clean_100. Is this procedure correct? The other two folders (exp/tri4b/decode_tgsmall_dev_clean/  and  exp/tri4b/decode_tgsmall_test_clean/ ) folders as well as their trans.* files are created after stage 13 decoding.

**Comment by mravanelli** [comment]
It doesn't seems a problem. Apparently they recently changed a bit the
run.sh file and it's not exactly the one I used some time ago to run my
baselines. Let me know if you are able to run the experiment with
pytorch-kaldi....

Mirco

**Comment by shigetajima** [comment]
Hi Mirco,
Thank you again for your comments. I was able to run the code using Librispeech corpus with MLP. I ran up to epochs=10, but it ran and no errors. I'd like to suggest updating the Librispeech tutorial instructions as you said run.sh was updated recently. Given below are things that are new or need to be updated.

In Step-1 (kaldi), Run the baseline until stage 13 (included).

In Step-2 (kaldi), copy exp/tri4b/trans.* files into exp/tri4b/decode_tgsmall_train_clean_100/ before running the make_fmllr_feats.sh script using chunk=train_clean_100

In step-3 (kaldi): run this in addition to dev and test.
`steps/align_fmllr.sh --nj 30 data/train_clean_100 data/lang exp/tri4b exp/tri4b_ali_clean_100`

In Step-4 (pytorch-kaldi): no new update

**Comment by mravanelli** [comment]
Sure,
feel free to update the README file with the new information and do a pull
request. Thank you very much for your cooperation!

Mirco

**Comment by shigetajima** [comment]
yes, I will do so.

**Comment by mravanelli** [comment]
thank you!
