### ISSUE TITLE
Decode only option

### ISSUE THREAD

**Issue by ravikirancap** [mravanelli/pytorch-kaldi#70]
Let's say I want to decode new utterances which were not present in the cfg file, is there an option to do this. Extending the same, is online decoding possible using pytorch-kaldi

**Comment by TParcollet** [comment]
Hi,

You can take a look at "How can I transcript my own audio files" that shows how to transcript other audio files from a pre-trained model.

**Comment by ravikirancap** [comment]
My bad, missed that section

Thank you

**Comment by vkdhanaraj** [comment]
Hello, I want to transcript my own audio file. I have it in .wav format. I'am not understanding where exactly to specify the path to .wav file so that the model uses it and produces corresponding text.
