### ISSUE TITLE
GRU

### ISSUE THREAD

**Issue by Johe-cqu** [mravanelli/pytorch-kaldi#71]
**Hi,Mirco @mravanelli** 

 **I have read your paper** _Light Gated Recurrent Units for Speech Recognition_ **,and I have one question.**
 
**In reference [[47]](https://arxiv.org/abs/1412.3555), the standard GRU architecture is defined by** h<sub>t</sub>=(1-z<sub>t</sub>) * h<sub>t-1</sub>+z<sub>t</sub>*h<sub>t</sub> **.** 

**But in your paper, the standard GRU architecture is defined by** h<sub>t</sub>=z<sub>t</sub> * h<sub>t-1</sub>+(1-z<sub>t</sub>)*h<sub>t</sub> **.** **And in your code** `neural_networks.py`  , **it also defined by your equation.**

**Why? Does it perform better?**

**John**

**Comment by TParcollet** [comment]
Hi ! 
In our implementation of GRU you can find this line `ht=(zt*ht+(1-zt)*hcand)`. Here, **ht** = **ht-1** and **hcand** is equivalent to **ht** if compared to the official equations. In the case of a liGRU you have the exact same equation, but the gate **rt** disappeared .

**Comment by Johe-cqu** [comment]
**Hi,
Thank you for your reply, but I think you misunderstood what I meant.**  
**I know  your  code** `ht=(zt*ht+(1-zt)*hcand)`  **stand for**   h<sub>t</sub>=z<sub>t</sub> * h<sub>t-1</sub>+(1-z<sub>t</sub>)*h<sub>t</sub>.

**But in reference** [[47]](https://arxiv.org/abs/1412.3555), **the standard GRU architecture is defined by** h<sub>t</sub>=(1-z<sub>t</sub>) * h<sub>t-1</sub>+z<sub>t</sub>*h<sub>t</sub> .

**Your expression seems to be a little different from the reference [47].**

John

**Comment by TParcollet** [comment]
Well I don't know this paper, but if I do a quick search I can find the same equation that we are using here: https://towardsdatascience.com/understanding-gru-networks-2ef37df6c9be . In fact, I suppose that this makes no real difference, since it's just inverting the use of ht and ht-1. @mravanelli What do you think ?

**Comment by Johe-cqu** [comment]
Thank you for reminding @TParcollet 

It's just inverting the use of z<sub>t</sub> and 1-z<sub>t</sub>.

John

**Comment by mravanelli** [comment]
Hi,
yes the two models are equivalent. Both formulations are possible and
normally lead to the same or a very similar performance.

Best,

Mirco
