### ISSUE TITLE
Different decoding results for Aurora 4

### ISSUE THREAD

**Issue by HardikSailor** [mravanelli/pytorch-kaldi#75]
I have observed a strange behavior in decoding results. Here is a summary.

Trying to decode Aurora 4 test sets A, B, C, D and all (combining A to D via kaldi combine dir tool). I have make sure the number of utterances in all test sets are correct and feature files and hence no issue in data directory.

Now I have decoded test set A to D and obtained reasonable WER with number of chunks to 1
I have decoded test all set  with chunks =4 , here I seen the decoding log and found that the decoded results are slightly different then obtained using individual test sets! 

I carefully examine many files and found that some of decoded text is same as test A however likelihood is different! (see second example utt no. 444c020m0).

During decoding each utt is considered independent then how can this be possible? I have checked the final.mdl is also same during decoding. Is it related to number of chunks =4 for test all. I can't reduce it for full test since it throws memory error. Your suggests are most welcome. Thank you.

Few Examples
For test A (330 utts)

latgen-faster-mapped --min-active=200 --max-active=7000 --max-mem=50000000 --beam=15.0 --lattice-beam=8.0 --acoustic-scale=0.10 --allow-partial=true --word-symbol-table=/share/spandh.ami1/asr/framework/builds/kaurora4-kaldimonotriphonednn_aurora4_20190301_3/kaldidecodetriphone/graph_5k/words.txt /share/spandh.ami1/asr/framework/builds/kaurora4-kaldimonotriphonednn_aurora4_20190301_3/kaldidecodetriphone/final.mdl /share/spandh.ami1/asr/framework/builds/kaurora4-kaldimonotriphonednn_aurora4_20190301_3/kaldidecodetriphone/graph_5k/HCLG.fst 'ark,s,cs: cat /share/spandh.ami1/usr/hardik/PyTorch_Kaldi/aurora4/exp/aurora4_MLP_fbank_1024_4_20032019_uttcmvn/exp_files/forward_test_All_ep23_ck0_out_dnn1_to_decode.ark |' 'ark:|gzip -c > /share/spandh.ami1/usr/hardik/PyTorch_Kaldi/aurora4/exp/aurora4_MLP_fbank_1024_4_20032019_uttcmvn/decode_test_All_out_dnn1/lat.1.gz'

447c020d0 I WILL TELL YOU I THINK IN MY OFFICE
LOG (latgen-faster-mapped[5.5.101~1-cd6d5]:DecodeUtteranceLatticeFaster():decoder-wrappers.cc:289) Log-like per frame for utterance 447c020d0 is 0.266065 over 451 frames.
444c020m0 WE HAD A SUSTAINED THE MODEST OPERATING LOSSES
LOG (latgen-faster-mapped[5.5.101~1-cd6d5]:DecodeUtteranceLatticeFaster():decoder-wrappers.cc:289) Log-like per frame for utterance 444c020m0 is 0.275512 over 457 frames.

For all test (4620 utt)

latgen-faster-mapped --min-active=200 --max-active=7000 --max-mem=50000000 --beam=15.0 --lattice-beam=8.0 --acoustic-scale=0.10 --allow-partial=true --word-symbol-table=/share/spandh.ami1/asr/framework/builds/kaurora4-kaldimonotriphonednn_aurora4_20190301_3/kaldidecodetriphone/graph_5k/words.txt /share/spandh.ami1/asr/framework/builds/kaurora4-kaldimonotriphonednn_aurora4_20190301_3/kaldidecodetriphone/final.mdl /share/spandh.ami1/asr/framework/builds/kaurora4-kaldimonotriphonednn_aurora4_20190301_3/kaldidecodetriphone/graph_5k/HCLG.fst 'ark,s,cs: cat /share/spandh.ami1/usr/hardik/PyTorch_Kaldi/aurora4/exp/aurora4_MLP_fbank_1024_4_20032019_uttcmvn/exp_files/forward_test_A_ep23_ck0_out_dnn1_to_decode.ark |' 'ark:|gzip -c > /share/spandh.ami1/usr/hardik/PyTorch_Kaldi/aurora4/exp/aurora4_MLP_fbank_1024_4_20032019_uttcmvn/decode_test_A_out_dnn1/lat.1.gz'

447c020d0 I WOULD SO <UNK> IN <UNK> OFFICE
LOG (latgen-faster-mapped[5.5.101~1-cd6d5]:DecodeUtteranceLatticeFaster():decoder-wrappers.cc:289) Log-like per frame for utterance 447c020d0 is 0.178518 over 451 frames.
444c020m0 WE HAD A SUSTAINED THE MODEST OPERATING LOSSES
LOG (latgen-faster-mapped[5.5.101~1-cd6d5]:DecodeUtteranceLatticeFaster():decoder-wrappers.cc:289) Log-like per frame for utterance 444c020m0 is 0.240718 over 457 frames.

**Comment by HardikSailor** [comment]
Oops I don't know why those lines come. Please ignore it

**Comment by HardikSailor** [comment]
Interesting observation!!

I have decoded test all set with chunks=6 (earlier it was 4) and again the decoding logs are different ! Log likelihood is also slightly different and hence it conclude that there is problem with decoding with chunks!

Kindly help me to solve this.

**Comment by TParcollet** [comment]
I suspect the fact that chunks are naive segmentations. We don't know how the decoding will behave around the segmented area. @mravanelli What do you think ?

**Comment by TParcollet** [comment]
@HardikSailor Do you see a significant impact on the WER ?

**Comment by HardikSailor** [comment]
@TParcollet Yes, WER changed about 1 %. If I do chunk=1 for test data (that has 4620 utts) it shows memory error. I tried on both CPU and GPU mode but memory error still there in data_load function.

**Comment by HardikSailor** [comment]
@TParcollet Also chunks are with respect to utterances (1155 utts in every chunk if no. of chunks=4) so it should not affect the performance.

**Comment by HardikSailor** [comment]
When chunk=2 or less following error occurs

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/share/spandh.ami1/sw/std/python/anaconda3/v3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/share/spandh.ami1/sw/std/python/anaconda3/v3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/share/spandh.ami1/sw/spl/Pytorch_Kaldi_ver/git_2019_03_20/pytorch-kaldi/data_io.py", line 207, in read_lab_fea
    [data_name_fea,data_set_fea,data_end_index_fea]=load_chunk(fea_scp,fea_opts,lab_folder,lab_opts,cw_left,cw_right,max_seq_length, output_folder, fea_only)
  File "/share/spandh.ami1/sw/spl/Pytorch_Kaldi_ver/git_2019_03_20/pytorch-kaldi/data_io.py", line 127, in load_chunk
    data_set=context_window(data_set,left,right)
  File "/share/spandh.ami1/sw/spl/Pytorch_Kaldi_ver/git_2019_03_20/pytorch-kaldi/data_io.py", line 108, in context_window
    fea_conc=np.empty([N_elem,N_fea*(left+right+1)])
MemoryError

- Reading config file......OK!
- Chunk creation......OK!

Forwarding test_All chunk = 1 / 2
Traceback (most recent call last):
  File "/share/spandh.ami1/sw/spl/Pytorch_Kaldi_ver/git_2019_03_20/pytorch-kaldi/run_exp.py", line 332, in <module>
    [data_name,data_set,data_end_index,fea_dict,lab_dict,arch_dict]=run_nn(data_name,data_set,data_end_index,fea_dict,lab_dict,arch_dict,config_chunk_file,processed_first,next_config_file)
  File "/share/spandh.ami1/sw/spl/Pytorch_Kaldi_ver/git_2019_03_20/pytorch-kaldi/core.py", line 81, in run_nn
    data_name=shared_list[0]
IndexError: list index out of range
Done

**Comment by mravanelli** [comment]
Hi,
let me add some comments:
1- if you want to speed up a bit decoding you can use multi-threading. To
do it, you can set the number of threads that you want (e.g. 4 or 8) in the
variable "num_threads" that you can find
in kaldi_decoding_scripts/decode_dnn.sh. I haven't observed a massive speed
up, but other users have noticed it. Please, let us know if this helps for
you.
2- In the current version we read the chunk and we store it in RAM. This
means that if you don't have enough memory or your chunk is too big, you
might run into an out-of-memory issue. You can either work on a machine
with higher RAM or increase the number of chunk.
3- Regarding the variation of the results when you change the number of
chunks, I think the only explanation is that this version of the toolkit
performs per-chunk mean and variance normalization. This means that if you
change the number of chunk, you have slightly different normalization
statistics. This normally doesn't change the performance that much, but for
tasks characterized by a lot of noise (an thus a lot of uncertainty) a
higher variation can arise. I will investigate a little bit on that. In the
next version of the toolkit, we will support other types of normalization
that can bypass this issue.

**Comment by HardikSailor** [comment]
@mravanelli Thank you for your response. I agree with the above first two points. However, I am now worried about the last point. During feature preparation, I have set the option to calculate CMVN per utterance and we then specify cmvn file in cfg. If it per chunk CMVN then it is bad for decoding since for noisy task results significantly differ. During training also it is doing the same way? If yes can I avoid giving cmvn option and only give to compute delta features? I may then directly compute mean subtracted features in Kaldi directly (via substract_mean=true option in compute-feats-fbank). Please suggest.

**Comment by mravanelli** [comment]
Hi,

let me take this opportunity to clarify a bit better how CMNV is done.
There are actually two possible normalizations, that happen one after the
other:

- The first CMVN normalization is not mandatory and can be specified using
the field "fea_opts"(e.g., apply-cmvn
--utt2spk=ark:quick_test/data/train/utt2spk
ark:quick_test/mfcc/train_cmvn_speaker.ark ark:- ark:- | add-deltas
--delta-order=2 ark:- ark:- |). In this example, we apply different
normalization statistics for each speaker as normally done within Kaldi.

- Then we apply another CMVN, that is mandatory. This normalization is
applied in the function "load_chunk" in data_io.py. See the following lines:

 # mean and variance normalization
  data_set=(data_set-np.mean(data_set,axis=0))/np.std(data_set,axis=0)

Note that this normalization is computed for each chunk, because mean and
std statistics are computed over the full chunk.  These normalization
statistics can thus change a bit depending on the chunk size. Actually, if
the chunk size is large enough (e.g, 1 hour of speech) only tiny variations
are expected. Note that the same normalization procedure is the same for
training, test, and validation data, so there isn't a mismatch from this
point of view.

The reason why we apply this second normalization is that in this way we
are 100% sure that the input features are normalized, even if the user
doesn't specify any normalization in the "fea_opts" field.
Said that, if you have specified a normalization in the field "fea_opts",
this second one is not really needed.

To check if it is the second normalization that causes the change of
performance during decoding, you can manually comment the line of code
indicated above and repeat the decoding step. In the next version, however,
it could make sense to add another option that allows users to activate or
deactivate from the config file this second normalization step.

Please, keep us updated!

Mirco

**Comment by HardikSailor** [comment]
@mravanelli Thank you so much for detailed explanation. Yes, when I done cmvn per utt and comment out   data_set=(data_set-np.mean(data_set,axis=0))/np.std(data_set,axis=0) in code, it worked! 

It has huge effect especially when you have mismatch training and test set and you are running test mode in chunks. Chunk-wise CMVN stats significantly affect for clean and noisy utt in test files. Otherwise for all other ASR task I am keeping cmvn option in scripts.

Thank you.

**Comment by mravanelli** [comment]
ok,
thank you for your feedback! In the next version we will add an option in
the config file to allow users to enable/disable the per-chunk
normalization.

Best,

Mirco
