### ISSUE TITLE
Questions about Speech recognition from the raw waveform with SincNet

### ISSUE THREAD

**Issue by maomaoqiuqiu** [mravanelli/pytorch-kaldi#76]
Hello, when I was running this step：“Save the raw waveform into the Kaldi ark format. To do it, you can use the save_raw_fea.py utility in our repository. The script saves the input signals into a binary Kaldi archive, keeping the alignments with the pre-computed labels. You have to run it for all the data chunks (e.g., train, dev, test). It can also specify the length of the speech chunk (sig_wlen=200 # ms) composing each frame.”
I was having this problem：
$ python save_raw_fea.py
Traceback (most recent call last):
  File "save_raw_fea.py", line 76, in <module>
    [fs,signal]=scipy.io.wavfile.read(sig_path)
  File "/home/oem/anaconda3/lib/python3.6/site-packages/scipy/io/wavfile.py", line 236, in read
    file_size, is_big_endian = _read_riff_chunk(fid)
  File "/home/oem/anaconda3/lib/python3.6/site-packages/scipy/io/wavfile.py", line 168, in _read_riff_chunk
    "understood.".format(repr(str1)))
ValueError: File format b'\x7fELF'... not understood.
Can you please help me to see what is wrong? In addition, can you describe the details of this step? Thank you very much

**Comment by mravanelli** [comment]
Hi,
could you print the variable "sig_path"? It should be a valid wav file.
