### ISSUE TITLE
Questions about Speech recognition from the raw waveform with SincNet 

### ISSUE THREAD

**Issue by maomaoqiuqiu** [mravanelli/pytorch-kaldi#77]
Hello, when I run this program：save_raw_fea.py， I can't find this file：wav_lst='/users/parcollet/KALDI/kaldi-trunk/egs/timit/s5/data/test/wav.lst'.
Can you please send me information about this document? Thank you very much!

**Comment by mravanelli** [comment]
Before running this script, you have to run the kaldi recipe to create
labels and all the other needed information. Once that you have run it, you
can find in $KALDI_ROOT/egs/timit/s5/data/test/wav.lst a file that contains
the list of wav signals to process.

Mirco

**Comment by maomaoqiuqiu** [comment]
hello,I run the kaldi recipe to create labels and all the other needed information,but I don't find the file:wav.lst,I just find wav.scp

**Comment by mravanelli** [comment]
That was.scp should work as well because it is a file containing "snt_id
snt_file"
