### ISSUE TITLE
copy-feats hmm-info not working as suggested in the documentation  

### ISSUE THREAD

**Issue by HoussBz** [mravanelli/pytorch-kaldi#78]
![scr1-1](https://user-images.githubusercontent.com/37712301/55082415-ed239680-50a1-11e9-87c2-82c66a819063.png)
I just added kaldi and cuda 10.1 to my ./bashrc .
following the documentation(that suggested to run both commands to be sure of clean install with no erros)  , I ran copy-feats , and hmm-info , but got no result . here's a screenshot . Please Help 
![scr1](https://user-images.githubusercontent.com/37712301/55082262-a7ff6480-50a1-11e9-9de0-3b93fccbbf42.png)

**Comment by mravanelli** [comment]
Hi,
have you modified your .bash file? If so, you might probably have to simply
reload it  doing (source $HOME/.bashrc)
Does it fix the problem?

Mirco

**Comment by HoussBz** [comment]
Hello sir , thanks for your reply . 
I just did , but that didnt change it . here's a screenshot 
![scr2](https://user-images.githubusercontent.com/37712301/55083065-214b8700-50a3-11e9-9464-a0066deff165.png)

**Comment by mravanelli** [comment]
You have to change the
export KALDI_ROOT=/home/mirco/kaldi-trunk

Using your path. You are currently using my paths that are reported just to
give you an example....

Mirco

**Comment by HoussBz** [comment]
Im sorry , I was a bit distracted .. so sorry .. yes , now everything works fine 
![allesgood_copy-feats _hmm-info](https://user-images.githubusercontent.com/37712301/55085006-34ac2180-50a6-11e9-89bc-b0f8c777c1f2.png)
Thank you very much !

**Comment by HoussBz** [comment]
Do I have to downgrade to CUDA 10.0 ? I just installed CUDA10.1 , and it seems that it is not supported yet by pytorch ?

**Comment by mravanelli** [comment]
You might try to see if it pytorch works....

Mirco
