### ISSUE TITLE
error while running ./run.sh after downloading TIMIT dataset

### ISSUE THREAD

**Issue by HoussBz** [mravanelli/pytorch-kaldi#79]
I just downloaded TIMIT dataset and while running ./run.sh , I got this error . if you can please tell me what went wrong . here's a screenshot . Thanks 
![quest2](https://user-images.githubusercontent.com/37712301/55094279-67f6ac80-50b6-11e9-80c8-82f8c4d33fad.png)
![quest2-2](https://user-images.githubusercontent.com/37712301/55094280-688f4300-50b6-11e9-9515-354d6bdd8f81.png)

**Comment by mravanelli** [comment]
Have you installed to kaldi tools is ~/kaldi-trunk/tools?

Mirco

**Comment by HoussBz** [comment]
did you  mean sir to put the audio TIMIT downloaded in kaldi-trunk/tools ? or in kaldi/tools ? 
then run.sh ?

**Comment by mravanelli** [comment]
No. This error probably means that you don't have installed the sph2pipe
software that you find in kaldi-trunk/tools. You should install it, along
with the other required Kaldi toolkits (see kaldi-trunk/tools/INSTALL). If
you have already installed all the toolkits make sure that your .bashrc
file contains the path to read sph2pipe.

Mirco

Mirco

**Comment by HoussBz** [comment]
I just added the path manually of sph2pipe . although I found it installed in kaldi-trunk tools . 
here's a screenshot of both the content of kaldi-trunk/tools , and my paths in bashrc .
still problems running ./run.sh . what have I done wrong please  ? 
![asking1](https://user-images.githubusercontent.com/37712301/55143664-7b018f00-513f-11e9-9f7d-8072028940b5.png)
![asking2-adding-sph2pipe](https://user-images.githubusercontent.com/37712301/55143665-7b018f00-513f-11e9-889c-b6642d1a0850.png)

**Comment by HoussBz** [comment]
could you please refer me to a source or a more explained documentation ? I  am stuck , and I need to get it up and running real soon . Thanks a lot .

**Comment by mravanelli** [comment]
are you sure that your executable has the execution permission? try
"chmod +x our_kaldi_root/tools/sph2pipe_v2.5/sph2pipe"
I think this could just be permission problem or something like this..

Let me know if this works

Mirco

**Comment by HoussBz** [comment]
I think the problem is that i did : cd kaldi/egs/timit/s5 (like in the official documentation on pytorch-kaldi) . But when I switch to kaldi-trunk/egs/timit/s5 : I got this : 
![image](https://user-images.githubusercontent.com/37712301/55175952-8923cf80-5180-11e9-81d0-cf31a154009d.png)
what am I supposed to do to make it run ?
I am new 
to both linux and ML, and I am doing a lot of efforts to implement pytorch-kaldi . I hope efforts pay off . Thank you sir .

**Comment by mravanelli** [comment]
Well, we suppose that our users have already a bit of knowledge  of linux
and kaldi (otherwise is very difficult to use our toolkit). Do you have
someone that can help you with that?

Mirco

**Comment by HoussBz** [comment]
no sir , I don't . I am all on my own , and I am doing this project as a final year project to get my engineering degree diploma .I am suposed to get everything ready before May . I am supposed to create a system that extracts named entities NER from speech . but no one here is to help , im sorry if I bothered you sir .

**Comment by raeidsaqur** [comment]
@mravanelli fyi.
@HoussBz : well, the issue is given in the message no? Open run.sh and replace line 39 with the absolute path to where you've downloaded and extracted timit.

For e.g:
#timit=/mnt/matylda2/data/TIMIT/timit # @BUT
timit=/home/raeidsaqur/Documents/data/LDC/timit/TIMIT # @RS

![image](https://user-images.githubusercontent.com/978863/55373205-6d972c80-54d2-11e9-81cd-1d26272b043f.png)

Hope that helps.

**Comment by HoussBz** [comment]
@mravanelli :   please sir , is there any way to contact you , I may have some questions , can I run pytorch-kaldi on my laptop (8Gb RAM , 2Gb GPU) . if so , how much would it take to entirely be functional ? how much would the training take approximately ? Thank you for helping .

**Comment by TParcollet** [comment]
@HoussBz You can contact us via GitHub ;) Pytorch-Kaldi can run on your laptop. Nonetheless, note that you will only be able to process very small batch_size and small architectures (or small datasets) due to your GPU which is limited to 2Gb. The longest part of he Installation of Pytorch-Kaldi, is the installation of Kaldi itself. If everything goes well, you can expect one hour of installation (Kaldi compilation). For the training time it depends on your task.

**Comment by HoussBz** [comment]
Sir , I have kaldi , pytorch , cuda10.1 , all up and running , I have
downloaded libripseech then . this is the step in which I got stuck . am I
still too far away from getting my asr ready ? am I still to far ?  im new
to this , but im doing timeless effort to get it running .
*Houssem B'ZYWISH*



* Mobile : +216 55 515 111** Courriel : houssemusbzi@gmail.com
<houssemusbzi@gmail.com>*

**Comment by TParcollet** [comment]
Well, librispeech is definitely a dataset that you won't be able to train on with a 2Go GPU. Unless you use a straightforward MLP. It will take you many weeks to train (if you manage to).

**Comment by TParcollet** [comment]
If you don't have more ressources, I would suggest to start with TIMIT and MLP models. Find an architecture that works with TIMIT on your laptop, and then apply the same architecture to librispeech. But to be honest, do not expect too much from the final performances of the model, since you will only be able to train a small network.

**Comment by HoussBz** [comment]
so is it a good idea to create an image of cuda10.1 , kaldi , pytorch , put
it on  a server , and then train it then extract the trained models and go
back to work with it on my laptop ? i dont know if that is even feasible ?
*Houssem B'ZYWISH*



* Mobile : +216 55 515 111** Courriel : houssemusbzi@gmail.com
<houssemusbzi@gmail.com>*

**Comment by TParcollet** [comment]
Usually, you will have to create your Kaldi and Pytorch-Kaldi environnement on a server. Train your model on this server, and only use your laptop to get the results back. If you train a model that takes 10Gb of VRAM, you won't be able to use it on your laptop after training. Therefore, everything will have to be done on the server.

**Comment by HoussBz** [comment]
what about if I elevate my RAM and GPU performance ? thanks

**Comment by TParcollet** [comment]
You will start doing some interesting models with 8Gb of VRAM for the GPU. For the RAM, 8 can be enough but I would say that 16Go is a good minimum.

**Comment by HoussBz** [comment]
and for the RAM : nothing to mention ? I have a 8GB RAM , and a 2GB GPU . so i just elevate my GPU to 16 GB if i understood well ,and i ll be able to do all the training and everything up and running on my laptop ? no need for a server anymore , right  ? thank you so much for your time .

**Comment by TParcollet** [comment]
To be honest, I have no idea on how you will be able to increase the amount of VRAM of your GPU. The only way is to buy a new laptop with a better GPU. Considering the price of mobile GPU with 8Go of VRAM, I would rather suggest to build a small server with Ryzen CPU / 16 or 32 Gb or RAM and a GTX 1080 Ti or RTX 2070 / 2080.

**Comment by AtefehSamadi** [comment]
Hi,
I'm very new in this field. Could you please help me how can I download the TIMIT dataset?
I tried to download the dataset from (https://catalog.ldc.upenn.edu/LDC93S1), but unfortunately  I can't find the download link.
Could you please help me
Thanks in advance 
Atefeh
