### ISSUE TITLE
voxceleb cfg

### ISSUE THREAD

**Issue by hdubey** [mravanelli/pytorch-kaldi#86]
Hi Mirco,
Thanks for this great toolkit. I am trying to re-produce some of the experiments from MI training of SincNet paper Here:https://arxiv.org/pdf/1812.00271.pdf
Is the related codes for voxCeleb available in this repo. I am interested it is as it is noiser and realistic as compared to TIMIT or Librispeech. Thanks!

**Comment by mravanelli** [comment]
It is not currently available, but we are working to extend this repository to other tasks such as speaker recognition. In the next months, you will probably find also the mutual-information approach proposed in that paper. Stay tuned!

**Comment by tombarti** [comment]
Hi Mirco,
First of all thank you for your fantastic research!
I too am very interested in reproducing some of the experiments from your paper "Learning Speaker Representations with Mutual Information", especially for speaker diarisation.
Is there any update on adding speaker recognition (and in particular speaker verification) to this repository?
Thanks!

**Comment by mravanelli** [comment]
Hi Tom,
the goal is to drastically extend the current version of pytorch-kaldi in
many different ways (including adding LIM or other self-supervised
techniques such as PASE (https://arxiv.org/abs/1904.03416)). The project
will get bigger and we already have some sponsors for that. At the
beginning of September there will be an announcement for that. Stay tuned!

Mirco

**Comment by tombarti** [comment]
Thank you for the swift reply Mirco, it is much appreciated!
I am looking forward to the September announcement, especially LIM and PASE!

**Comment by LCF2764** [comment]
Hi Mirco,
The literature "Learning Speaker Representations with Mutual Information" says that the code is open source. I haven't found the relevant code here. Is it open source now?
Trhanks!

**Comment by mravanelli** [comment]
Hi,
the plan is to put it in the speechbrain project directly
https://speechbrain.github.io/

**Comment by Soar-Sir** [comment]
Hi Mirco,
as a developer in the field of speech, I am very interested in SpeechBrain. 
So when will the public version of the code be released? 
I am looking forward to this project.
Thanks a lot!

**Comment by TParcollet** [comment]
Dear Soar-Sir,

Thank you for your interest in SpeechBrain. Due to the very complex COVID situation, we had to postpone a little bit the release. Right now, an expected period is Fall 2020.
