### ISSUE TITLE
Using Triphone alignements as a starting point for a pytorch network

### ISSUE THREAD

**Issue by mohitsharma29** [mravanelli/pytorch-kaldi#87]
Hey
I have trained my classical models in Kaldi and if I use the nnet scripts, it does give me the flexibility of using CNNs and LSTMs type architectures with classical alignments. How can I do this with PyTorch Kaldi?

**Comment by mravanelli** [comment]
Hi,
in pytorch-kaldi you can use the alignments you prefer. Take a look for instance to the TIMIT tutorial that you can find in the documentation...
