### ISSUE TITLE
CNN_feaproc shape issue

### ISSUE THREAD

**Issue by sdrobert** [mravanelli/pytorch-kaldi#9]
Hi Mirco,

I think this is a bug, but please correct me if I'm wrong.

When constructing context windows, the left and right context are constructed by flattening a slice of an input feature array of shape ``(num_frames, num_feats)``. Later, ``CNN_feaproc`` reconstructs the 2D context window by calling ``x.view(batch * steps, 1, -1, 11)``, which, as I understand it, is supposed to generate a tensor of shape ``(n, num_input_channels, num_feats, window_length)`` (11 is the fixed context window length). Since the original slice of shape ``(window_length, num_feats)`` would be flattened in c-contiguous order, asking for a view of shape ``(num_feats, window_length)`` would not recover the original slice.

Best,
Sean

**Comment by mravanelli** [comment]
Hi Sean,
we also noticed some issues with the CNN_feaproc flag. We are now working
on a new version of the code that, among the other interventions,
implements CNN directly and will allow combinations between networks (e.g.,
CNN+RNN+DNN) in a much better and more transparent way. That part of the
code will be thus removed soon....

Mirco
