### ISSUE TITLE
optparse is deprecated

### ISSUE THREAD

**Issue by dmitriy-serdyuk** [mravanelli/pytorch-kaldi#90]
`OptionParser` is [deprecated](https://docs.python.org/3/library/optparse.html) and can be discontinued any moment. They recommend to switch to `argparse` module.

It is used here https://github.com/mravanelli/pytorch-kaldi/blob/master/tune_hyperparameters.py#L17.

EDIT: Actually, I don't understand why you need `optparse` here. It seems that `sys.argv` is what you want.

**Comment by mravanelli** [comment]
Thank you Dima! We will plan to do an update in the next days and we can
fix it as well..
