### ISSUE TITLE
Code not using GPU

### ISSUE THREAD

**Issue by mohitsharma29** [mravanelli/pytorch-kaldi#92]
Hey Everyone
So, I have run the TIMIT recipe, but during the initial run, I was not able to see any GPU activity on "nvidia-smi". Is there any place where I have to set the GPU explicitly? @mravanelli

**Comment by mravanelli** [comment]
The initial part of the TIMIT recipe (egs/TIMIT/s5/run.sh) doesn't use
GPUs. It trains some GMM/HMM on CPUs. Only the DNN paper (that happens at
the end of the recipe) uses GPUs.





<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by mohitsharma29** [comment]
Thank you for a quick reply. So, after this initial phase, will it automatically use any of the available GPU? And if yes, how do I set a specific GPU (gpu:/0 or /1)?

**Comment by TParcollet** [comment]
Overall, you can use the env variable CUDA_VISIBLE_DEVICES. You can change it directly before your calling your program: CUDA_VISIBLE_DEVICES=0 ./run.sh

**Comment by mohitsharma29** [comment]
the main script is run_exp.py. Does it have such an argument which accepts CUDA_VISIBLE_DEVICES=0?

**Comment by TParcollet** [comment]
The notation CUDA_VISIBLE_DEVICES=0 is just a call before launching the program. Thus, you can do CUDA_VISIBLE_DEVICES=0 python run_exp.py. You could also create a launch.sh script that sets the device visible variable and then run the program.

**Comment by mohitsharma29** [comment]
"RuntimeError: CUDA out of memory. Tried to allocate 16.03 GiB (GPU 0; 11.91 GiB total capacity; 0 bytes already allocated; 11.35 GiB free; 0 bytes cached)"
So I am using this "CUDA_VISIBLE_DEVICES=1 python run_exp.py cfg/voxforge/TIMIT_MLP_mfcc_basic.cfg" to run the script.

1. I am explicitly setting the gpu to be used as 1. But it is still trying to run it on 0. Why is this happening?
2. How do I resolve CUDA out of memory error?

**Comment by TParcollet** [comment]
What is the model you are trying to train, and have you verified that the model is actually running on GPU 0 instead of GPU 1 ?
