### ISSUE TITLE
The Graph in Decoding

### ISSUE THREAD

**Issue by coalboss** [mravanelli/pytorch-kaldi#93]
I'm getting a doubt in the decoding section of run_exp.py. When i used kaldi, i need to make graph before decoding, but i find that HCLG.fst in decode_dnn.sh seems to have been produced in the previous experiment (exp/tri3), why i can used old  HCLG.fst? cfg is TIMIT_MLP_mfcc_basic.cfg

**Comment by mravanelli** [comment]
Hi,
the decoding graph that one must use is the one that contains the same HMM
states of the labels (i.e, if you have created the labels with tri3 you
have to use the graph created during tri3 training).

Mirco

**Comment by coalboss** [comment]
Thank you for your quick reply!
