### ISSUE TITLE
ERROR: the following tags are opened but not closed

### ISSUE THREAD

**Issue by mfch101** [mravanelli/pytorch-kaldi#94]
I download the latest version. I met the following error when running command: python run_exp.sh cfg/TIMIT_baselines/TIMIT_MLP_mfcc_basic.cfg.
ERROR: the following tags are opened but not closed! ['[cfg_proto]', '[exp]', '[dataset1]', '[dataset2]', '[dataset3]', '[data_use]', '[batches]', '[architecture1]', '[model]', '[forward]', '[decoding]']

**Comment by mravanelli** [comment]
Sorry, I accidentally pushed a work in progress version of the toolkit. Let
me go back to the previous version. Thank you very much for let me know
about this issue!

**Comment by mravanelli** [comment]
ok restored the previous version.
Thank you again!

Mirco
